add_hydrogen_caps – metalquicha
add_hydrogen_caps Subroutine
27 statements
Source File
private subroutine add_hydrogen_caps(atoms_in_fragment, bonds, sys_geom, fragment, base_atom_count)
Add hydrogen caps to fragment for broken bonds Caps are placed at the position of the atom outside the fragment
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: atoms_in_fragment(:)
0-indexed atom indices in fragment
type(bond_t), intent(in) :: bonds(:)
type(system_geometry_t), intent(in) :: sys_geom
type(physical_fragment_t), intent(inout) :: fragment
integer, intent(in) :: base_atom_count
Number of non-cap atoms
Called by
Variables
Type Visibility Attributes Name Initial
logical, private :: atom_i_in_frag
logical, private :: atom_j_in_frag
integer, private :: cap_idx
integer, private :: ibond
Source Code
   subroutine add_hydrogen_caps(atoms_in_fragment, bonds, sys_geom, fragment, base_atom_count)
      !! Add hydrogen caps to fragment for broken bonds
      !! Caps are placed at the position of the atom outside the fragment
      integer, intent(in) :: atoms_in_fragment(:)  !! 0-indexed atom indices in fragment
      type(bond_t), intent(in) :: bonds(:)
      type(system_geometry_t), intent(in) :: sys_geom
      type(physical_fragment_t), intent(inout) :: fragment
      integer, intent(in) :: base_atom_count  !! Number of non-cap atoms
      integer :: ibond, cap_idx
      logical :: atom_i_in_frag, atom_j_in_frag
      if (fragment%n_caps == 0) return
      cap_idx = 0
      do ibond = 1, size(bonds)
         if (.not. bonds(ibond)%is_broken) cycle
         atom_i_in_frag = any(atoms_in_fragment == bonds(ibond)%atom_i)
         atom_j_in_frag = any(atoms_in_fragment == bonds(ibond)%atom_j)
         if (atom_i_in_frag .and. .not. atom_j_in_frag) then
            ! atom_i is in fragment, atom_j is not  cap at position of atom_j
            cap_idx = cap_idx + 1
            fragment%element_numbers(base_atom_count + cap_idx) = 1  ! Hydrogen
            ! Place H at position of atom_j (1-indexed for coordinates array)
            fragment%coordinates(:, base_atom_count + cap_idx) = &
               sys_geom%coordinates(:, bonds(ibond)%atom_j + 1)
            fragment%cap_replaces_atom(cap_idx) = bonds(ibond)%atom_j
         else if (atom_j_in_frag .and. .not. atom_i_in_frag) then
            ! atom_j is in fragment, atom_i is not  cap at position of atom_i
            cap_idx = cap_idx + 1
            fragment%element_numbers(base_atom_count + cap_idx) = 1  ! Hydrogen
            ! Place H at position of atom_i (1-indexed for coordinates array)
            fragment%coordinates(:, base_atom_count + cap_idx) = &
               sys_geom%coordinates(:, bonds(ibond)%atom_i + 1)
            fragment%cap_replaces_atom(cap_idx) = bonds(ibond)%atom_i
         end if
      end do
   end subroutine add_hydrogen_caps
Call graph
build_fragment_from_atom_list calls add_hydrogen_caps
build_fragment_from_indices calls add_hydrogen_caps
compute_gmbe_energy_gradient calls build_fragment_from_atom_list, build_fragment_from_indices
compute_gmbe_energy_gradient_hessian calls build_fragment_from_atom_list, build_fragment_from_indices
gmbe_pie_coordinator calls build_fragment_from_atom_list
map_fragment_to_system_gradient calls build_fragment_from_indices
map_fragment_to_system_hessian calls build_fragment_from_indices
node_worker calls build_fragment_from_atom_list, build_fragment_from_indices, node_worker
serial_fragment_processor calls build_fragment_from_indices, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian, serial_fragment_processor
serial_gmbe_pie_processor calls build_fragment_from_atom_list
compute_mbe_energy_gradient calls map_fragment_to_system_gradient, compute_mbe_gradient
compute_mbe_energy_gradient_hessian calls map_fragment_to_system_gradient, map_fragment_to_system_hessian, compute_mbe_gradient, compute_mbe_hessian
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
run_fragmented_calculation calls gmbe_pie_coordinator, serial_gmbe_pie_processor, node_worker, serial_fragment_processor
global_coordinator calls compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian, global_coordinator
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation