allocate_basis_shells – metalquicha
allocate_basis_shells Subroutine
6 statements
Source File
private pure subroutine allocate_basis_shells(self, nshells)
Allocate array of shells in an atomic basis
Type Bound
atomic_basis_type
Arguments
Type Intent Optional Attributes Name
class(atomic_basis_type), intent(inout) :: self
integer, intent(in) :: nshells
Called by
Source Code
   pure subroutine allocate_basis_shells(self, nshells)
      !! Allocate array of shells in an atomic basis
      class(atomic_basis_type), intent(inout) :: self
      integer, intent(in) :: nshells
      self%nshells = nshells
      allocate (self%shells(nshells))
   end subroutine allocate_basis_shells
Call graph
copy_atomic_basis calls allocate_basis_shells
parse_element_basis calls allocate_basis_shells
build_molecular_basis calls copy_atomic_basis, parse_element_basis