apply_distance_screening – metalquicha
apply_distance_screening Subroutine
61 statements
Source File
public subroutine apply_distance_screening(polymers, total_fragments, sys_geom, driver_config, max_level)
Uses
mqc_physical_fragment
mqc_config_adapter
Apply distance-based screening to filter out fragments that exceed cutoff distances Modifies polymers array in-place and updates total_fragments count
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: polymers(:,:)
integer(kind=int64), intent(inout) :: total_fragments
type(system_geometry_t), intent(in) :: sys_geom
type(driver_config_t), intent(in) :: driver_config
integer, intent(in) :: max_level
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=dp), private :: cutoff
real(kind=dp), private :: fragment_distance
integer, private :: fragment_size
integer(kind=int64), private :: fragments_kept
integer(kind=int64), private :: fragments_screened
integer(kind=int64), private :: i
integer, private :: nmer_level
Source Code
   subroutine apply_distance_screening(polymers, total_fragments, sys_geom, driver_config, max_level)
      !! Apply distance-based screening to filter out fragments that exceed cutoff distances
      !! Modifies polymers array in-place and updates total_fragments count
      use mqc_physical_fragment, only: calculate_monomer_distance
      use mqc_config_adapter, only: driver_config_t
      integer, intent(inout) :: polymers(:, :)
      integer(int64), intent(inout) :: total_fragments
      type(system_geometry_t), intent(in) :: sys_geom
      type(driver_config_t), intent(in) :: driver_config
      integer, intent(in) :: max_level
      integer(int64) :: i, fragments_kept
      integer :: fragment_size
      real(dp) :: fragment_distance, cutoff
      integer(int64) :: fragments_screened
      integer :: nmer_level
      ! Check if we have cutoffs to apply
      if (.not. allocated(driver_config%fragment_cutoffs)) then
         return  ! No screening needed
      end if
      fragments_kept = 0_int64
      fragments_screened = 0_int64
      ! Loop through all fragments and filter based on distance
      do i = 1_int64, total_fragments
         fragment_size = count(polymers(i, :) > 0)
         ! Monomers are always kept (distance = 0)
         if (fragment_size == 1) then
            fragments_kept = fragments_kept + 1_int64
            if (fragments_kept /= i) then
               ! Compact array - move this fragment to the kept position
               polymers(fragments_kept, :) = polymers(i, :)
            end if
            cycle
         end if
         ! For n-mers (n >= 2), check if we have a cutoff and apply screening
         nmer_level = fragment_size
         if (nmer_level > size(driver_config%fragment_cutoffs)) then
            ! No cutoff defined for this level - keep the fragment
            fragments_kept = fragments_kept + 1_int64
            if (fragments_kept /= i) then
               polymers(fragments_kept, :) = polymers(i, :)
            end if
            cycle
         end if
         cutoff = driver_config%fragment_cutoffs(nmer_level)
         if (cutoff <= 0.0_dp) then
            ! Negative or zero cutoff means no screening for this level
            fragments_kept = fragments_kept + 1_int64
            if (fragments_kept /= i) then
               polymers(fragments_kept, :) = polymers(i, :)
            end if
            cycle
         end if
         ! Calculate distance for this fragment
         fragment_distance = calculate_monomer_distance(sys_geom, polymers(i, 1:fragment_size))
         ! Apply cutoff filter
         if (fragment_distance <= cutoff) then
            ! Keep this fragment
            fragments_kept = fragments_kept + 1_int64
            if (fragments_kept /= i) then
               polymers(fragments_kept, :) = polymers(i, :)
            end if
         else
            ! Screen out this fragment
            fragments_screened = fragments_screened + 1_int64
         end if
      end do
      ! Update total fragment count
      if (fragments_screened > 0) then
         call logger%info("Distance-based screening applied:")
         call logger%info("  Fragments before screening: "//to_char(total_fragments))
         call logger%info("  Fragments screened out: "//to_char(fragments_screened))
         call logger%info("  Fragments kept: "//to_char(fragments_kept))
         total_fragments = fragments_kept
      end if
   end subroutine apply_distance_screening
Call graph
apply_distance_screening calls info, calculate_monomer_distance, to_char
calculate_monomer_distance calls to_angstrom
run_fragmented_calculation calls apply_distance_screening
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations