arrays_equal_internal – metalquicha
arrays_equal_internal Function
16 statements
Source File
private pure function arrays_equal_internal(a, b, n) result(equal)
Check if two arrays are equal
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: a(:)
integer, intent(in) :: b(:)
integer, intent(in) :: n
Return Value logical
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
Source Code
   pure function arrays_equal_internal(a, b, n) result(equal)
      !! Check if two arrays are equal
      integer, intent(in) :: a(:), b(:), n
      logical :: equal
      integer :: i
      equal = .true.
      if (size(a) /= n .or. size(b) /= n) then
         equal = .false.
         return
      end if
      do i = 1, n
         if (a(i) /= b(i)) then
            equal = .false.
            return
         end if
      end do
   end function arrays_equal_internal
Call graph
fragment_lookup_find calls arrays_equal_internal
compute_mbe calls fragment_lookup_find
compute_mbe_gradient calls fragment_lookup_find
compute_mbe_hessian calls fragment_lookup_find
compute_mbe_energy calls compute_mbe
compute_mbe_energy_gradient calls compute_mbe, compute_mbe_gradient
compute_mbe_energy_gradient_hessian calls compute_mbe, compute_mbe_gradient, compute_mbe_hessian
global_coordinator calls compute_mbe_energy, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian
serial_fragment_processor calls compute_mbe_energy, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian
run_fragmented_calculation calls global_coordinator, serial_fragment_processor