atom_sets_equal – metalquicha
atom_sets_equal Function
13 statements
Source File
private function atom_sets_equal(set1, set2, n_atoms) result(equal)
Check if two atom sets are equal (assuming sorted)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: set1(:)
integer, intent(in) :: set2(:)
integer, intent(in) :: n_atoms
Return Value logical
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
Source Code
   function atom_sets_equal(set1, set2, n_atoms) result(equal)
      !! Check if two atom sets are equal (assuming sorted)
      integer, intent(in) :: set1(:), set2(:)
      integer, intent(in) :: n_atoms
      logical :: equal
      integer :: i
      equal = .true.
      do i = 1, n_atoms
         if (set1(i) /= set2(i)) then
            equal = .false.
            return
         end if
      end do
   end function atom_sets_equal
Call graph
dfs_pie_accumulate calls atom_sets_equal, dfs_pie_accumulate
gmbe_enumerate_pie_terms calls dfs_pie_accumulate
run_fragmented_calculation calls gmbe_enumerate_pie_terms
run_calculation calls run_fragmented_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation