atomic_basis_destroy – metalquicha
atomic_basis_destroy Subroutine
12 statements
Source File
private pure subroutine atomic_basis_destroy(self)
Clean up allocated memory in an atomic basis
Type Bound
atomic_basis_type
Arguments
Type Intent Optional Attributes Name
class(atomic_basis_type), intent(inout) :: self
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
Source Code
   pure subroutine atomic_basis_destroy(self)
      !! Clean up allocated memory in an atomic basis
      class(atomic_basis_type), intent(inout) :: self
      integer :: i
      if (allocated(self%shells)) then
         do i = 1, self%nshells
            call self%shells(i)%destroy()
         end do
         deallocate (self%shells)
      end if
      if (allocated(self%element)) deallocate (self%element)
      self%nshells = 0
   end subroutine atomic_basis_destroy
Call graph
atomic_basis_destroy calls cgto_destroy
basis_set_destroy calls atomic_basis_destroy
build_molecular_basis calls atomic_basis_destroy
fragment_destroy calls basis_set_destroy
fragment_set_basis calls basis_set_destroy
compute_gmbe calls fragment_destroy, process_intersection_derivatives
displaced_geometry_destroy calls fragment_destroy
gmbe_pie_coordinator calls fragment_destroy
map_fragment_to_system_dipole_derivatives calls fragment_destroy
map_fragment_to_system_gradient calls fragment_destroy
map_fragment_to_system_hessian calls fragment_destroy
node_worker calls fragment_destroy, node_worker
process_intersection_derivatives calls fragment_destroy
serial_fragment_processor calls fragment_destroy, compute_mbe, serial_fragment_processor
serial_gmbe_pie_processor calls fragment_destroy
compute_mbe calls map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
gmbe_run_distributed calls gmbe_pie_coordinator, node_worker
gmbe_run_serial calls serial_gmbe_pie_processor
global_coordinator calls compute_mbe
mbe_run_distributed calls node_worker
mbe_run_serial calls serial_fragment_processor