basis_set_destroy – metalquicha
basis_set_destroy Subroutine
11 statements
Source File
private pure subroutine basis_set_destroy(self)
Clean up allocated memory in a molecular basis set
Type Bound
molecular_basis_type
Arguments
Type Intent Optional Attributes Name
class(molecular_basis_type), intent(inout) :: self
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
Source Code
   pure subroutine basis_set_destroy(self)
      !! Clean up allocated memory in a molecular basis set
      class(molecular_basis_type), intent(inout) :: self
      integer :: i
      if (allocated(self%elements)) then
         do i = 1, self%nelements
            call self%elements(i)%destroy()
         end do
         deallocate (self%elements)
      end if
      self%nelements = 0
   end subroutine basis_set_destroy
Call graph
basis_set_destroy calls atomic_basis_destroy
atomic_basis_destroy calls cgto_destroy
fragment_destroy calls basis_set_destroy
fragment_set_basis calls basis_set_destroy
compute_gmbe calls fragment_destroy, process_intersection_derivatives
displaced_geometry_destroy calls fragment_destroy
gmbe_pie_coordinator calls fragment_destroy
map_fragment_to_system_dipole_derivatives calls fragment_destroy
map_fragment_to_system_gradient calls fragment_destroy
map_fragment_to_system_hessian calls fragment_destroy
node_worker calls fragment_destroy, node_worker
process_intersection_derivatives calls fragment_destroy
serial_fragment_processor calls fragment_destroy, compute_mbe, serial_fragment_processor
serial_gmbe_pie_processor calls fragment_destroy
compute_mbe calls map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
run_fragmented_calculation calls gmbe_pie_coordinator, serial_gmbe_pie_processor, node_worker, serial_fragment_processor
global_coordinator calls compute_mbe, global_coordinator
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation