binomial – metalquicha
binomial Function
16 statements
Source File
public pure function binomial(n, r) result(c)
Compute binomial coefficient C(n,r) = n! / (r! * (n-r)!)
Calculates “n choose r” using iterative algorithm to avoid factorial overflow for large numbers. Uses int64 to handle large combinatorial values that overflow int32.
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n
Total number of items
integer(kind=default_int), intent(in) :: r
Number of items to choose
Return Value integer(kind=int64)
Binomial coefficient result
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=default_int), private :: i
Loop counter
Source Code
   pure function binomial(n, r) result(c)
      !! Compute binomial coefficient C(n,r) = n! / (r! * (n-r)!)
      !!
      !! Calculates "n choose r" using iterative algorithm to avoid
      !! factorial overflow for large numbers.
      !! Uses int64 to handle large combinatorial values that overflow int32.
      integer(default_int), intent(in) :: n  !! Total number of items
      integer(default_int), intent(in) :: r  !! Number of items to choose
      integer(int64) :: c              !! Binomial coefficient result
      integer(default_int) :: i              !! Loop counter
      if (r == 0 .or. r == n) then
         c = 1_int64
      else if (r > n) then
         c = 0_int64
      else
         c = 1_int64
         do i = 1, r
            c = c*int(n - i + 1, int64)/int(i, int64)
         end do
      end if
   end function binomial
Call graph
get_nfrags calls binomial
run_fragmented_calculation calls binomial, get_nfrags
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations