calc_type_to_string – metalquicha
calc_type_to_string Function
14 statements
Source File
public pure function calc_type_to_string(calc_type) result(calc_type_str)
Convert calculation type integer constant to string
Provides human-readable string representation of calculation type.
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: calc_type
Input integer constant
Return Value character(len=:), allocatable
Output string representation
Called by
Source Code
   pure function calc_type_to_string(calc_type) result(calc_type_str)
      !! Convert calculation type integer constant to string
      !!
      !! Provides human-readable string representation of calculation type.
      integer(int32), intent(in) :: calc_type         !! Input integer constant
      character(len=:), allocatable :: calc_type_str  !! Output string representation
      select case (calc_type)
      case (CALC_TYPE_ENERGY)
         calc_type_str = "energy"
      case (CALC_TYPE_GRADIENT)
         calc_type_str = "gradient"
      case (CALC_TYPE_HESSIAN)
         calc_type_str = "hessian"
      case default
         calc_type_str = "unknown"
      end select
   end function calc_type_to_string
Call graph
do_fragment_work calls calc_type_to_string, do_fragment_work
run_unfragmented_calculation calls calc_type_to_string, unfragmented_calculation
serial_fragment_processor calls calc_type_to_string, do_fragment_work, serial_fragment_processor
serial_gmbe_pie_processor calls calc_type_to_string, do_fragment_work
gmbe_run_serial calls serial_gmbe_pie_processor
run_calculation calls run_unfragmented_calculation
compute_energy_and_forces calls run_calculation
mbe_run_serial calls serial_fragment_processor
node_worker calls do_fragment_work, node_worker
run_multi_molecule_calculations calls run_calculation
unfragmented_calculation calls do_fragment_work, unfragmented_calculation
main calls run_calculation, run_multi_molecule_calculations
gmbe_run_distributed calls node_worker
mbe_run_distributed calls node_worker