cgto_destroy – metalquicha
cgto_destroy Subroutine
7 statements
Source File
private pure subroutine cgto_destroy(self)
Clean up allocated memory in a CGTO
Type Bound
cgto_type
Arguments
Type Intent Optional Attributes Name
class(cgto_type), intent(inout) :: self
Called by
Source Code
   pure subroutine cgto_destroy(self)
      !! Clean up allocated memory in a CGTO
      class(cgto_type), intent(inout) :: self
      if (allocated(self%exponents)) deallocate (self%exponents)
      if (allocated(self%coefficients)) deallocate (self%coefficients)
      self%nfunc = 0
      self%ang_mom = 0
   end subroutine cgto_destroy
Call graph
atomic_basis_destroy calls cgto_destroy
basis_set_destroy calls atomic_basis_destroy
build_molecular_basis calls atomic_basis_destroy
fragment_destroy calls basis_set_destroy
fragment_set_basis calls basis_set_destroy
compute_gmbe calls fragment_destroy, process_intersection_derivatives
displaced_geometry_destroy calls fragment_destroy
gmbe_pie_coordinator calls fragment_destroy
map_fragment_to_system_dipole_derivatives calls fragment_destroy
map_fragment_to_system_gradient calls fragment_destroy
map_fragment_to_system_hessian calls fragment_destroy
node_worker calls fragment_destroy, node_worker
process_intersection_derivatives calls fragment_destroy
serial_fragment_processor calls fragment_destroy, serial_fragment_processor
serial_gmbe_pie_processor calls fragment_destroy
compute_mbe calls map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
gmbe_run_distributed calls gmbe_pie_coordinator
gmbe_run_serial calls serial_gmbe_pie_processor