cgto_allocate_arrays – metalquicha
cgto_allocate_arrays Subroutine
7 statements
Source File
private pure subroutine cgto_allocate_arrays(self, nfunc)
Allocate arrays for exponents and coefficients in a CGTO
Type Bound
cgto_type
Arguments
Type Intent Optional Attributes Name
class(cgto_type), intent(inout) :: self
integer, intent(in) :: nfunc
Called by
Source Code
   pure subroutine cgto_allocate_arrays(self, nfunc)
      !! Allocate arrays for exponents and coefficients in a CGTO
      class(cgto_type), intent(inout) :: self
      integer, intent(in) :: nfunc
      self%nfunc = nfunc
      allocate (self%exponents(nfunc))
      allocate (self%coefficients(nfunc))
   end subroutine cgto_allocate_arrays
Call graph
copy_atomic_basis calls cgto_allocate_arrays
fill_element_basis calls cgto_allocate_arrays
build_molecular_basis calls copy_atomic_basis, parse_element_basis
parse_element_basis calls fill_element_basis