combine_util – metalquicha
combine_util Subroutine
15 statements
Source File
private recursive subroutine combine_util(arr, n, r, index, data, i, out_array, count)
Utility for generating combinations recursively Uses int64 for count to handle large numbers of combinations that overflow int32.
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: arr(:)
integer(kind=default_int), intent(in) :: n
integer(kind=default_int), intent(in) :: r
integer(kind=default_int), intent(in) :: index
integer(kind=default_int), intent(inout) :: data(:)
integer(kind=default_int), intent(in) :: i
integer(kind=default_int), intent(inout) :: out_array(:,:)
integer(kind=int64), intent(inout) :: count
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=default_int), private :: j
Source Code
   recursive subroutine combine_util(arr, n, r, index, data, i, out_array, count)
      !! Utility for generating combinations recursively
      !! Uses int64 for count to handle large numbers of combinations that overflow int32.
      integer(default_int), intent(in) :: arr(:), n, r, index, i
      integer(default_int), intent(inout) :: data(:), out_array(:, :)
      integer(int64), intent(inout) :: count
      integer(default_int) :: j
      if (index > r) then
         count = count + 1_int64
         out_array(count, 1:r) = data(1:r)
         return
      end if
      do j = i, n
         data(index) = arr(j)
         call combine_util(arr, n, r, index + 1, data, j + 1, out_array, count)
      end do
   end subroutine combine_util
Call graph
combine_util calls combine_util
combine calls combine_util
generate_fragment_list calls combine
run_fragmented_calculation calls combine, generate_fragment_list
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations