compute_delta_nbody – metalquicha
compute_delta_nbody Function
16 statements
Source File
private pure recursive function compute_delta_nbody(fragment, polymers, energies, fragment_count, n) result(delta_E)
Compute general n-body correction using recursion deltaE(i1,i2,…,in) = E(i1,i2,…,in) - sum over all proper subsets of deltaE or E For n=2: deltaE(ij) = E(ij) - E(i) - E(j) For n=3: deltaE(ijk) = E(ijk) - deltaE(ij) - deltaE(ik) - deltaE(jk) - E(i) - E(j) - E(k) For n>=4: same pattern recursively Uses int64 for fragment_count to handle large fragment counts that overflow int32.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fragment(:)
integer, intent(in) :: polymers(:,:)
real(kind=dp), intent(in) :: energies(:)
integer(kind=int64), intent(in) :: fragment_count
integer, intent(in) :: n
Return Value real(kind=dp)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=dp), private :: E_n
integer, private :: i
integer(kind=int64), private :: idx_n
integer, private, allocatable :: indices(:)
integer, private :: j
integer, private :: num_subsets
integer, private, allocatable :: subset(:)
real(kind=dp), private :: subset_contribution
integer, private :: subset_size
Source Code
   pure recursive function compute_delta_nbody(fragment, polymers, energies, fragment_count, n) result(delta_E)
      !! Compute general n-body correction using recursion
      !! deltaE(i1,i2,...,in) = E(i1,i2,...,in)
      !!                        - sum over all proper subsets of deltaE or E
      !! For n=2: deltaE(ij) = E(ij) - E(i) - E(j)
      !! For n=3: deltaE(ijk) = E(ijk) - deltaE(ij) - deltaE(ik) - deltaE(jk) - E(i) - E(j) - E(k)
      !! For n>=4: same pattern recursively
      !! Uses int64 for fragment_count to handle large fragment counts that overflow int32.
      integer, intent(in) :: fragment(:), polymers(:, :), n
      integer(int64), intent(in) :: fragment_count
      real(dp), intent(in) :: energies(:)
      real(dp) :: delta_E
      integer(int64) :: idx_n
      integer :: subset_size, i, j, num_subsets
      integer, allocatable :: subset(:), indices(:)
      real(dp) :: E_n, subset_contribution
      ! Find the energy of this n-mer
      idx_n = find_fragment_index(fragment, polymers, fragment_count, n)
      E_n = energies(idx_n)
      ! Start with the full n-mer energy
      delta_E = E_n
      ! Subtract contributions from all proper subsets (size 1 to n-1)
      do subset_size = 1, n - 1
         ! Generate all subsets of this size and subtract their contributions
         call generate_and_subtract_subsets(fragment, subset_size, n, polymers, energies, &
                                            fragment_count, delta_E)
      end do
   end function compute_delta_nbody
Call graph
compute_delta_nbody calls find_fragment_index, generate_and_subtract_subsets
generate_and_subtract_subsets calls compute_delta_nbody, find_fragment_index, get_next_combination
compute_mbe_energy calls compute_delta_nbody
global_coordinator calls compute_mbe_energy
serial_fragment_processor calls compute_mbe_energy
run_fragmented_calculation calls global_coordinator, serial_fragment_processor
run_calculation calls run_fragmented_calculation
main calls run_calculation