compute_gmbe_energy_gradient_hessian – metalquicha
compute_gmbe_energy_gradient_hessian Subroutine
149 statements
Source File
public subroutine compute_gmbe_energy_gradient_hessian(monomers, n_monomers, monomer_results, n_intersections, intersection_results, intersection_sets, intersection_levels, sys_geom, total_energy, total_gradient, total_hessian, bonds)
Uses
pic_logger
mqc_physical_fragment
mqc_result_types
mqc_gmbe_utils
mqc_config_parser
mqc_error
Compute GMBE energy, gradient, and Hessian with full inclusion-exclusion TODO: Full implementation with intersection Hessians pending
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: monomers(:)
integer, intent(in) :: n_monomers
type(calculation_result_t), intent(in) :: monomer_results(:)
integer, intent(in) :: n_intersections
type(calculation_result_t), intent(in), optional :: intersection_results(:)
integer, intent(in), optional :: intersection_sets(:,:)
integer, intent(in), optional :: intersection_levels(:)
type(system_geometry_t), intent(in) :: sys_geom
real(kind=dp), intent(out) :: total_energy
real(kind=dp), intent(out) :: total_gradient(:,:)
real(kind=dp), intent(out) :: total_hessian(:,:)
type(bond_t), intent(in), optional :: bonds(:)
Calls
Variables
Type Visibility Attributes Name Initial
integer, private :: current_log_level
type(error_t), private :: error
type(physical_fragment_t), private :: fragment
integer, private :: hess_dim
integer, private :: i
integer, private :: k
integer, private, allocatable :: level_counts(:)
real(kind=dp), private, allocatable :: level_energies(:)
integer, private :: max_level
real(kind=dp), private :: monomer_energy
integer, private, allocatable :: monomer_idx(:)
real(kind=dp), private :: sign_factor
Source Code
   subroutine compute_gmbe_energy_gradient_hessian(monomers, n_monomers, monomer_results, &
                                                   n_intersections, intersection_results, &
                                                   intersection_sets, intersection_levels, &
                                                   sys_geom, total_energy, total_gradient, total_hessian, bonds)
      !! Compute GMBE energy, gradient, and Hessian with full inclusion-exclusion
      !! TODO: Full implementation with intersection Hessians pending
      use mqc_result_types, only: calculation_result_t
      use mqc_physical_fragment, only: build_fragment_from_indices, redistribute_cap_gradients, &
                                       redistribute_cap_hessian, build_fragment_from_atom_list
      use mqc_gmbe_utils, only: find_fragment_intersection
      use mqc_config_parser, only: bond_t
      use mqc_error, only: error_t
      use pic_logger, only: info_level
      integer, intent(in) :: monomers(:)
      integer, intent(in) :: n_monomers
      type(calculation_result_t), intent(in) :: monomer_results(:)
      integer, intent(in) :: n_intersections
      type(calculation_result_t), intent(in), optional :: intersection_results(:)
      integer, intent(in), optional :: intersection_sets(:, :)
      integer, intent(in), optional :: intersection_levels(:)
      type(system_geometry_t), intent(in) :: sys_geom
      real(dp), intent(out) :: total_energy
      real(dp), intent(out) :: total_gradient(:, :)
      real(dp), intent(out) :: total_hessian(:, :)
      type(bond_t), intent(in), optional :: bonds(:)
      integer :: i, k, max_level, current_log_level, hess_dim
      real(dp) :: monomer_energy
      real(dp), allocatable :: level_energies(:)
      integer, allocatable :: level_counts(:)
      real(dp) :: sign_factor
      type(physical_fragment_t) :: fragment
      type(error_t) :: error
      integer, allocatable :: monomer_idx(:)
      ! Zero out outputs
      total_gradient = 0.0_dp
      total_hessian = 0.0_dp
      hess_dim = 3*sys_geom%total_atoms
      ! Sum monomer energies, gradients, and Hessians
      monomer_energy = 0.0_dp
      do i = 1, n_monomers
         monomer_energy = monomer_energy + monomer_results(i)%energy%total()
         ! Accumulate monomer gradients
         if (monomer_results(i)%has_gradient) then
            allocate (monomer_idx(1))
            monomer_idx(1) = monomers(i)
            call build_fragment_from_indices(sys_geom, monomer_idx, fragment, error, bonds)
            if (error%has_error()) then
               call logger%error(error%get_full_trace())
               error stop "Failed to build monomer fragment in GMBE gradient+Hessian"
            end if
            call redistribute_cap_gradients(fragment, monomer_results(i)%gradient, total_gradient)
            if (monomer_results(i)%has_hessian) then
               call redistribute_cap_hessian(fragment, monomer_results(i)%hessian, total_hessian)
            end if
            call fragment%destroy()
            deallocate (monomer_idx)
         end if
      end do
      total_energy = monomer_energy
      if (n_intersections > 0 .and. present(intersection_results) .and. &
          present(intersection_sets) .and. present(intersection_levels)) then
         max_level = maxval(intersection_levels)
         allocate (level_energies(2:max_level))
         allocate (level_counts(2:max_level))
         level_energies = 0.0_dp
         level_counts = 0
         do i = 1, n_intersections
            k = intersection_levels(i)
            sign_factor = real((-1)**(k + 1), dp)
            level_energies(k) = level_energies(k) + intersection_results(i)%energy%total()
            level_counts(k) = level_counts(k) + 1
            if (intersection_results(i)%has_gradient .or. intersection_results(i)%has_hessian) then
               block
                  integer :: j, current_n, next_n, n_intersect
                  integer, allocatable :: current_atoms(:), next_atoms(:), intersect_atoms(:)
                  real(dp), allocatable :: term_gradient(:, :), term_hessian(:, :)
                  logical :: has_intersection
                  type(physical_fragment_t) :: inter_fragment
                  type(error_t) :: inter_error
                  call get_monomer_atom_list(sys_geom, intersection_sets(1, i), current_atoms, current_n)
                  if (current_n > 0) then
                     do j = 2, k
                        call get_monomer_atom_list(sys_geom, intersection_sets(j, i), next_atoms, next_n)
                        has_intersection = find_fragment_intersection(current_atoms, current_n, &
                                                                      next_atoms, next_n, &
                                                                      intersect_atoms, n_intersect)
                        deallocate (current_atoms, next_atoms)
                        if (.not. has_intersection) then
                           current_n = 0
                           exit
                        end if
                        current_n = n_intersect
                        allocate (current_atoms(current_n))
                        current_atoms = intersect_atoms
                        deallocate (intersect_atoms)
                     end do
                  end if
                  if (current_n > 0) then
                     call build_fragment_from_atom_list(sys_geom, current_atoms, current_n, &
                                                        inter_fragment, inter_error, bonds)
                     if (inter_error%has_error()) then
                        call logger%error(inter_error%get_full_trace())
                        error stop "Failed to build intersection fragment in GMBE gradient+Hessian"
                     end if
                     if (intersection_results(i)%has_gradient) then
                        allocate (term_gradient(3, sys_geom%total_atoms))
                        term_gradient = 0.0_dp
                        call redistribute_cap_gradients(inter_fragment, intersection_results(i)%gradient, &
                                                        term_gradient)
                        total_gradient = total_gradient + sign_factor*term_gradient
                        deallocate (term_gradient)
                     end if
                     if (intersection_results(i)%has_hessian) then
                        allocate (term_hessian(hess_dim, hess_dim))
                        term_hessian = 0.0_dp
                        call redistribute_cap_hessian(inter_fragment, intersection_results(i)%hessian, &
                                                      term_hessian)
                        total_hessian = total_hessian + sign_factor*term_hessian
                        deallocate (term_hessian)
                     end if
                     call inter_fragment%destroy()
                  else
                     call logger%warning("GMBE intersection has no atoms; skipping derivatives")
                  end if
                  if (allocated(current_atoms)) deallocate (current_atoms)
               end block
            end if
         end do
         do k = 2, max_level
            if (level_counts(k) > 0) then
               sign_factor = real((-1)**(k + 1), dp)
               total_energy = total_energy + sign_factor*level_energies(k)
            end if
         end do
         call logger%info("GMBE Energy breakdown (Inclusion-Exclusion Principle):")
         block
            character(len=256) :: line
            write (line, '(a,i0,a,f20.10)') "  Monomers (", n_monomers, "):  ", monomer_energy
            call logger%info(trim(line))
            do k = 2, max_level
               if (level_counts(k) > 0) then
                  sign_factor = real((-1)**(k + 1), dp)
                  if (sign_factor > 0.0_dp) then
                     write (line, '(a,i0,a,i0,a,f20.10)') "  ", k, "-way  (", level_counts(k), "):  +", level_energies(k)
                  else
                     write (line, '(a,i0,a,i0,a,f20.10)') "  ", k, "-way  (", level_counts(k), "):  ", level_energies(k)
                  end if
                  call logger%info(trim(line))
               end if
            end do
            write (line, '(a,f20.10)') "  Total GMBE:      ", total_energy
            call logger%info(trim(line))
         end block
         deallocate (level_energies, level_counts)
      else
         call logger%info("GMBE Energy breakdown:")
         call logger%info("  Monomers ("//to_char(n_monomers)//"): "//to_char(monomer_energy))
         call logger%info("  Total GMBE:  "//to_char(total_energy))
      end if
      ! Print info
      call logger%info("GMBE gradient computation completed")
      call logger%info("  Total gradient norm: "//to_char(sqrt(sum(total_gradient**2))))
      call logger%info("GMBE Hessian computation completed")
      call logger%info("  Total Hessian Frobenius norm: "//to_char(sqrt(sum(total_hessian**2))))
   end subroutine compute_gmbe_energy_gradient_hessian
Call graph
compute_gmbe_energy_gradient_hessian calls current_atoms, error, info, intersect_atoms, next_atoms, build_fragment_from_atom_list, build_fragment_from_indices, energy_total, error_get_full_trace, error_has_error, find_fragment_intersection, fragment_destroy, get_monomer_atom_list, redistribute_cap_gradients, redistribute_cap_hessian, term_gradient, term_hessian, to_char, warning
build_fragment_from_atom_list calls error_has_error, add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
build_fragment_from_indices calls error_has_error, add_hydrogen_caps, calculate_monomer_distance, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
energy_total calls mp2_total
error_get_full_trace calls error_has_error
fragment_destroy calls basis_set_destroy
basis_set_destroy calls atomic_basis_destroy
calculate_monomer_distance calls to_angstrom
check_duplicate_atoms calls error, to_char, element_number_to_symbol, error_set
atomic_basis_destroy calls cgto_destroy