compute_mbe_energy – metalquicha
compute_mbe_energy Subroutine
69 statements
Source File
public subroutine compute_mbe_energy(polymers, fragment_count, max_level, results, total_energy)
Uses
mqc_result_types
Compute the many-body expansion (MBE) energy Total = sum(E(i)) + sum(deltaE(ij)) + sum(deltaE(ijk)) + … General n-body correction: deltaE(i1,i2,…,in) = E(i1,i2,…,in) - sum of all lower-order terms Uses int64 for fragment_count to handle large fragment counts that overflow int32. Detailed breakdown is printed only if logger level is verbose or higher.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: polymers(:,:)
integer(kind=int64), intent(in) :: fragment_count
integer, intent(in) :: max_level
type(calculation_result_t), intent(in) :: results(:)
real(kind=dp), intent(out) :: total_energy
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: current_log_level
real(kind=dp), private :: delta_E
real(kind=dp), private, allocatable :: delta_energies(:)
logical, private :: do_detailed_print
real(kind=dp), private, allocatable :: energies(:)
integer, private :: fragment_size
integer(kind=int64), private :: i
type(fragment_lookup_t), private :: lookup
type(timer_type), private :: lookup_timer
integer, private :: nlevel
real(kind=dp), private, allocatable :: sum_by_level(:)
Source Code
   subroutine compute_mbe_energy(polymers, fragment_count, max_level, results, total_energy)
      !! Compute the many-body expansion (MBE) energy
      !! Total = sum(E(i)) + sum(deltaE(ij)) + sum(deltaE(ijk)) + ...
      !! General n-body correction:
      !! deltaE(i1,i2,...,in) = E(i1,i2,...,in) - sum of all lower-order terms
      !! Uses int64 for fragment_count to handle large fragment counts that overflow int32.
      !! Detailed breakdown is printed only if logger level is verbose or higher.
      use mqc_result_types, only: calculation_result_t
      integer(int64), intent(in) :: fragment_count
      integer, intent(in) :: polymers(:, :), max_level
      type(calculation_result_t), intent(in) :: results(:)
      real(dp), intent(out) :: total_energy
      integer(int64) :: i
      integer :: fragment_size, nlevel, current_log_level
      real(dp), allocatable :: sum_by_level(:), delta_energies(:), energies(:)
      real(dp) :: delta_E
      logical :: do_detailed_print
      type(fragment_lookup_t) :: lookup
      type(timer_type) :: lookup_timer
      call logger%configuration(level=current_log_level)
      do_detailed_print = (current_log_level >= verbose_level)
      allocate (sum_by_level(max_level))
      allocate (delta_energies(fragment_count))
      allocate (energies(fragment_count))
      sum_by_level = 0.0_dp
      delta_energies = 0.0_dp
      ! Extract total energies from results
      do i = 1_int64, fragment_count
         energies(i) = results(i)%energy%total()
      end do
      ! Build hash table for fast fragment lookups
      call lookup_timer%start()
      call lookup%init(fragment_count)
      do i = 1_int64, fragment_count
         fragment_size = count(polymers(i, :) > 0)
         call lookup%insert(polymers(i, :), fragment_size, i)
      end do
      call lookup_timer%stop()
      call logger%debug("Time to build lookup table: "//to_char(lookup_timer%get_elapsed_time())//" s")
      call logger%debug("Hash table size: "//to_char(lookup%table_size)// &
                        ", entries: "//to_char(lookup%n_entries))
      ! Bottom-up computation: process fragments by size (1-body, then 2-body, then 3-body, etc.)
      ! This makes the algorithm independent of input fragment order
      ! We process by n-mer level to ensure all subsets are computed before they're needed
      do nlevel = 1, max_level
         do i = 1_int64, fragment_count
            fragment_size = count(polymers(i, :) > 0)
            ! Only process fragments of the current nlevel
            if (fragment_size /= nlevel) cycle
            if (fragment_size == 1) then
               ! 1-body: deltaE = E (no subsets to subtract)
               delta_energies(i) = energies(i)
               sum_by_level(1) = sum_by_level(1) + delta_energies(i)
            else if (fragment_size >= 2 .and. fragment_size <= max_level) then
               ! n-body: deltaE = E - sum(all subset deltaEs)
               ! All subsets have already been computed in previous nlevel iterations
               delta_E = compute_mbe(i, polymers(i, 1:fragment_size), lookup, &
                                     energies, delta_energies, fragment_size)
               delta_energies(i) = delta_E
               sum_by_level(fragment_size) = sum_by_level(fragment_size) + delta_E
            end if
         end do
      end do
      ! Clean up lookup table
      call lookup%destroy()
      total_energy = sum(sum_by_level)
      ! Print text summary to console
      call logger%info("MBE Energy breakdown:")
      do nlevel = 1, max_level
         if (abs(sum_by_level(nlevel)) > 1e-15_dp) then
            block
               character(len=256) :: energy_line
               write (energy_line, '(a,i0,a,f20.10)') "  ", nlevel, "-body:  ", sum_by_level(nlevel)
               call logger%info(trim(energy_line))
            end block
         end if
      end do
      block
         character(len=256) :: total_line
         write (total_line, '(a,f20.10)') "  Total:   ", total_energy
         call logger%info(trim(total_line))
      end block
      ! Print detailed breakdown if requested
      if (do_detailed_print) then
         call print_detailed_breakdown(polymers, fragment_count, max_level, energies, delta_energies)
      end if
      ! Always write JSON file for machine-readable output
      call print_detailed_breakdown_json(polymers, fragment_count, max_level, energies, delta_energies, &
                                         sum_by_level, total_energy, results=results)
      deallocate (sum_by_level, delta_energies, energies)
   end subroutine compute_mbe_energy
Call graph
compute_mbe_energy calls configuration, debug, get_elapsed_time, info, compute_mbe, energy_total, fragment_lookup_destroy, fragment_lookup_init, fragment_lookup_insert, print_detailed_breakdown, print_detailed_breakdown_json, start, to_char
compute_mbe calls error, fragment_lookup_find, get_next_combination
energy_total calls mp2_total
fragment_lookup_init calls next_prime_internal
fragment_lookup_insert calls fnv_1a_hash, sort
print_detailed_breakdown calls header, level_name, get_frag_level_name, verbose, warning
print_detailed_breakdown_json calls info, error, get_basename, get_frag_level_name, get_output_json_filename, warning
fragment_lookup_find calls fnv_1a_hash, sort, arrays_equal_internal
global_coordinator calls compute_mbe_energy, global_coordinator
serial_fragment_processor calls compute_mbe_energy, serial_fragment_processor
run_fragmented_calculation calls global_coordinator, serial_fragment_processor
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation