compute_energy_and_forces – metalquicha
compute_energy_and_forces Subroutine
33 statements
Source File
public subroutine compute_energy_and_forces(sys_geom, driver_config, resources, energy, gradient, hessian, bonds)
Uses
mqc_config_adapter
mqc_driver
Compute energy and forces for current geometry This is the main interface for optimization/dynamics codes
Master rank provides updated geometry, all ranks compute fragments, results are returned on master rank only
Usage: 1. Master rank updates sys_geom%coordinates 2. Call this subroutine (all ranks) 3. Master rank receives energy/gradient/hessian 4. Master rank updates geometry based on forces 5. Repeat from step 1
Arguments
Type Intent Optional Attributes Name
type(system_geometry_t), intent(inout) :: sys_geom
type(driver_config_t), intent(in) :: driver_config
type(resources_t), intent(in) :: resources
real(kind=dp), intent(out) :: energy
real(kind=dp), intent(out), optional :: gradient(:,:)
(3, total_atoms)
real(kind=dp), intent(out), optional :: hessian(:,:)
(3total_atoms, 3total_atoms)
type(bond_t), intent(in), optional :: bonds(:)
Calls
Variables
Type Visibility Attributes Name Initial
logical, private :: need_gradient
logical, private :: need_hessian
type(calculation_result_t), private :: result
Source Code
   subroutine compute_energy_and_forces(sys_geom, driver_config, resources, &
                                        energy, gradient, hessian, bonds)
      !! Compute energy and forces for current geometry
      !! This is the main interface for optimization/dynamics codes
      !!
      !! Master rank provides updated geometry, all ranks compute fragments,
      !! results are returned on master rank only
      !!
      !! Usage:
      !!   1. Master rank updates sys_geom%coordinates
      !!   2. Call this subroutine (all ranks)
      !!   3. Master rank receives energy/gradient/hessian
      !!   4. Master rank updates geometry based on forces
      !!   5. Repeat from step 1
      use mqc_driver, only: run_calculation
      use mqc_config_adapter, only: driver_config_t
      type(system_geometry_t), intent(inout) :: sys_geom
      type(driver_config_t), intent(in) :: driver_config
      type(resources_t), intent(in) :: resources
      real(dp), intent(out) :: energy
      real(dp), intent(out), optional :: gradient(:, :)  !! (3, total_atoms)
      real(dp), intent(out), optional :: hessian(:, :)  !! (3*total_atoms, 3*total_atoms)
      type(bond_t), intent(in), optional :: bonds(:)
      type(calculation_result_t) :: result
      logical :: need_gradient, need_hessian
      ! Determine what we need based on what's requested
      need_gradient = present(gradient)
      need_hessian = present(hessian)
      ! Synchronize geometry from master to all ranks
      ! (Master may have updated coordinates for optimization/dynamics)
      call sync_geometry_to_workers(sys_geom, resources%mpi_comms%world_comm)
      ! Call the main calculation driver
      ! This handles both fragmented and unfragmented cases
      call run_calculation(resources, driver_config, sys_geom, bonds, result)
      ! Extract results (only valid on master rank)
      if (resources%mpi_comms%world_comm%rank() == 0) then
         energy = result%energy%total()
         if (need_gradient .and. result%has_gradient) then
            gradient = result%gradient
         else if (need_gradient) then
            call logger%error("Gradient requested but not computed!")
            call abort_comm(resources%mpi_comms%world_comm, 1)
         end if
         if (need_hessian .and. result%has_hessian) then
            hessian = result%hessian
         else if (need_hessian) then
            call logger%error("Hessian requested but not computed!")
            call abort_comm(resources%mpi_comms%world_comm, 1)
         end if
         ! Clean up
         call result%destroy()
      end if
   end subroutine compute_energy_and_forces
Call graph
compute_energy_and_forces calls abort_comm, error, energy_total, result_destroy, run_calculation, sync_geometry_to_workers
energy_total calls mp2_total
result_destroy calls result_reset
run_calculation calls info, omp_set_num_threads, json_output_data_destroy, run_fragmented_calculation, run_unfragmented_calculation, write_json_output, xtb_has_solvation, to_char, warning
json_output_data_destroy calls json_output_data_reset
result_reset calls energy_reset, error_clear
run_fragmented_calculation calls abort_comm, error, info, omp_set_num_threads, to_char, allgather, bcast, global_coordinator, node_coordinator, node_worker, serial_fragment_processor, leader, omp_get_max_threads, apply_distance_screening, binomial, combine, create_monomer_list, error_get_message, error_has_error, generate_fragment_list, get_nfrags, gmbe_enumerate_pie_terms, gmbe_pie_coordinator, serial_gmbe_pie_processor, sort_fragments_by_size, verbose
run_unfragmented_calculation calls info, to_char, distributed_unfragmented_hessian, unfragmented_calculation, calc_type_to_string, verbose
write_json_output calls error, write_gmbe_pie_json_impl, write_mbe_breakdown_json_impl, write_unfragmented_json_impl, write_vibrational_json_impl
distributed_unfragmented_hessian calls distributed_unfragmented_hessian, barrier, hessian_coordinator, hessian_worker
global_coordinator calls global_coordinator, abort_comm, error, info, to_char, error_get_message, verbose, destroy, get_elapsed_time, iprobe, irecv, isend, result_irecv, start, allocate_dipole, allocate_gradient, allocate_hessian, debug, compute_mbe, send_fragment_to_node, send_fragment_to_worker
node_coordinator calls node_coordinator, abort_comm, error, to_char, error_get_message, iprobe, irecv, isend, result_irecv, result_isend, recv
node_worker calls node_worker, abort_comm, error, to_char, error_has_error, do_fragment_work, irecv, isend, build_fragment_from_atom_list, error_get_full_trace, fragment_destroy, build_fragment_from_indices, result_isend, recv
serial_fragment_processor calls serial_fragment_processor, error, energy_total, info, omp_set_num_threads, to_char, omp_get_max_threads, calc_type_to_string, error_get_message, error_has_error, verbose, configuration, get_elapsed_time, do_fragment_work, error_get_full_trace, fragment_destroy, start, build_fragment_from_indices, compute_mbe, mbe_result_allocate_dipole, mbe_result_allocate_gradient, mbe_result_allocate_hessian
unfragmented_calculation calls unfragmented_calculation, error, energy_total, result_destroy, info, to_char, error_get_message, error_has_error, cart_disp, configuration, fc_mdyne, force_constants, frequencies, do_fragment_work, compute_thermochemistry, compute_vibrational_analysis, error_get_full_trace, print_vibrational_analysis, reduced_masses, eigenvalues, ir_intensities, check_duplicate_atoms, compute_vibrational_frequencies, fragment_compute_nelec, projected_hessian
apply_distance_screening calls info, to_char, fragment_should_be_screened
combine calls combine_util
energy_reset calls mp2_reset
generate_fragment_list calls combine
get_nfrags calls binomial
gmbe_enumerate_pie_terms calls info, to_char, error_has_error, atom_list, compute_polymer_atoms, dfs_pie_accumulate, error_set
gmbe_pie_coordinator calls abort_comm, error, energy_total, info, to_char, error_get_message, verbose, cart_disp, configuration, fc_mdyne, force_constants, frequencies, get_elapsed_time, iprobe, irecv, isend, build_fragment_from_atom_list, compute_thermochemistry, compute_vibrational_analysis, fragment_destroy, print_vibrational_analysis, redistribute_cap_dipole_derivatives, redistribute_cap_gradients, redistribute_cap_hessian, result_irecv, send_pie_term_to_node, send_pie_term_to_worker, reduced_masses, start
serial_gmbe_pie_processor calls error, energy_total, info, to_char, calc_type_to_string, error_get_message, error_has_error, verbose, cart_disp, configuration, fc_mdyne, force_constants, frequencies, do_fragment_work, build_fragment_from_atom_list, compute_thermochemistry, compute_vibrational_analysis, error_get_full_trace, fragment_destroy, print_vibrational_analysis, redistribute_cap_dipole_derivatives, redistribute_cap_gradients, redistribute_cap_hessian, reduced_masses
sort_fragments_by_size calls info, sort_index
write_gmbe_pie_json_impl calls error, info, add, create_array, create_object, destroy, initialize, get_basename, get_output_json_filename
write_mbe_breakdown_json_impl calls error, info, warning, add, create_array, create_object, destroy, initialize, get_basename, get_frag_level_name, get_output_json_filename
write_unfragmented_json_impl calls error, info, add, create_object, destroy, initialize, get_basename, get_output_json_filename
write_vibrational_json_impl calls error, info, add, create_object, destroy, initialize, get_basename, get_output_json_filename
do_fragment_work calls do_fragment_work
build_fragment_from_atom_list calls error_has_error, add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
combine_util calls combine_util
compute_thermochemistry calls compute_electronic_entropy, compute_moments_of_inertia, compute_partition_functions, compute_rotational_constants, compute_rotational_thermo, compute_translational_thermo, compute_vibrational_thermo, compute_zpe
compute_vibrational_analysis calls compute_cartesian_displacements, compute_force_constants, compute_ir_intensities, compute_reduced_masses, compute_vibrational_frequencies
dfs_pie_accumulate calls error_has_error, dfs_pie_accumulate, new_clique, atom_sets_equal, grow_pie_storage, intersect_atom_lists, test_intersect
error_get_full_trace calls error_has_error
fragment_destroy calls basis_set_destroy
fragment_should_be_screened calls calculate_monomer_distance, get_next_combination
print_vibrational_analysis calls info, warning, compute_thermochemistry, element_number_to_symbol, print_thermochemistry
result_irecv calls irecv, recv
send_pie_term_to_node calls isend
send_pie_term_to_worker calls isend