compute_gmbe_energy_gradient – metalquicha
compute_gmbe_energy_gradient Subroutine
150 statements
Source File
public subroutine compute_gmbe_energy_gradient(monomers, n_monomers, monomer_results, n_intersections, intersection_results, intersection_sets, intersection_levels, sys_geom, total_energy, total_gradient, bonds)
Uses
pic_logger
mqc_config_parser
mqc_gmbe_utils
mqc_physical_fragment
mqc_error
mqc_result_types
Compute GMBE (Generalized Many-Body Expansion) energy and gradient with full inclusion-exclusion
Extends compute_gmbe_energy to also compute gradients for overlapping fragments. Gradient redistribution handles hydrogen caps at broken bonds.
For overlapping fragments, the GMBE formula follows the inclusion-exclusion principle: E_total = sum(E_monomers) - sum(E_2-way) + sum(E_3-way) - … ∇E_total = sum(∇E_monomers) - sum(∇E_2-way) + sum(∇E_3-way) - …
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: monomers(:)
Monomer indices (1-based)
integer, intent(in) :: n_monomers
Number of monomers
type(calculation_result_t), intent(in) :: monomer_results(:)
Monomer energies and gradients
integer, intent(in) :: n_intersections
Number of intersection fragments
type(calculation_result_t), intent(in), optional :: intersection_results(:)
Intersection energies and gradients
integer, intent(in), optional :: intersection_sets(:,:)
k-tuples that created each intersection (n_monomers, n_intersections)
integer, intent(in), optional :: intersection_levels(:)
Level k of each intersection
type(system_geometry_t), intent(in) :: sys_geom
real(kind=dp), intent(out) :: total_energy
Total GMBE energy
real(kind=dp), intent(out) :: total_gradient(:,:)
Total GMBE gradient (3, total_atoms)
type(bond_t), intent(in), optional :: bonds(:)
Bond information for caps
Calls
Variables
Type Visibility Attributes Name Initial
integer, private :: current_log_level
type(error_t), private :: error
type(physical_fragment_t), private :: fragment
integer, private :: i
integer, private :: k
integer, private, allocatable :: level_counts(:)
real(kind=dp), private, allocatable :: level_energies(:)
integer, private :: max_level
real(kind=dp), private :: monomer_energy
integer, private, allocatable :: monomer_idx(:)
real(kind=dp), private :: sign_factor
Source Code
   subroutine compute_gmbe_energy_gradient(monomers, n_monomers, monomer_results, &
                                           n_intersections, intersection_results, &
                                           intersection_sets, intersection_levels, &
                                           sys_geom, total_energy, total_gradient, bonds)
      !! Compute GMBE (Generalized Many-Body Expansion) energy and gradient with full inclusion-exclusion
      !!
      !! Extends compute_gmbe_energy to also compute gradients for overlapping fragments.
      !! Gradient redistribution handles hydrogen caps at broken bonds.
      !!
      !! For overlapping fragments, the GMBE formula follows the inclusion-exclusion principle:
      !!   E_total = sum(E_monomers) - sum(E_2-way) + sum(E_3-way) - ...
      !!   ∇E_total = sum(∇E_monomers) - sum(∇E_2-way) + sum(∇E_3-way) - ...
      use mqc_result_types, only: calculation_result_t
      use mqc_physical_fragment, only: build_fragment_from_indices, build_fragment_from_atom_list, &
                                       redistribute_cap_gradients
      use mqc_gmbe_utils, only: find_fragment_intersection
      use mqc_config_parser, only: bond_t
      use mqc_error, only: error_t
      use pic_logger, only: info_level
      integer, intent(in) :: monomers(:)              !! Monomer indices (1-based)
      integer, intent(in) :: n_monomers               !! Number of monomers
      type(calculation_result_t), intent(in) :: monomer_results(:)     !! Monomer energies and gradients
      integer, intent(in) :: n_intersections          !! Number of intersection fragments
      type(calculation_result_t), intent(in), optional :: intersection_results(:)  !! Intersection energies and gradients
      integer, intent(in), optional :: intersection_sets(:, :)  !! k-tuples that created each intersection (n_monomers, n_intersections)
      integer, intent(in), optional :: intersection_levels(:)   !! Level k of each intersection
      type(system_geometry_t), intent(in) :: sys_geom
      real(dp), intent(out) :: total_energy           !! Total GMBE energy
      real(dp), intent(out) :: total_gradient(:, :)   !! Total GMBE gradient (3, total_atoms)
      type(bond_t), intent(in), optional :: bonds(:)  !! Bond information for caps
      integer :: i, k, max_level, current_log_level
      real(dp) :: monomer_energy
      real(dp), allocatable :: level_energies(:)
      integer, allocatable :: level_counts(:)
      real(dp) :: sign_factor
      type(physical_fragment_t) :: fragment
      type(error_t) :: error
      integer, allocatable :: monomer_idx(:)
      ! Zero out total gradient
      total_gradient = 0.0_dp
      ! Sum monomer energies and gradients
      monomer_energy = 0.0_dp
      do i = 1, n_monomers
         monomer_energy = monomer_energy + monomer_results(i)%energy%total()
         ! Accumulate monomer gradients
         if (monomer_results(i)%has_gradient) then
            ! Rebuild fragment to get local→global mapping
            allocate (monomer_idx(1))
            monomer_idx(1) = monomers(i)
            call build_fragment_from_indices(sys_geom, monomer_idx, fragment, error, bonds)
            if (error%has_error()) then
               call logger%error(error%get_full_trace())
               error stop "Failed to build monomer fragment in GMBE gradient"
            end if
            call redistribute_cap_gradients(fragment, monomer_results(i)%gradient, total_gradient)
            call fragment%destroy()
            deallocate (monomer_idx)
         end if
      end do
      ! Start with monomer contribution
      total_energy = monomer_energy
      if (n_intersections > 0 .and. present(intersection_results) .and. &
          present(intersection_sets) .and. present(intersection_levels)) then
         ! Find maximum intersection level
         max_level = maxval(intersection_levels)
         ! Allocate arrays to track contributions by level
         allocate (level_energies(2:max_level))
         allocate (level_counts(2:max_level))
         level_energies = 0.0_dp
         level_counts = 0
         ! Sum intersection energies by level with alternating signs
         do i = 1, n_intersections
            k = intersection_levels(i)
            sign_factor = real((-1)**(k + 1), dp)
            level_energies(k) = level_energies(k) + intersection_results(i)%energy%total()
            level_counts(k) = level_counts(k) + 1
            ! Accumulate intersection gradients with sign
            if (intersection_results(i)%has_gradient) then
               block
                  integer :: j, current_n, next_n, n_intersect
                  integer, allocatable :: current_atoms(:), next_atoms(:), intersect_atoms(:)
                  real(dp), allocatable :: term_gradient(:, :)
                  logical :: has_intersection
                  type(physical_fragment_t) :: inter_fragment
                  type(error_t) :: inter_error
                  ! Start with the atom list for the first monomer in this intersection set
                  call get_monomer_atom_list(sys_geom, intersection_sets(1, i), current_atoms, current_n)
                  if (current_n > 0) then
                     ! Intersect with the remaining monomers in the set
                     do j = 2, k
                        call get_monomer_atom_list(sys_geom, intersection_sets(j, i), next_atoms, next_n)
                        has_intersection = find_fragment_intersection(current_atoms, current_n, &
                                                                      next_atoms, next_n, &
                                                                      intersect_atoms, n_intersect)
                        deallocate (current_atoms, next_atoms)
                        if (.not. has_intersection) then
                           current_n = 0
                           exit
                        end if
                        current_n = n_intersect
                        allocate (current_atoms(current_n))
                        current_atoms = intersect_atoms
                        deallocate (intersect_atoms)
                     end do
                  end if
                  if (current_n > 0) then
                     call build_fragment_from_atom_list(sys_geom, current_atoms, current_n, &
                                                        inter_fragment, inter_error, bonds)
                     if (inter_error%has_error()) then
                        call logger%error(inter_error%get_full_trace())
                        error stop "Failed to build intersection fragment in GMBE gradient"
                     end if
                     allocate (term_gradient(3, sys_geom%total_atoms))
                     term_gradient = 0.0_dp
                     call redistribute_cap_gradients(inter_fragment, intersection_results(i)%gradient, term_gradient)
                     total_gradient = total_gradient + sign_factor*term_gradient
                     call inter_fragment%destroy()
                     deallocate (term_gradient)
                  else
                     call logger%warning("GMBE intersection has no atoms; skipping gradient")
                  end if
                  if (allocated(current_atoms)) deallocate (current_atoms)
               end block
            end if
         end do
         ! Apply inclusion-exclusion to energy: sign is (-1)^(k+1) for k-way intersections
         do k = 2, max_level
            if (level_counts(k) > 0) then
               sign_factor = real((-1)**(k + 1), dp)
               total_energy = total_energy + sign_factor*level_energies(k)
            end if
         end do
         ! Print breakdown
         call logger%info("GMBE Energy breakdown (Inclusion-Exclusion Principle):")
         block
            character(len=256) :: line
            write (line, '(a,i0,a,f20.10)') "  Monomers (", n_monomers, "):  ", monomer_energy
            call logger%info(trim(line))
            do k = 2, max_level
               if (level_counts(k) > 0) then
                  sign_factor = real((-1)**(k + 1), dp)
                  if (sign_factor > 0.0_dp) then
                     write (line, '(a,i0,a,i0,a,f20.10)') "  ", k, "-way ∩ (", level_counts(k), "):  +", level_energies(k)
                  else
                     write (line, '(a,i0,a,i0,a,f20.10)') "  ", k, "-way ∩ (", level_counts(k), "):  ", level_energies(k)
                  end if
                  call logger%info(trim(line))
               end if
            end do
            write (line, '(a,f20.10)') "  Total GMBE:      ", total_energy
            call logger%info(trim(line))
         end block
         deallocate (level_energies, level_counts)
      else
         ! No intersections - just report monomer sum
         call logger%info("GMBE Energy breakdown:")
         block
            character(len=256) :: line
            write (line, '(a,i0,a,f20.10)') "  Monomers (", n_monomers, "): ", monomer_energy
            call logger%info(trim(line))
            write (line, '(a,f20.10)') "  Total GMBE:  ", total_energy
            call logger%info(trim(line))
         end block
      end if
      ! Print gradient info (same format as MBE)
      call logger%info("GMBE gradient computation completed")
      call logger%info("  Total gradient norm: "//to_char(sqrt(sum(total_gradient**2))))
      ! Print detailed gradient if info level and small system
      call logger%configuration(level=current_log_level)
      if (current_log_level >= info_level .and. sys_geom%total_atoms < 100) then
         call logger%info(" ")
         call logger%info("Total GMBE Gradient (Hartree/Bohr):")
         do i = 1, sys_geom%total_atoms
            block
               character(len=256) :: grad_line
               write (grad_line, '(a,i5,a,3f20.12)') "  Atom ", i, ": ", &
                  total_gradient(1, i), total_gradient(2, i), total_gradient(3, i)
               call logger%info(trim(grad_line))
            end block
         end do
         call logger%info(" ")
      end if
   end subroutine compute_gmbe_energy_gradient
Call graph
compute_gmbe_energy_gradient calls configuration, current_atoms, error, info, intersect_atoms, next_atoms, build_fragment_from_atom_list, build_fragment_from_indices, energy_total, error_get_full_trace, error_has_error, find_fragment_intersection, fragment_destroy, get_monomer_atom_list, redistribute_cap_gradients, term_gradient, to_char, warning
build_fragment_from_atom_list calls error_has_error, add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
build_fragment_from_indices calls error_has_error, add_hydrogen_caps, calculate_monomer_distance, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
energy_total calls mp2_total
error_get_full_trace calls error_has_error
fragment_destroy calls basis_set_destroy
basis_set_destroy calls atomic_basis_destroy
calculate_monomer_distance calls to_angstrom
check_duplicate_atoms calls error, to_char, element_number_to_symbol, error_set
atomic_basis_destroy calls cgto_destroy