compute_mbe_energy_gradient_hessian – metalquicha
compute_mbe_energy_gradient_hessian Subroutine
115 statements
Source File
public subroutine compute_mbe_energy_gradient_hessian(polymers, fragment_count, max_level, results, sys_geom, total_energy, total_gradient, total_hessian, bonds)
Uses
mqc_result_types
mqc_config_parser
mqc_physical_fragment
Compute MBE energy, gradient, and Hessian in a single pass Most efficient for simultaneous energy+gradient+Hessian calculations
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: polymers(:,:)
integer(kind=int64), intent(in) :: fragment_count
integer, intent(in) :: max_level
type(calculation_result_t), intent(in) :: results(:)
type(system_geometry_t), intent(in) :: sys_geom
real(kind=dp), intent(out) :: total_energy
real(kind=dp), intent(out) :: total_gradient(:,:)
(3, total_atoms)
real(kind=dp), intent(out) :: total_hessian(:,:)
(3total_atoms, 3total_atoms)
type(bond_t), intent(in), optional :: bonds(:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: current_log_level
real(kind=dp), private :: delta_E
real(kind=dp), private, allocatable :: delta_energies(:)
real(kind=dp), private, allocatable :: delta_gradients(:,:,:)
real(kind=dp), private, allocatable :: delta_hessians(:,:,:)
logical, private :: do_detailed_print
real(kind=dp), private, allocatable :: energies(:)
type(physical_fragment_t), private :: fragment
integer, private :: fragment_size
integer, private :: hess_dim
integer(kind=int64), private :: i
integer, private :: iatom
type(fragment_lookup_t), private :: lookup
integer, private :: nlevel
real(kind=dp), private, allocatable :: sum_by_level(:)
real(kind=dp), private, allocatable :: temp_hess(:,:)
Source Code
   subroutine compute_mbe_energy_gradient_hessian(polymers, fragment_count, max_level, results, sys_geom, &
                                                  total_energy, total_gradient, total_hessian, bonds)
      !! Compute MBE energy, gradient, and Hessian in a single pass
      !! Most efficient for simultaneous energy+gradient+Hessian calculations
      use mqc_result_types, only: calculation_result_t
      use mqc_config_parser, only: bond_t
      use mqc_physical_fragment, only: build_fragment_from_indices, redistribute_cap_gradients, &
                                       redistribute_cap_hessian
      integer(int64), intent(in) :: fragment_count
      integer, intent(in) :: polymers(:, :), max_level
      type(calculation_result_t), intent(in) :: results(:)
      type(system_geometry_t), intent(in) :: sys_geom
      real(dp), intent(out) :: total_energy
      real(dp), intent(out) :: total_gradient(:, :)  !! (3, total_atoms)
      real(dp), intent(out) :: total_hessian(:, :)   !! (3*total_atoms, 3*total_atoms)
      type(bond_t), intent(in), optional :: bonds(:)
      integer(int64) :: i
      integer :: fragment_size, nlevel, current_log_level, iatom
      real(dp), allocatable :: sum_by_level(:), delta_energies(:), energies(:)
      real(dp), allocatable :: delta_gradients(:, :, :), delta_hessians(:, :, :)
      type(fragment_lookup_t) :: lookup
      logical :: do_detailed_print
      integer :: hess_dim
      type(physical_fragment_t) :: fragment
      real(dp), allocatable :: temp_hess(:, :)
      real(dp) :: delta_E
      hess_dim = 3*sys_geom%total_atoms
      ! Validate all fragments have Hessians
      do i = 1, fragment_count
         if (.not. results(i)%has_hessian) then
            call logger%error("Fragment "//to_char(i)//" does not have Hessian!")
            error stop "Missing Hessian in compute_mbe_energy_gradient_hessian"
         end if
      end do
      call logger%configuration(level=current_log_level)
      do_detailed_print = (current_log_level >= verbose_level)
      allocate (sum_by_level(max_level))
      allocate (delta_energies(fragment_count))
      allocate (energies(fragment_count))
      allocate (delta_gradients(3, sys_geom%total_atoms, fragment_count))
      allocate (delta_hessians(hess_dim, hess_dim, fragment_count))
      allocate (temp_hess(hess_dim, hess_dim))
      sum_by_level = 0.0_dp
      delta_energies = 0.0_dp
      energies = 0.0_dp
      delta_gradients = 0.0_dp
      delta_hessians = 0.0_dp
      total_gradient = 0.0_dp
      total_hessian = 0.0_dp
      ! Build lookup table for fragment indices
      call lookup%init(fragment_count)
      do i = 1_int64, fragment_count
         fragment_size = count(polymers(i, :) > 0)
         if (fragment_size > 0 .and. fragment_size <= max_level) then
            call lookup%insert(polymers(i, 1:fragment_size), fragment_size, i)
         end if
      end do
      ! Extract energies first
      do i = 1_int64, fragment_count
         energies(i) = results(i)%energy%total()
      end do
      ! Compute delta energies, gradients, and Hessians for each fragment
      ! Process by n-mer level to ensure all subsets are computed before they're needed
      do nlevel = 1, max_level
         do i = 1_int64, fragment_count
            fragment_size = count(polymers(i, :) > 0)
            ! Only process fragments of the current nlevel
            if (fragment_size /= nlevel) cycle
            if (fragment_size == 1) then
               ! 1-body: delta = value (no subsets)
               delta_energies(i) = energies(i)
               sum_by_level(1) = sum_by_level(1) + delta_energies(i)
               ! Map fragment gradient and Hessian to system coordinates
               call map_fragment_to_system_gradient(results(i)%gradient, polymers(i, 1:fragment_size), &
                                                    sys_geom, delta_gradients(:, :, i), bonds)
               call map_fragment_to_system_hessian(results(i)%hessian, polymers(i, 1:fragment_size), &
                                                   sys_geom, delta_hessians(:, :, i), bonds)
            else if (fragment_size >= 2 .and. fragment_size <= max_level) then
               ! n-body: delta = value - sum(all subset deltas)
               delta_E = compute_mbe(i, polymers(i, 1:fragment_size), lookup, &
                                     energies, delta_energies, fragment_size)
               delta_energies(i) = delta_E
               sum_by_level(fragment_size) = sum_by_level(fragment_size) + delta_E
               ! Gradient delta
               call compute_mbe_gradient(i, polymers(i, 1:fragment_size), lookup, &
                                         results, delta_gradients, fragment_size, sys_geom, bonds)
               ! Hessian delta
               call compute_mbe_hessian(i, polymers(i, 1:fragment_size), lookup, &
                                        results, delta_hessians, fragment_size, sys_geom, bonds)
            end if
         end do
      end do
      ! Clean up lookup table
      call lookup%destroy()
      ! Compute total energy, gradient, and Hessian
      total_energy = sum(sum_by_level)
      do i = 1_int64, fragment_count
         fragment_size = count(polymers(i, :) > 0)
         if (fragment_size <= max_level) then
            total_gradient = total_gradient + delta_gradients(:, :, i)
            total_hessian = total_hessian + delta_hessians(:, :, i)
         end if
      end do
      ! Print energy breakdown
      call logger%info("MBE Energy breakdown:")
      do nlevel = 1, max_level
         if (abs(sum_by_level(nlevel)) > 1e-15_dp) then
            block
               character(len=256) :: energy_line
               write (energy_line, '(a,i0,a,f20.10)') "  ", nlevel, "-body:  ", sum_by_level(nlevel)
               call logger%info(trim(energy_line))
            end block
         end if
      end do
      block
         character(len=256) :: total_line
         write (total_line, '(a,f20.10)') "  Total:   ", total_energy
         call logger%info(trim(total_line))
      end block
      ! Print gradient and Hessian info
      call logger%info("MBE gradient computation completed")
      call logger%info("  Total gradient norm: "//to_char(sqrt(sum(total_gradient**2))))
      call logger%info("MBE Hessian computation completed")
      call logger%info("  Total Hessian Frobenius norm: "//to_char(sqrt(sum(total_hessian**2))))
      ! Print detailed gradient if verbose and small system
      if (current_log_level >= info_level .and. sys_geom%total_atoms < 100) then
         call logger%info(" ")
         call logger%info("Total MBE Gradient (Hartree/Bohr):")
         do iatom = 1, sys_geom%total_atoms
            block
               character(len=256) :: grad_line
               write (grad_line, '(a,i5,a,3f20.12)') "  Atom ", iatom, ": ", &
                  total_gradient(1, iatom), total_gradient(2, iatom), total_gradient(3, iatom)
               call logger%info(trim(grad_line))
            end block
         end do
         call logger%info(" ")
      end if
      ! Always write JSON file for machine-readable output (include gradient and Hessian)
      call print_detailed_breakdown_json(polymers, fragment_count, max_level, energies, delta_energies, &
                                         sum_by_level, total_energy, total_gradient, total_hessian, results)
      deallocate (sum_by_level, delta_energies, energies, delta_gradients, delta_hessians, temp_hess)
   end subroutine compute_mbe_energy_gradient_hessian
Call graph
compute_mbe_energy_gradient_hessian calls configuration, error, info, compute_mbe, compute_mbe_gradient, compute_mbe_hessian, energy_total, fragment_lookup_destroy, fragment_lookup_init, fragment_lookup_insert, map_fragment_to_system_gradient, map_fragment_to_system_hessian, print_detailed_breakdown_json, to_char
compute_mbe calls error, fragment_lookup_find, get_next_combination
compute_mbe_gradient calls map_fragment_to_system_gradient, fragment_lookup_find, get_next_combination
compute_mbe_hessian calls map_fragment_to_system_hessian, fragment_lookup_find, get_next_combination
energy_total calls mp2_total
fragment_lookup_init calls next_prime_internal
fragment_lookup_insert calls fnv_1a_hash, sort
map_fragment_to_system_gradient calls configuration, error, debug, build_fragment_from_indices, error_get_full_trace, error_has_error, fragment_destroy, redistribute_cap_gradients
map_fragment_to_system_hessian calls build_fragment_from_indices, fragment_destroy, redistribute_cap_hessian
print_detailed_breakdown_json calls error, info, get_basename, get_frag_level_name, get_output_json_filename, warning
build_fragment_from_indices calls error_has_error, add_hydrogen_caps, calculate_monomer_distance, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
error_get_full_trace calls error_has_error
fragment_destroy calls basis_set_destroy
fragment_lookup_find calls fnv_1a_hash, sort, arrays_equal_internal
basis_set_destroy calls atomic_basis_destroy
calculate_monomer_distance calls to_angstrom
check_duplicate_atoms calls error, to_char, element_number_to_symbol, error_set
atomic_basis_destroy calls cgto_destroy
global_coordinator calls compute_mbe_energy_gradient_hessian
serial_fragment_processor calls compute_mbe_energy_gradient_hessian, serial_fragment_processor
run_fragmented_calculation calls serial_fragment_processor
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation