compute_mbe_energy_gradient – metalquicha
compute_mbe_energy_gradient Subroutine
130 statements
Source File
public subroutine compute_mbe_energy_gradient(polymers, fragment_count, max_level, results, sys_geom, total_energy, total_gradient, bonds)
Uses
mqc_config_parser
mqc_result_types
Compute both MBE energy and gradient in a single pass This is more efficient than calling compute_mbe_energy and compute_mbe_gradient separately as it only builds the lookup table once and processes all fragments in one loop
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: polymers(:,:)
integer(kind=int64), intent(in) :: fragment_count
integer, intent(in) :: max_level
type(calculation_result_t), intent(in) :: results(:)
type(system_geometry_t), intent(in) :: sys_geom
real(kind=dp), intent(out) :: total_energy
real(kind=dp), intent(out) :: total_gradient(:,:)
(3, total_atoms)
type(bond_t), intent(in), optional :: bonds(:)
Bond information for caps
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: current_log_level
real(kind=dp), private :: delta_E
real(kind=dp), private, allocatable :: delta_energies(:)
real(kind=dp), private, allocatable :: delta_gradients(:,:,:)
(3, total_atoms, fragment_count)
logical, private :: do_detailed_print
real(kind=dp), private, allocatable :: energies(:)
integer, private, allocatable :: fragment_sizes(:)
integer(kind=int64), private :: i
integer, private :: iatom
integer(kind=int64), private :: idx
integer(kind=int64), private :: j
integer(kind=int64), private :: level_counts(max_level)
integer(kind=int64), private, allocatable :: level_indices(:)
integer(kind=int64), private, allocatable :: level_offsets(:)
real(kind=dp), private :: level_sum
type(fragment_lookup_t), private :: lookup
type(timer_type), private :: lookup_timer
integer, private :: nlevel
real(kind=dp), private, allocatable :: sum_by_level(:)
Source Code
   subroutine compute_mbe_energy_gradient(polymers, fragment_count, max_level, results, sys_geom, &
                                          total_energy, total_gradient, bonds)
      !! Compute both MBE energy and gradient in a single pass
      !! This is more efficient than calling compute_mbe_energy and compute_mbe_gradient separately
      !! as it only builds the lookup table once and processes all fragments in one loop
      use mqc_result_types, only: calculation_result_t
      use mqc_config_parser, only: bond_t
      integer(int64), intent(in) :: fragment_count
      integer, intent(in) :: polymers(:, :), max_level
      type(calculation_result_t), intent(in) :: results(:)
      type(system_geometry_t), intent(in) :: sys_geom
      real(dp), intent(out) :: total_energy
      real(dp), intent(out) :: total_gradient(:, :)  !! (3, total_atoms)
      type(bond_t), intent(in), optional :: bonds(:)  !! Bond information for caps
      integer(int64) :: i, j, idx
      integer :: nlevel, current_log_level, iatom
      real(dp), allocatable :: sum_by_level(:), delta_energies(:), energies(:)
      real(dp), allocatable :: delta_gradients(:, :, :)  !! (3, total_atoms, fragment_count)
      real(dp) :: delta_E, level_sum
      logical :: do_detailed_print
      type(fragment_lookup_t) :: lookup
      type(timer_type) :: lookup_timer
      ! OpenMP parallelization support
      integer, allocatable :: fragment_sizes(:)
      integer(int64), allocatable :: level_indices(:), level_offsets(:)
      integer(int64) :: level_counts(max_level)
      ! Validate that all fragments have gradients
      do i = 1_int64, fragment_count
         if (.not. results(i)%has_gradient) then
            call logger%error("Fragment "//to_char(i)//" does not have gradient!")
            error stop "Missing gradient in compute_mbe_energy_gradient"
         end if
      end do
      call logger%configuration(level=current_log_level)
      do_detailed_print = (current_log_level >= verbose_level)
      ! Allocate arrays for energy
      allocate (sum_by_level(max_level))
      allocate (delta_energies(fragment_count))
      allocate (energies(fragment_count))
      sum_by_level = 0.0_dp
      delta_energies = 0.0_dp
      ! Extract total energies from results and pre-compute fragment sizes
      allocate (fragment_sizes(fragment_count))
      do i = 1_int64, fragment_count
         energies(i) = results(i)%energy%total()
         fragment_sizes(i) = count(polymers(i, :) > 0)
      end do
      ! Allocate arrays for gradient
      allocate (delta_gradients(3, sys_geom%total_atoms, fragment_count))
      delta_gradients = 0.0_dp
      total_gradient = 0.0_dp
      ! Build hash table for fast fragment lookups (shared for both energy and gradient)
      call lookup_timer%start()
      call lookup%init(fragment_count)
      do i = 1_int64, fragment_count
         call lookup%insert(polymers(i, :), fragment_sizes(i), i)
      end do
      call lookup_timer%stop()
      call logger%debug("Time to build lookup table: "//to_char(lookup_timer%get_elapsed_time())//" s")
      call logger%debug("Hash table size: "//to_char(lookup%table_size)// &
                        ", entries: "//to_char(lookup%n_entries))
      ! Build level-indexed arrays for efficient parallel iteration
      level_counts = 0_int64
      do i = 1_int64, fragment_count
         if (fragment_sizes(i) >= 1 .and. fragment_sizes(i) <= max_level) then
            level_counts(fragment_sizes(i)) = level_counts(fragment_sizes(i)) + 1_int64
         end if
      end do
      ! Compute level offsets (prefix sum)
      allocate (level_offsets(max_level + 1))
      level_offsets(1) = 1_int64
      do nlevel = 1, max_level
         level_offsets(nlevel + 1) = level_offsets(nlevel) + level_counts(nlevel)
      end do
      ! Build index array grouping fragments by level
      allocate (level_indices(fragment_count))
      level_counts = 0_int64  ! Reuse as insertion counters
      do i = 1_int64, fragment_count
         nlevel = fragment_sizes(i)
         if (nlevel >= 1 .and. nlevel <= max_level) then
            idx = level_offsets(nlevel) + level_counts(nlevel)
            level_indices(idx) = i
            level_counts(nlevel) = level_counts(nlevel) + 1_int64
         end if
      end do
      ! Bottom-up computation: process fragments by size (1-body, 2-body, 3-body, etc.)
      ! Process by n-mer level to ensure all subsets are computed before they're needed
      ! OpenMP parallelization: within each level, all computations are independent
      do nlevel = 1, max_level
         level_sum = 0.0_dp
         !$omp parallel do default(shared) &
         !$omp& private(j, i, delta_E) &
         !$omp& reduction(+:level_sum) &
         !$omp& schedule(dynamic, 1000)
         do j = level_offsets(nlevel), level_offsets(nlevel + 1) - 1_int64
            i = level_indices(j)
            if (nlevel == 1) then
               ! 1-body: deltaE = E, deltaG = G (no subsets to subtract)
               delta_energies(i) = energies(i)
               level_sum = level_sum + delta_energies(i)
               ! Map fragment gradient to system coordinates
               call map_fragment_to_system_gradient(results(i)%gradient, polymers(i, 1:nlevel), &
                                                    sys_geom, delta_gradients(:, :, i), bonds)
            else
               ! n-body: deltaE = E - sum(all subset deltaEs), deltaG = G - sum(all subset deltaGs)
               ! Energy delta
               delta_E = compute_mbe(i, polymers(i, 1:nlevel), lookup, &
                                     energies, delta_energies, nlevel)
               delta_energies(i) = delta_E
               level_sum = level_sum + delta_E
               ! Gradient delta
               call compute_mbe_gradient(i, polymers(i, 1:nlevel), lookup, &
                                         results, delta_gradients, nlevel, sys_geom, bonds)
            end if
         end do
         !$omp end parallel do
         sum_by_level(nlevel) = level_sum
      end do
      ! Clean up lookup table
      call lookup%destroy()
      ! Compute total energy
      total_energy = sum(sum_by_level)
      ! Compute total gradient (using pre-computed sizes)
      do i = 1_int64, fragment_count
         if (fragment_sizes(i) <= max_level) then
            total_gradient = total_gradient + delta_gradients(:, :, i)
         end if
      end do
      ! Print energy breakdown
      call logger%info("MBE Energy breakdown:")
      do nlevel = 1, max_level
         if (abs(sum_by_level(nlevel)) > 1e-15_dp) then
            block
               character(len=256) :: energy_line
               write (energy_line, '(a,i0,a,f20.10)') "  ", nlevel, "-body:  ", sum_by_level(nlevel)
               call logger%info(trim(energy_line))
            end block
         end if
      end do
      block
         character(len=256) :: total_line
         write (total_line, '(a,f20.10)') "  Total:   ", total_energy
         call logger%info(trim(total_line))
      end block
      ! Print gradient info
      call logger%info("MBE gradient computation completed")
      call logger%info("  Total gradient norm: "//to_char(sqrt(sum(total_gradient**2))))
      ! Print detailed gradient if verbose and small system
      if (current_log_level >= info_level .and. sys_geom%total_atoms < 100) then
         call logger%info(" ")
         call logger%info("Total MBE Gradient (Hartree/Bohr):")
         do iatom = 1, sys_geom%total_atoms
            block
               character(len=256) :: grad_line
               write (grad_line, '(a,i5,a,3f20.12)') "  Atom ", iatom, ": ", &
                  total_gradient(1, iatom), total_gradient(2, iatom), total_gradient(3, iatom)
               call logger%info(trim(grad_line))
            end block
         end do
         call logger%info(" ")
      end if
      ! Print detailed breakdown if requested
      if (do_detailed_print) then
         call print_detailed_breakdown(polymers, fragment_count, max_level, energies, delta_energies)
      end if
      ! Always write JSON file for machine-readable output (include gradient)
      call print_detailed_breakdown_json(polymers, fragment_count, max_level, energies, delta_energies, &
                                         sum_by_level, total_energy, total_gradient, results=results)
      deallocate (sum_by_level, delta_energies, energies, delta_gradients, &
                  fragment_sizes, level_indices, level_offsets)
   end subroutine compute_mbe_energy_gradient
Call graph
compute_mbe_energy_gradient calls configuration, debug, error, get_elapsed_time, info, compute_mbe, compute_mbe_gradient, energy_total, fragment_lookup_destroy, fragment_lookup_init, fragment_lookup_insert, map_fragment_to_system_gradient, print_detailed_breakdown, print_detailed_breakdown_json, start, to_char
compute_mbe calls error, fragment_lookup_find, get_next_combination
compute_mbe_gradient calls map_fragment_to_system_gradient, fragment_lookup_find, get_next_combination
energy_total calls mp2_total
fragment_lookup_init calls next_prime_internal
fragment_lookup_insert calls fnv_1a_hash, sort
map_fragment_to_system_gradient calls configuration, debug, error, build_fragment_from_indices, error_get_full_trace, error_has_error, fragment_destroy, redistribute_cap_gradients
print_detailed_breakdown calls header, level_name, get_frag_level_name, verbose, warning
print_detailed_breakdown_json calls error, info, get_basename, get_frag_level_name, get_output_json_filename, warning
build_fragment_from_indices calls error_has_error, add_hydrogen_caps, calculate_monomer_distance, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
error_get_full_trace calls error_has_error
fragment_destroy calls basis_set_destroy
fragment_lookup_find calls fnv_1a_hash, sort, arrays_equal_internal
basis_set_destroy calls atomic_basis_destroy
calculate_monomer_distance calls to_angstrom
check_duplicate_atoms calls error, to_char, element_number_to_symbol, error_set
atomic_basis_destroy calls cgto_destroy
global_coordinator calls compute_mbe_energy_gradient
serial_fragment_processor calls compute_mbe_energy_gradient, serial_fragment_processor
run_fragmented_calculation calls serial_fragment_processor
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation