config_log_settings – metalquicha
config_log_settings Subroutine
14 statements
Source File
private subroutine config_log_settings(this)
Uses
pic_logger
mqc_method_types
Log method-specific settings based on method type
Dispatches to appropriate logging based on the configured method. This allows the driver to log settings without knowing method details.
Type Bound
method_config_t
Arguments
Type Intent Optional Attributes Name
class(method_config_t), intent(in) :: this
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
character(len=128), private :: info_lines(4)
integer, private :: n_lines
Source Code
   subroutine config_log_settings(this)
      !! Log method-specific settings based on method type
      !!
      !! Dispatches to appropriate logging based on the configured method.
      !! This allows the driver to log settings without knowing method details.
      use mqc_method_types, only: METHOD_TYPE_GFN1, METHOD_TYPE_GFN2
      use pic_logger, only: logger => global_logger
      class(method_config_t), intent(in) :: this
      character(len=128) :: info_lines(4)
      integer :: n_lines, i
      ! Log XTB solvation settings if using XTB method
      select case (this%method_type)
      case (METHOD_TYPE_GFN1, METHOD_TYPE_GFN2)
         call this%xtb%get_solvation_info(info_lines, n_lines)
         do i = 1, n_lines
            call logger%info(trim(info_lines(i)))
         end do
      end select
   end subroutine config_log_settings
Call graph
config_log_settings calls info, xtb_get_solvation_info
xtb_get_solvation_info calls xtb_has_solvation, to_char
run_calculation calls config_log_settings
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations