configure_hf – metalquicha
configure_hf Subroutine
15 statements
Source File
private subroutine configure_hf(method, config)
Configure a Hartree-Fock method instance from config%scf (shared SCF settings)
Arguments
Type Intent Optional Attributes Name
class(qc_method_t), intent(inout) :: method
type(method_config_t), intent(in) :: config
Called by
Source Code
   subroutine configure_hf(method, config)
      !! Configure a Hartree-Fock method instance from config%scf (shared SCF settings)
      class(qc_method_t), intent(inout) :: method
      type(method_config_t), intent(in) :: config
      select type (m => method)
      type is (hf_method_t)
         ! Common settings
         m%options%basis_set = config%basis_set
         m%options%spherical = config%use_spherical
         m%options%verbose = config%verbose
         ! SCF settings from shared config%scf
         m%options%max_iter = config%scf%max_iter
         m%options%conv_tol = config%scf%energy_convergence
         m%options%density_tol = config%scf%density_convergence
         m%options%use_diis = config%scf%use_diis
         m%options%diis_size = config%scf%diis_size
      end select
   end subroutine configure_hf
Call graph
factory_create calls configure_hf
create_method calls factory_create
do_fragment_work calls create_method, do_fragment_work
hessian_coordinator calls create_method, hessian_coordinator
hessian_worker calls create_method, hessian_worker
distributed_unfragmented_hessian calls hessian_coordinator, hessian_worker
node_worker calls do_fragment_work
serial_fragment_processor calls do_fragment_work
serial_gmbe_pie_processor calls do_fragment_work
unfragmented_calculation calls do_fragment_work