config_to_system_geometry – metalquicha
config_to_system_geometry Subroutine
37 statements
Source File
public subroutine config_to_system_geometry(mqc_config, sys_geom, error, molecule_index)
Convert mqc_config_t geometry to system_geometry_t For unfragmented calculations (nfrag=0), treats entire system as single unit For fragmented calculations, currently assumes monomer-based fragmentation If molecule_index is provided, uses that specific molecule from multi-molecule mode
Arguments
Type Intent Optional Attributes Name
type(mqc_config_t), intent(in) :: mqc_config
type(system_geometry_t), intent(out) :: sys_geom
type(error_t), intent(out) :: error
integer, intent(in), optional :: molecule_index
Which molecule to use (for multi-molecule mode)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
logical, private :: use_angstrom
Source Code
   subroutine config_to_system_geometry(mqc_config, sys_geom, error, molecule_index)
      !! Convert mqc_config_t geometry to system_geometry_t
      !! For unfragmented calculations (nfrag=0), treats entire system as single unit
      !! For fragmented calculations, currently assumes monomer-based fragmentation
      !! If molecule_index is provided, uses that specific molecule from multi-molecule mode
      type(mqc_config_t), intent(in) :: mqc_config
      type(system_geometry_t), intent(out) :: sys_geom
      type(error_t), intent(out) :: error
      integer, intent(in), optional :: molecule_index  !! Which molecule to use (for multi-molecule mode)
      integer :: i
      logical :: use_angstrom
      ! Determine units
      use_angstrom = .true.
      if (allocated(mqc_config%units)) then
         if (trim(mqc_config%units) == 'bohr') then
            use_angstrom = .false.
         end if
      end if
      ! Handle multi-molecule vs single molecule mode
      if (present(molecule_index)) then
         ! Multi-molecule mode: extract specific molecule
         if (molecule_index < 1 .or. molecule_index > mqc_config%nmol) then
            call error%set(ERROR_VALIDATION, "Invalid molecule_index in multi-molecule mode")
            return
         end if
         call molecule_to_system_geometry(mqc_config%molecules(molecule_index), &
                                          sys_geom, use_angstrom, mqc_config%allow_overlapping_fragments, error)
      else
         ! Single molecule mode (backward compatible)
         ! Check if geometry is loaded
         if (mqc_config%geometry%natoms == 0) then
            call error%set(ERROR_VALIDATION, "No geometry loaded in mqc_config")
            return
         end if
         if (mqc_config%nfrag == 0) then
            ! Unfragmented calculation: entire system is one "monomer"
            call geometry_to_system_unfragmented(mqc_config%geometry, sys_geom, use_angstrom)
            sys_geom%charge = mqc_config%charge
            sys_geom%multiplicity = mqc_config%multiplicity
         else
            ! Fragmented calculation with explicit fragments
            call geometry_to_system_fragmented(mqc_config, sys_geom, use_angstrom, error)
            if (error%has_error()) then
               call error%add_context("mqc_config_adapter:config_to_system_geometry")
               return
            end if
         end if
      end if
   end subroutine config_to_system_geometry
Call graph
config_to_system_geometry calls error_add_context, error_has_error, error_set, geometry_to_system_fragmented, geometry_to_system_unfragmented, molecule_to_system_geometry
geometry_to_system_fragmented calls initialize_fragmented_system
geometry_to_system_unfragmented calls element_symbol_to_number, to_bohr
molecule_to_system_geometry calls error_set, geometry_to_system_unfragmented, initialize_fragmented_system
element_symbol_to_number calls to_lower, to_upper
initialize_fragmented_system calls error_add_context, error_has_error, element_symbol_to_number, to_bohr, check_fragment_overlap
check_fragment_overlap calls error_set, to_char
run_multi_molecule_calculations calls config_to_system_geometry
main calls config_to_system_geometry, run_multi_molecule_calculations