count_shells_for_element – metalquicha
count_shells_for_element Subroutine
49 statements
Source File
private pure subroutine count_shells_for_element(basis_string, element_name, nshells, stat, errmsg)
Count the number of shells for a specific element in a GAMESS formatted basis string,
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: basis_string
character(len=*), intent(in) :: element_name
integer, intent(out) :: nshells
integer, intent(out) :: stat
character(len=:), intent(out), allocatable :: errmsg
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=1), private :: ang_mom
logical, private :: found_element
logical, private :: in_target_element
character(len=256), private :: line
integer, private :: line_end
integer, private :: line_start
integer, private :: line_type
Source Code
   pure subroutine count_shells_for_element(basis_string, element_name, nshells, stat, errmsg)
      !! Count the number of shells for a specific element in a GAMESS formatted basis string,
      character(len=*), intent(in) :: basis_string
      character(len=*), intent(in) :: element_name
      integer, intent(out) :: nshells
      integer, intent(out) :: stat
      character(len=:), allocatable, intent(out) :: errmsg
      integer :: line_start, line_end, line_type
      character(len=256) :: line
      logical :: in_target_element, found_element
      character(len=1) :: ang_mom
      stat = 0
      nshells = 0
      in_target_element = .false.
      found_element = .false.
      line_start = 1
      do while (line_start <= len(basis_string))
         call get_next_line(basis_string, line_start, line, line_end)
         if (line_end == 0) exit
         line = adjustl(line)
         line_type = classify_line(line)
         select case (line_type)
         case (LINE_ATOM)
            ! Check if this is our target element
            if (strings_equal(line, element_name)) then
               in_target_element = .true.
               found_element = .true.
            else
               ! Different element - stop counting if we were in target
               if (in_target_element) exit
               in_target_element = .false.
            end if
         case (LINE_SHELL)
            if (in_target_element) then
               ! Extract angular momentum
               line = adjustl(line)
               ang_mom = line(1:1)
               ! L shells become 2 shells (S + P)
               if (ang_mom == 'L') then
                  nshells = nshells + 2
               else
                  nshells = nshells + 1
               end if
            end if
         case (LINE_UNKNOWN)
            ! Skip blank lines and comments
            continue
         end select
         line_start = line_end
      end do
      ! Check if we found the element at all
      if (.not. found_element) then
         stat = 1
         errmsg = "Element not found in basis string: "//trim(element_name)
      end if
   end subroutine count_shells_for_element
Call graph
count_shells_for_element calls classify_line, get_next_line, strings_equal
classify_line calls is_blank_or_control, is_function_line, is_shell_header
parse_element_basis calls count_shells_for_element
build_molecular_basis calls parse_element_basis