count_hydrogen_caps – metalquicha
count_hydrogen_caps Subroutine
17 statements
Source File
private subroutine count_hydrogen_caps(atoms_in_fragment, bonds, n_caps)
Count how many hydrogen caps are needed for a fragment A cap is needed when exactly one atom of a broken bond is in the fragment
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: atoms_in_fragment(:)
0-indexed atom indices in fragment
type(bond_t), intent(in), optional :: bonds(:)
integer, intent(out) :: n_caps
Called by
Variables
Type Visibility Attributes Name Initial
logical, private :: atom_i_in_frag
logical, private :: atom_j_in_frag
integer, private :: ibond
Source Code
   subroutine count_hydrogen_caps(atoms_in_fragment, bonds, n_caps)
      !! Count how many hydrogen caps are needed for a fragment
      !! A cap is needed when exactly one atom of a broken bond is in the fragment
      integer, intent(in) :: atoms_in_fragment(:)  !! 0-indexed atom indices in fragment
      type(bond_t), intent(in), optional :: bonds(:)
      integer, intent(out) :: n_caps
      integer :: ibond
      logical :: atom_i_in_frag, atom_j_in_frag
      n_caps = 0
      if (.not. present(bonds)) return
      do ibond = 1, size(bonds)
         if (.not. bonds(ibond)%is_broken) cycle
         ! Check if exactly one atom of this bond is in the fragment
         atom_i_in_frag = any(atoms_in_fragment == bonds(ibond)%atom_i)
         atom_j_in_frag = any(atoms_in_fragment == bonds(ibond)%atom_j)
         ! Add cap only if one atom in fragment, other not (XOR condition)
         if ((atom_i_in_frag .and. .not. atom_j_in_frag) .or. &
             (.not. atom_i_in_frag .and. atom_j_in_frag)) then
            n_caps = n_caps + 1
         end if
      end do
   end subroutine count_hydrogen_caps
Call graph
build_fragment_from_atom_list calls count_hydrogen_caps
build_fragment_from_indices calls count_hydrogen_caps
compute_gmbe_energy_gradient calls build_fragment_from_atom_list, build_fragment_from_indices
compute_gmbe_energy_gradient_hessian calls build_fragment_from_atom_list, build_fragment_from_indices
gmbe_pie_coordinator calls build_fragment_from_atom_list
map_fragment_to_system_gradient calls build_fragment_from_indices
map_fragment_to_system_hessian calls build_fragment_from_indices
node_worker calls build_fragment_from_atom_list, build_fragment_from_indices
serial_fragment_processor calls build_fragment_from_indices, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian, serial_fragment_processor
serial_gmbe_pie_processor calls build_fragment_from_atom_list
compute_mbe_energy_gradient calls map_fragment_to_system_gradient, compute_mbe_gradient
compute_mbe_energy_gradient_hessian calls map_fragment_to_system_gradient, map_fragment_to_system_hessian, compute_mbe_gradient, compute_mbe_hessian
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
run_fragmented_calculation calls gmbe_pie_coordinator, serial_gmbe_pie_processor, serial_fragment_processor
global_coordinator calls compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation