create_method – metalquicha
create_method Function
6 statements
Source File
public function create_method(config) result(method)
Convenience function to create a method without instantiating factory
Usage: use mqc_method_factory, only: create_method method = create_method(config)
Arguments
Type Intent Optional Attributes Name
type(method_config_t), intent(in) :: config
Return Value class(qc_method_t), allocatable
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(method_factory_t), private :: factory
Source Code
   function create_method(config) result(method)
      !! Convenience function to create a method without instantiating factory
      !!
      !! Usage:
      !!   use mqc_method_factory, only: create_method
      !!   method = create_method(config)
      type(method_config_t), intent(in) :: config
      class(qc_method_t), allocatable :: method
      type(method_factory_t) :: factory
      method = factory%create(config)
   end function create_method
Call graph
create_method calls factory_create
factory_create calls configure_dft, configure_hf, configure_mcscf, configure_xtb
configure_mcscf calls state_weights
configure_xtb calls method_type_to_string, xtb_has_solvation
do_fragment_work calls create_method, do_fragment_work
hessian_coordinator calls create_method, hessian_coordinator
hessian_worker calls create_method, hessian_worker
distributed_unfragmented_hessian calls hessian_coordinator, hessian_worker, distributed_unfragmented_hessian
node_worker calls do_fragment_work, node_worker
serial_fragment_processor calls do_fragment_work, serial_fragment_processor
serial_gmbe_pie_processor calls do_fragment_work
unfragmented_calculation calls do_fragment_work, unfragmented_calculation
gmbe_run_serial calls serial_gmbe_pie_processor
gmbe_run_distributed calls node_worker
mbe_run_distributed calls node_worker
mbe_run_serial calls serial_fragment_processor
run_unfragmented_calculation calls distributed_unfragmented_hessian, unfragmented_calculation