distance_between_fragments – metalquicha
distance_between_fragments Function
14 statements
Source File
public pure function distance_between_fragments(frag1, frag2, use_com) result(distance)
Calculate distance between two fragments If use_com is .true., uses center of mass; otherwise uses centroid Distance is in the same units as the fragment coordinates (typically Bohr)
Arguments
Type Intent Optional Attributes Name
type(physical_fragment_t), intent(in) :: frag1
type(physical_fragment_t), intent(in) :: frag2
logical, intent(in) :: use_com
Return Value real(kind=dp)
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=dp), private :: point1(3)
real(kind=dp), private :: point2(3)
Source Code
   pure function distance_between_fragments(frag1, frag2, use_com) result(distance)
      !! Calculate distance between two fragments
      !! If use_com is .true., uses center of mass; otherwise uses centroid
      !! Distance is in the same units as the fragment coordinates (typically Bohr)
      type(physical_fragment_t), intent(in) :: frag1, frag2
      logical, intent(in) :: use_com
      real(dp) :: distance
      real(dp) :: point1(3), point2(3)
      if (use_com) then
         point1 = fragment_center_of_mass(frag1)
         point2 = fragment_center_of_mass(frag2)
      else
         point1 = fragment_centroid(frag1)
         point2 = fragment_centroid(frag2)
      end if
      distance = distance_between_points(point1, point2)
   end function distance_between_fragments
Call graph
distance_between_fragments calls distance_between_points, fragment_center_of_mass, fragment_centroid
fragment_center_of_mass calls element_mass