distributed_unfragmented_hessian – metalquicha
distributed_unfragmented_hessian Module Subroutine
35 statements
Source File
module subroutine distributed_unfragmented_hessian(world_comm, sys_geom, method, driver_config, json_data) Interface →
Uses
mqc_method_xtb
mqc_finite_differences
mqc_json_output_types
mqc_config_adapter
Compute Hessian for unfragmented system using MPI distribution
Uses a dynamic work queue approach: workers request displacement indices from rank 0, compute gradients, and send results back. This provides better load balancing than static work distribution.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: world_comm
type(system_geometry_t), intent(in) :: sys_geom
integer(kind=int32), intent(in) :: method
type(driver_config_t), intent(in), optional :: driver_config
Driver configuration
type(json_output_data_t), intent(out), optional :: json_data
JSON output data
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=dp), private :: displacement
integer, private :: my_rank
integer, private :: n_ranks
real(kind=dp), private :: pressure
real(kind=dp), private :: temperature
Source Code
   module subroutine distributed_unfragmented_hessian(world_comm, sys_geom, method, driver_config, json_data)
      !! Compute Hessian for unfragmented system using MPI distribution
      !!
      !! Uses a dynamic work queue approach: workers request displacement indices
      !! from rank 0, compute gradients, and send results back. This provides
      !! better load balancing than static work distribution.
      use mqc_finite_differences, only: generate_perturbed_geometries, displaced_geometry_t, &
                                        finite_diff_hessian_from_gradients, DEFAULT_DISPLACEMENT, &
                                        copy_and_displace_geometry
      use mqc_config_adapter, only: driver_config_t
      use mqc_json_output_types, only: json_output_data_t
#ifndef MQC_WITHOUT_TBLITE
      use mqc_method_xtb, only: xtb_method_t
#endif
      type(comm_t), intent(in) :: world_comm
      type(system_geometry_t), intent(in) :: sys_geom
      integer(int32), intent(in) :: method
      type(driver_config_t), intent(in), optional :: driver_config  !! Driver configuration
      type(json_output_data_t), intent(out), optional :: json_data  !! JSON output data
      integer :: my_rank, n_ranks
      real(dp) :: displacement
      real(dp) :: temperature, pressure
      my_rank = world_comm%rank()
      n_ranks = world_comm%size()
      ! Use provided settings or defaults
      if (present(driver_config)) then
         displacement = driver_config%hessian%displacement
         temperature = driver_config%hessian%temperature
         pressure = driver_config%hessian%pressure
      else
         displacement = DEFAULT_DISPLACEMENT
         temperature = 298.15_dp
         pressure = 1.0_dp
      end if
      if (my_rank == 0) then
         ! Rank 0 is the coordinator
         if (present(json_data)) then
            call hessian_coordinator(world_comm, sys_geom, method, displacement, temperature, pressure, json_data)
         else
            call hessian_coordinator(world_comm, sys_geom, method, displacement, temperature, pressure)
         end if
      else
         ! Other ranks are workers
         call hessian_worker(world_comm, sys_geom, method, displacement)
      end if
      ! Synchronize all ranks before returning
      call world_comm%barrier()
   end subroutine distributed_unfragmented_hessian
Call graph
distributed_unfragmented_hessian calls barrier, hessian_coordinator, hessian_worker, distributed_unfragmented_hessian
hessian_coordinator calls hessian_coordinator, cart_disp, configuration, fc_mdyne, force_constants, get_elapsed_time, info, iprobe, ir_intensities, irecv, isend, compute_thermochemistry, compute_vibrational_analysis, compute_vibrational_frequencies, energy_total, finite_diff_dipole_derivatives, finite_diff_hessian_from_gradients, fragment_compute_nelec, method_type_to_string, populate_unfragmented_json_data, populate_vibrational_json_data, print_vibrational_analysis, result_destroy, xtb_calc_gradient, recv, reduced_masses, start, to_char, vib_freqs
hessian_worker calls hessian_worker, abort_comm, error, irecv, isend, copy_and_displace_geometry, error_get_message, fragment_compute_nelec, method_type_to_string, result_destroy, xtb_calc_gradient, send, to_char
compute_thermochemistry calls compute_electronic_entropy, compute_moments_of_inertia, compute_partition_functions, compute_rotational_constants, compute_rotational_thermo, compute_translational_thermo, compute_vibrational_thermo, compute_zpe
compute_vibrational_analysis calls compute_vibrational_frequencies, compute_cartesian_displacements, compute_force_constants, compute_ir_intensities, compute_reduced_masses
compute_vibrational_frequencies calls error, pic_syev, mass_weight_hessian, project_translation_rotation, warning
energy_total calls mp2_total
populate_unfragmented_json_data calls energy_total
populate_vibrational_json_data calls energy_total
print_vibrational_analysis calls info, compute_thermochemistry, element_number_to_symbol, print_thermochemistry, warning
result_destroy calls result_reset
xtb_calc_gradient calls energy_total, dpat, new, new_gfn1_calculator, new_gfn2_calculator, new_wavefunction, add_solvation_to_calc, error_set, qat, xtb_singlepoint
add_solvation_to_calc calls new_solvation, new_solvation_cds, new_solvation_shift, get_solvent_dielectric, push_back
compute_cartesian_displacements calls element_mass
compute_ir_intensities calls element_mass
compute_moments_of_inertia calls to_char, pic_syev, warning, element_mass
compute_reduced_masses calls element_mass
compute_zpe calls to_char, warning
mass_weight_hessian calls element_mass
print_thermochemistry calls info
project_translation_rotation calls pic_gesvd, element_mass
result_reset calls energy_reset, error_clear
run_unfragmented_calculation calls distributed_unfragmented_hessian
run_calculation calls run_unfragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations