do_fragment_work – metalquicha
do_fragment_work Module Subroutine
54 statements
Source File
module subroutine do_fragment_work(fragment_idx, result, method, phys_frag, calc_type, world_comm) Interface →
Uses
pic_logger
Process a single fragment for quantum chemistry calculation
Performs energy and gradient calculation on a molecular fragment using specified quantum chemistry method (GFN-xTB variants). Verbosity is controlled by the global logger level.
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: fragment_idx
Fragment index for identification
type(calculation_result_t), intent(out) :: result
Computation results
integer(kind=int32), intent(in) :: method
QC method
type(physical_fragment_t), intent(in), optional :: phys_frag
Fragment geometry
integer(kind=int32), intent(in) :: calc_type
Calculation type
type(comm_t), intent(in), optional :: world_comm
MPI communicator for abort
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: calc_type_local
Local copy of calc_type
integer, private :: current_log_level
Current logger verbosity level
logical, private :: is_verbose
Whether verbose output is enabled
type(xtb_method_t), private :: xtb_calc
XTB calculator instance
Source Code
   module subroutine do_fragment_work(fragment_idx, result, method, phys_frag, calc_type, world_comm)
      !! Process a single fragment for quantum chemistry calculation
      !!
      !! Performs energy and gradient calculation on a molecular fragment using
      !! specified quantum chemistry method (GFN-xTB variants).
      !! Verbosity is controlled by the global logger level.
      use pic_logger, only: verbose_level
      integer(int64), intent(in) :: fragment_idx        !! Fragment index for identification
      type(calculation_result_t), intent(out) :: result  !! Computation results
      integer(int32), intent(in) :: method       !! QC method
      type(physical_fragment_t), intent(in), optional :: phys_frag  !! Fragment geometry
      integer(int32), intent(in) :: calc_type  !! Calculation type
      type(comm_t), intent(in), optional :: world_comm  !! MPI communicator for abort
      integer :: current_log_level  !! Current logger verbosity level
      logical :: is_verbose  !! Whether verbose output is enabled
      integer(int32) :: calc_type_local  !! Local copy of calc_type
#ifndef MQC_WITHOUT_TBLITE
      type(xtb_method_t) :: xtb_calc  !! XTB calculator instance
#endif
      calc_type_local = calc_type
      ! Query logger to determine verbosity
      call logger%configuration(level=current_log_level)
      is_verbose = (current_log_level >= verbose_level)
      ! Print fragment geometry if provided and verbose mode is enabled
      if (present(phys_frag)) then
         if (is_verbose) then
            call print_fragment_xyz(fragment_idx, phys_frag)
         end if
#ifndef MQC_WITHOUT_TBLITE
         ! Setup XTB method
         xtb_calc%variant = method_type_to_string(method)
         xtb_calc%verbose = is_verbose
         ! Set solvation options from module-level config
         if (allocated(xtb_options%solvent)) then
            xtb_calc%solvent = xtb_options%solvent
         end if
         if (allocated(xtb_options%solvation_model)) then
            xtb_calc%solvation_model = xtb_options%solvation_model
         end if
         xtb_calc%use_cds = xtb_options%use_cds
         xtb_calc%use_shift = xtb_options%use_shift
         ! CPCM-specific settings
         xtb_calc%dielectric = xtb_options%dielectric
         xtb_calc%cpcm_nang = xtb_options%cpcm_nang
         xtb_calc%cpcm_rscale = xtb_options%cpcm_rscale
         ! Run the calculation using the method API
         select case (calc_type_local)
         case (CALC_TYPE_ENERGY)
            call xtb_calc%calc_energy(phys_frag, result)
         case (CALC_TYPE_GRADIENT)
            call xtb_calc%calc_gradient(phys_frag, result)
         case (CALC_TYPE_HESSIAN)
            call xtb_calc%calc_hessian(phys_frag, result)
         case default
            call result%error%set(ERROR_VALIDATION, "Unknown calc_type: "//calc_type_to_string(calc_type_local))
            result%has_error = .true.
            return
         end select
         ! Check for calculation errors
         if (result%has_error) then
            call result%error%add_context("do_fragment_work:fragment_"//to_char(fragment_idx))
            return
         end if
         ! Copy fragment distance to result for JSON output
         result%distance = phys_frag%distance
#else
         call result%error%set(ERROR_GENERIC, "XTB method requested but tblite support not compiled in. "// &
                               "Please rebuild with -DMQC_ENABLE_TBLITE=ON")
         result%has_error = .true.
         return
#endif
      else
         ! For empty fragments, set energy to zero
         call result%energy%reset()
         result%has_energy = .true.
      end if
   end subroutine do_fragment_work
Call graph
do_fragment_work calls configuration, calc_type_to_string, energy_reset, error_add_context, error_set, method_type_to_string, print_fragment_xyz, xtb_calc_energy, xtb_calc_gradient, xtb_calc_hessian, to_char, do_fragment_work
energy_reset calls mp2_reset
print_fragment_xyz calls to_char, info, element_number_to_symbol, to_angstrom
xtb_calc_energy calls error_set, dpat, new, new_gfn1_calculator, new_gfn2_calculator, new_wavefunction, add_solvation_to_calc, energy_total, qat, xtb_singlepoint
xtb_calc_gradient calls error_set, dpat, new, new_gfn1_calculator, new_gfn2_calculator, new_wavefunction, add_solvation_to_calc, energy_total, qat, xtb_singlepoint
xtb_calc_hessian calls error_set, xtb_calc_gradient, to_char, info, finite_diff_dipole_derivatives, finite_diff_hessian_from_gradients, generate_perturbed_geometries, result_destroy
add_solvation_to_calc calls new_solvation, new_solvation_cds, new_solvation_shift, get_solvent_dielectric, push_back
energy_total calls mp2_total
generate_perturbed_geometries calls copy_and_displace_geometry
result_destroy calls result_reset
result_reset calls energy_reset, error_clear
node_worker calls do_fragment_work, node_worker
serial_fragment_processor calls do_fragment_work, serial_fragment_processor
serial_gmbe_pie_processor calls do_fragment_work
unfragmented_calculation calls do_fragment_work, unfragmented_calculation
run_fragmented_calculation calls serial_gmbe_pie_processor, node_worker, serial_fragment_processor
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
run_unfragmented_calculation calls unfragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation