element_mass – metalquicha
element_mass Function
10 statements
Source File
public pure function element_mass(atomic_number) result(mass)
Return atomic mass in atomic mass units (amu) for a given atomic number Uses standard atomic weights from IUPAC
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: atomic_number
Return Value real(kind=dp)
Called by
Source Code
   pure function element_mass(atomic_number) result(mass)
      !! Return atomic mass in atomic mass units (amu) for a given atomic number
      !! Uses standard atomic weights from IUPAC
      integer, intent(in) :: atomic_number
      real(dp) :: mass
      select case (atomic_number)
      case (1:118)
         mass = element_masses(atomic_number)
      case default
         mass = 0.0_dp  ! Unknown element
      end select
   end function element_mass
Call graph
compute_cartesian_displacements calls element_mass
compute_ir_intensities calls element_mass
compute_moments_of_inertia calls element_mass
compute_reduced_masses calls element_mass
mass_weight_hessian calls element_mass
project_translation_rotation calls element_mass
compute_thermochemistry calls compute_moments_of_inertia
compute_vibrational_analysis calls compute_cartesian_displacements, compute_ir_intensities, compute_reduced_masses, compute_vibrational_frequencies
compute_vibrational_frequencies calls mass_weight_hessian, project_translation_rotation
compute_gmbe calls compute_vibrational_analysis, print_vibrational_analysis
compute_mbe calls compute_thermochemistry, compute_vibrational_analysis, print_vibrational_analysis
gmbe_pie_coordinator calls compute_thermochemistry, compute_vibrational_analysis, print_vibrational_analysis
hessian_coordinator calls compute_thermochemistry, compute_vibrational_analysis, compute_vibrational_frequencies, print_vibrational_analysis, hessian_coordinator
print_vibrational_analysis calls compute_thermochemistry
serial_gmbe_pie_processor calls compute_thermochemistry, compute_vibrational_analysis, print_vibrational_analysis
unfragmented_calculation calls compute_thermochemistry, compute_vibrational_analysis, compute_vibrational_frequencies, print_vibrational_analysis, unfragmented_calculation
global_coordinator calls compute_mbe, global_coordinator
run_fragmented_calculation calls gmbe_pie_coordinator, serial_gmbe_pie_processor
serial_fragment_processor calls compute_mbe, serial_fragment_processor
distributed_unfragmented_hessian calls hessian_coordinator
run_calculation calls run_fragmented_calculation
run_unfragmented_calculation calls unfragmented_calculation