element_symbol_to_number – metalquicha
element_symbol_to_number Function
9 statements
Source File
public pure function element_symbol_to_number(symbol) result(atomic_number)
Convert element symbol to atomic number Covers the complete periodic table (elements 1-118)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: symbol
Return Value integer
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=2), private :: sym
Source Code
   pure function element_symbol_to_number(symbol) result(atomic_number)
      !! Convert element symbol to atomic number
      !! Covers the complete periodic table (elements 1-118)
      character(len=*), intent(in) :: symbol
      integer :: atomic_number
      character(len=2) :: sym
      ! Normalize: uppercase first letter, lowercase second
      sym = adjustl(symbol)
      if (len_trim(sym) >= 1) sym(1:1) = to_upper(sym(1:1))
      if (len_trim(sym) >= 2) sym(2:2) = to_lower(sym(2:2))
      ! Search for symbol in table
      atomic_number = findloc(element_symbols, sym, dim=1)
   end function element_symbol_to_number
Call graph
element_symbol_to_number calls to_lower, to_upper
geometry_to_system_unfragmented calls element_symbol_to_number
initialize_fragmented_system calls element_symbol_to_number
initialize_system_geometry calls element_symbol_to_number
config_to_system_geometry calls geometry_to_system_unfragmented, geometry_to_system_fragmented, molecule_to_system_geometry
geometry_to_system_fragmented calls initialize_fragmented_system
molecule_to_system_geometry calls geometry_to_system_unfragmented, initialize_fragmented_system
run_multi_molecule_calculations calls config_to_system_geometry
main calls config_to_system_geometry, run_multi_molecule_calculations