element_number_to_symbol – metalquicha
element_number_to_symbol Function
10 statements
Source File
public pure function element_number_to_symbol(atomic_number) result(symbol)
Convert atomic number to element symbol Covers the complete periodic table (elements 1-118)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: atomic_number
Return Value character(len=2)
Called by
Source Code
   pure function element_number_to_symbol(atomic_number) result(symbol)
      !! Convert atomic number to element symbol
      !! Covers the complete periodic table (elements 1-118)
      integer, intent(in) :: atomic_number
      character(len=2) :: symbol
      select case (atomic_number)
      case (1:118)
         symbol = element_symbols(atomic_number)
      case default
         symbol = 'Xx'  ! Unknown
      end select
   end function element_number_to_symbol
Call graph
check_duplicate_atoms calls element_number_to_symbol
print_fragment_xyz calls element_number_to_symbol
print_vibrational_analysis calls element_number_to_symbol
build_fragment_from_atom_list calls check_duplicate_atoms
build_fragment_from_indices calls check_duplicate_atoms
compute_gmbe calls print_vibrational_analysis, build_fragment_from_indices, process_intersection_derivatives
compute_mbe calls print_vibrational_analysis, map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian
do_fragment_work calls print_fragment_xyz, do_fragment_work
gmbe_pie_coordinator calls print_vibrational_analysis, build_fragment_from_atom_list
hessian_coordinator calls print_vibrational_analysis, hessian_coordinator
serial_gmbe_pie_processor calls print_vibrational_analysis, build_fragment_from_atom_list, do_fragment_work
unfragmented_calculation calls check_duplicate_atoms, print_vibrational_analysis, do_fragment_work, unfragmented_calculation
global_coordinator calls compute_mbe, global_coordinator
map_fragment_to_system_dipole_derivatives calls build_fragment_from_indices
map_fragment_to_system_gradient calls build_fragment_from_indices
map_fragment_to_system_hessian calls build_fragment_from_indices
node_worker calls build_fragment_from_atom_list, build_fragment_from_indices, do_fragment_work, node_worker
process_intersection_derivatives calls build_fragment_from_atom_list
run_fragmented_calculation calls gmbe_pie_coordinator, serial_gmbe_pie_processor, global_coordinator, node_worker, serial_fragment_processor
serial_fragment_processor calls build_fragment_from_indices, compute_mbe, do_fragment_work, serial_fragment_processor
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
distributed_unfragmented_hessian calls hessian_coordinator, distributed_unfragmented_hessian
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
run_unfragmented_calculation calls unfragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation