energy_total – metalquicha
energy_total Function
5 statements
Source File
private pure function energy_total(this) result(total)
Compute total energy from all components
Type Bound
energy_t
Arguments
Type Intent Optional Attributes Name
class(energy_t), intent(in) :: this
Return Value real(kind=dp)
Calls
Called by
Source Code
   pure function energy_total(this) result(total)
      !! Compute total energy from all components
      class(energy_t), intent(in) :: this
      real(dp) :: total
      ! this line needs to me modified if more components are added
      total = this%scf + this%mp2%total() + this%cc%total()
   end function energy_total
Call graph
energy_total calls mp2_total
compute_energy_and_forces calls energy_total, run_calculation
compute_gmbe_energy calls energy_total
compute_gmbe_energy_gradient calls energy_total
compute_gmbe_energy_gradient_hessian calls energy_total
compute_mbe_energy calls energy_total
compute_mbe_energy_gradient calls energy_total
compute_mbe_energy_gradient_hessian calls energy_total
gmbe_pie_coordinator calls energy_total
hessian_coordinator calls energy_total, print_unfragmented_json, xtb_calc_gradient, hessian_coordinator
hf_calc_energy calls energy_total
print_gmbe_json calls energy_total
print_unfragmented_json calls energy_total
serial_fragment_processor calls energy_total, compute_mbe_energy, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian, do_fragment_work, serial_fragment_processor
serial_gmbe_pie_processor calls energy_total, do_fragment_work
unfragmented_calculation calls energy_total, print_unfragmented_json, do_fragment_work, unfragmented_calculation
xtb_calc_energy calls energy_total
xtb_calc_gradient calls energy_total
do_fragment_work calls xtb_calc_energy, xtb_calc_gradient, xtb_calc_hessian, do_fragment_work
global_coordinator calls compute_mbe_energy, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian, global_coordinator
hessian_worker calls xtb_calc_gradient, hessian_worker
hf_calc_gradient calls hf_calc_energy
run_fragmented_calculation calls gmbe_pie_coordinator, serial_gmbe_pie_processor, serial_fragment_processor, global_coordinator
xtb_calc_hessian calls xtb_calc_gradient
distributed_unfragmented_hessian calls hessian_coordinator, hessian_worker, distributed_unfragmented_hessian
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
run_unfragmented_calculation calls unfragmented_calculation, distributed_unfragmented_hessian
node_worker calls do_fragment_work, node_worker
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations