energy_reset – metalquicha
energy_reset Subroutine
6 statements
Source File
private subroutine energy_reset(this)
Reset all energy components to zero
Type Bound
energy_t
Arguments
Type Intent Optional Attributes Name
class(energy_t), intent(inout) :: this
Calls
Called by
Source Code
   subroutine energy_reset(this)
      !! Reset all energy components to zero
      class(energy_t), intent(inout) :: this
      this%scf = 0.0_dp
      call this%mp2%reset()
      call this%cc%reset()
   end subroutine energy_reset
Call graph
energy_reset calls mp2_reset
do_fragment_work calls energy_reset, xtb_calc_hessian
result_reset calls energy_reset
node_worker calls do_fragment_work
result_destroy calls result_reset
serial_fragment_processor calls do_fragment_work
serial_gmbe_pie_processor calls do_fragment_work
unfragmented_calculation calls do_fragment_work, result_destroy
compute_energy_and_forces calls result_destroy, run_calculation
hessian_coordinator calls result_destroy
hessian_worker calls result_destroy
run_fragmented_calculation calls node_worker, serial_fragment_processor, serial_gmbe_pie_processor
run_unfragmented_calculation calls unfragmented_calculation, distributed_unfragmented_hessian
xtb_calc_hessian calls result_destroy
distributed_unfragmented_hessian calls hessian_coordinator, hessian_worker
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation