error_get_full_trace – metalquicha
error_get_full_trace Function
27 statements
Source File
private function error_get_full_trace(this) result(trace)
Get complete error message with stack trace Returns a multi-line string with error and call stack
Type Bound
error_t
Arguments
Type Intent Optional Attributes Name
class(error_t), intent(in) :: this
Return Value character(len=:), allocatable
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=2048), private :: buffer
integer, private :: i
integer, private :: pos
Source Code
   function error_get_full_trace(this) result(trace)
      !! Get complete error message with stack trace
      !! Returns a multi-line string with error and call stack
      class(error_t), intent(in) :: this
      character(len=:), allocatable :: trace
      character(len=2048) :: buffer
      integer :: i, pos
      if (.not. this%has_error()) then
         trace = ""
         return
      end if
      ! Build error message
      write (buffer, '(A,I0,A)') "Error ", this%code, ": "
      pos = len_trim(buffer) + 1
      if (allocated(this%message)) then
         buffer(pos:) = this%message
         pos = len_trim(buffer) + 1
      end if
      ! Add stack trace if available
      if (this%stack_depth > 0) then
         buffer(pos:) = new_line('a')//"Call stack (most recent first):"
         pos = len_trim(buffer) + 1
         do i = this%stack_depth, 1, -1
            write (buffer(pos:), '(A,I0,A)') new_line('a')//"  [", i, "] "
            pos = len_trim(buffer) + 1
            buffer(pos:) = trim(this%call_stack(i))
            pos = len_trim(buffer) + 1
         end do
      end if
      trace = trim(buffer)
   end function error_get_full_trace
Call graph
error_get_full_trace calls error_has_error
compute_gmbe_energy_gradient calls error_get_full_trace
compute_gmbe_energy_gradient_hessian calls error_get_full_trace
map_fragment_to_system_gradient calls error_get_full_trace
node_worker calls error_get_full_trace, node_worker
run_multi_molecule_calculations calls error_get_full_trace, run_calculation
serial_fragment_processor calls error_get_full_trace, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian, serial_fragment_processor
serial_gmbe_pie_processor calls error_get_full_trace
unfragmented_calculation calls error_get_full_trace, unfragmented_calculation
compute_mbe_energy_gradient calls map_fragment_to_system_gradient, compute_mbe_gradient
compute_mbe_energy_gradient_hessian calls map_fragment_to_system_gradient, compute_mbe_gradient
compute_mbe_gradient calls map_fragment_to_system_gradient
run_fragmented_calculation calls serial_gmbe_pie_processor, node_worker, serial_fragment_processor, global_coordinator
main calls run_multi_molecule_calculations, run_calculation
global_coordinator calls compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian, global_coordinator
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
run_unfragmented_calculation calls unfragmented_calculation
compute_energy_and_forces calls run_calculation