factory_create – metalquicha
factory_create Function
21 statements
Source File
private function factory_create(this, config) result(method)
Create a quantum chemistry method instance from configuration
Instantiates the appropriate concrete method type based on config%method_type and configures it from the nested config.
Type Bound
method_factory_t
Arguments
Type Intent Optional Attributes Name
class(method_factory_t), intent(in) :: this
type(method_config_t), intent(in) :: config
Return Value class(qc_method_t), allocatable
Calls
Called by
Source Code
   function factory_create(this, config) result(method)
      !! Create a quantum chemistry method instance from configuration
      !!
      !! Instantiates the appropriate concrete method type based on
      !! config%method_type and configures it from the nested config.
      class(method_factory_t), intent(in) :: this
      type(method_config_t), intent(in) :: config
      class(qc_method_t), allocatable :: method
      select case (config%method_type)
#ifndef MQC_WITHOUT_TBLITE
      case (METHOD_TYPE_GFN1, METHOD_TYPE_GFN2)
         allocate (xtb_method_t :: method)
         call configure_xtb(method, config)
#else
      case (METHOD_TYPE_GFN1, METHOD_TYPE_GFN2)
         error stop "XTB methods require tblite library (MQC_ENABLE_TBLITE)"
#endif
      case (METHOD_TYPE_HF)
         allocate (hf_method_t :: method)
         call configure_hf(method, config)
      case (METHOD_TYPE_DFT)
         allocate (dft_method_t :: method)
         call configure_dft(method, config)
      case (METHOD_TYPE_MCSCF)
         allocate (mcscf_method_t :: method)
         call configure_mcscf(method, config)
      case default
         error stop "Unknown method type in method_factory_t%create"
      end select
   end function factory_create
Call graph
factory_create calls configure_dft, configure_hf, configure_mcscf, configure_xtb
configure_mcscf calls state_weights
configure_xtb calls method_type_to_string, xtb_has_solvation
create_method calls factory_create
do_fragment_work calls create_method, do_fragment_work
hessian_coordinator calls create_method, hessian_coordinator
hessian_worker calls create_method, hessian_worker
distributed_unfragmented_hessian calls hessian_coordinator, hessian_worker, distributed_unfragmented_hessian
node_worker calls do_fragment_work, node_worker
serial_fragment_processor calls do_fragment_work, serial_fragment_processor
serial_gmbe_pie_processor calls do_fragment_work
unfragmented_calculation calls do_fragment_work, unfragmented_calculation
run_fragmented_calculation calls serial_gmbe_pie_processor