find_fragment_index – metalquicha
find_fragment_index Function
24 statements
Source File
public pure function find_fragment_index(target_monomers, polymers, fragment_count, expected_size) result(idx)
Find the fragment index that contains exactly the target monomers Uses int64 for fragment_count to handle large fragment counts that overflow int32.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: target_monomers(:)
integer, intent(in) :: polymers(:,:)
integer(kind=int64), intent(in) :: fragment_count
integer, intent(in) :: expected_size
Return Value integer(kind=int64)
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: fragment_size
integer(kind=int64), private :: i
integer, private :: j
logical, private :: match
Source Code
   pure function find_fragment_index(target_monomers, polymers, fragment_count, expected_size) result(idx)
      !! Find the fragment index that contains exactly the target monomers
      !! Uses int64 for fragment_count to handle large fragment counts that overflow int32.
      integer, intent(in) :: target_monomers(:), polymers(:, :), expected_size
      integer(int64), intent(in) :: fragment_count
      integer(int64) :: idx
      integer(int64) :: i
      integer :: j, fragment_size
      logical :: match
      idx = -1_int64
      do i = 1_int64, fragment_count
         fragment_size = count(polymers(i, :) > 0)
         ! Check if this fragment has the right size
         if (fragment_size /= expected_size) cycle
         ! Check if all target monomers are in this fragment
         match = .true.
         do j = 1, expected_size
            if (.not. any(polymers(i, 1:fragment_size) == target_monomers(j))) then
               match = .false.
               exit
            end if
         end do
         if (match) then
            idx = i
            return
         end if
      end do
      ! If we get here, we didn't find the fragment
      ! this should RARELY happen, unless someone did something very illegal
      ! this needs to be passed into an error log
      !block
      !   character(len=256) :: monomers_str
      !   integer :: k
      !   write (monomers_str, '(*(i0,1x))') (target_monomers(k), k=1, size(target_monomers))
      !   call logger%error("Could not find fragment with monomers: "//trim(monomers_str))
      !end block
      !error stop "Fragment not found in find_fragment_index"
   end function find_fragment_index
Call graph
compute_delta_nbody calls find_fragment_index, generate_and_subtract_subsets
generate_and_subtract_subsets calls find_fragment_index, compute_delta_nbody
compute_mbe_energy calls compute_delta_nbody
global_coordinator calls compute_mbe_energy
serial_fragment_processor calls compute_mbe_energy
run_fragmented_calculation calls global_coordinator, serial_fragment_processor
run_calculation calls run_fragmented_calculation