fragment_destroy – metalquicha
fragment_destroy Subroutine
16 statements
Source File
private subroutine fragment_destroy(this)
Clean up allocated memory in physical_fragment_t
Type Bound
physical_fragment_t
Arguments
Type Intent Optional Attributes Name
class(physical_fragment_t), intent(inout) :: this
Calls
Called by
Source Code
   subroutine fragment_destroy(this)
      !! Clean up allocated memory in physical_fragment_t
      class(physical_fragment_t), intent(inout) :: this
      if (allocated(this%element_numbers)) deallocate (this%element_numbers)
      if (allocated(this%coordinates)) deallocate (this%coordinates)
      if (allocated(this%cap_replaces_atom)) deallocate (this%cap_replaces_atom)
      if (allocated(this%local_to_global)) deallocate (this%local_to_global)
      if (allocated(this%basis)) then
         call this%basis%destroy()
         deallocate (this%basis)
      end if
      this%n_atoms = 0
      this%charge = 0
      this%multiplicity = 1
      this%nelec = 0
      this%n_caps = 0
   end subroutine fragment_destroy
Call graph
fragment_destroy calls basis_set_destroy
basis_set_destroy calls atomic_basis_destroy
atomic_basis_destroy calls cgto_destroy
compute_gmbe calls fragment_destroy, process_intersection_derivatives
displaced_geometry_destroy calls fragment_destroy
gmbe_pie_coordinator calls fragment_destroy
map_fragment_to_system_dipole_derivatives calls fragment_destroy
map_fragment_to_system_gradient calls fragment_destroy
map_fragment_to_system_hessian calls fragment_destroy
node_worker calls fragment_destroy, node_worker
process_intersection_derivatives calls fragment_destroy
serial_fragment_processor calls fragment_destroy, compute_mbe, serial_fragment_processor
serial_gmbe_pie_processor calls fragment_destroy
compute_mbe calls map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
run_fragmented_calculation calls gmbe_pie_coordinator, serial_gmbe_pie_processor, node_worker, serial_fragment_processor, global_coordinator
global_coordinator calls compute_mbe, global_coordinator
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations