fragment_lookup_destroy – metalquicha
fragment_lookup_destroy Subroutine
18 statements
Source File
private subroutine fragment_lookup_destroy(this)
Clean up hash table and all chains
Type Bound
fragment_lookup_t
Arguments
Type Intent Optional Attributes Name
class(fragment_lookup_t), intent(inout) :: this
Called by
Variables
Type Visibility Attributes Name Initial
type(hash_entry_t), private, pointer :: entry
integer, private :: i
type(hash_entry_t), private, pointer :: next_entry
Source Code
   subroutine fragment_lookup_destroy(this)
      !! Clean up hash table and all chains
      class(fragment_lookup_t), intent(inout) :: this
      integer :: i
      type(hash_entry_t), pointer :: entry, next_entry
      if (.not. this%initialized) return
      do i = 1, this%table_size
         ! Free chain
         entry => this%table(i)%next
         do while (associated(entry))
            next_entry => entry%next
            if (allocated(entry%key)) deallocate (entry%key)
            deallocate (entry)
            entry => next_entry
         end do
         ! Free bucket head
         if (allocated(this%table(i)%key)) deallocate (this%table(i)%key)
      end do
      deallocate (this%table)
      this%initialized = .false.
   end subroutine fragment_lookup_destroy
Call graph
compute_mbe_energy calls fragment_lookup_destroy
compute_mbe_energy_gradient calls fragment_lookup_destroy
compute_mbe_energy_gradient_hessian calls fragment_lookup_destroy
global_coordinator calls compute_mbe_energy, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian
serial_fragment_processor calls compute_mbe_energy, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian
run_fragmented_calculation calls global_coordinator, serial_fragment_processor
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation