fragment_lookup_init – metalquicha
fragment_lookup_init Subroutine
12 statements
Source File
private subroutine fragment_lookup_init(this, estimated_entries)
Initialize hash table with estimated size
Type Bound
fragment_lookup_t
Arguments
Type Intent Optional Attributes Name
class(fragment_lookup_t), intent(inout) :: this
integer(kind=int64), intent(in) :: estimated_entries
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
Source Code
   subroutine fragment_lookup_init(this, estimated_entries)
      !! Initialize hash table with estimated size
      class(fragment_lookup_t), intent(inout) :: this
      integer(int64), intent(in) :: estimated_entries
      integer :: i
      ! Use prime number close to estimated size for better distribution
      this%table_size = next_prime_internal(int(estimated_entries*1.3_8))
      allocate (this%table(this%table_size))
      ! Initialize all entries as empty
      do i = 1, this%table_size
         nullify (this%table(i)%next)
      end do
      this%n_entries = 0
      this%initialized = .true.
   end subroutine fragment_lookup_init
Call graph
fragment_lookup_init calls next_prime_internal
compute_mbe_energy calls fragment_lookup_init
compute_mbe_energy_gradient calls fragment_lookup_init
global_coordinator calls compute_mbe_energy, compute_mbe_energy_gradient
serial_fragment_processor calls compute_mbe_energy, compute_mbe_energy_gradient
run_fragmented_calculation calls global_coordinator, serial_fragment_processor
run_calculation calls run_fragmented_calculation
main calls run_calculation