fragment_lookup_insert – metalquicha
fragment_lookup_insert Subroutine
36 statements
Source File
private subroutine fragment_lookup_insert(this, monomers, n, fragment_idx, error)
Insert a monomer combination -> fragment index mapping
Type Bound
fragment_lookup_t
Arguments
Type Intent Optional Attributes Name
class(fragment_lookup_t), intent(inout) :: this
integer, intent(in) :: monomers(:)
integer, intent(in) :: n
integer(kind=int64), intent(in) :: fragment_idx
type(error_t), intent(out), optional :: error
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: bucket
integer(kind=int32), private :: hash_val
type(hash_entry_t), private, pointer :: new_entry
integer, private, allocatable :: sorted_key(:)
Source Code
   subroutine fragment_lookup_insert(this, monomers, n, fragment_idx, error)
      !! Insert a monomer combination -> fragment index mapping
      class(fragment_lookup_t), intent(inout) :: this
      integer, intent(in) :: monomers(:), n
      integer(int64), intent(in) :: fragment_idx
      type(error_t), intent(out), optional :: error
      integer(int32) :: hash_val
      integer :: bucket
      type(hash_entry_t), pointer :: new_entry
      integer, allocatable :: sorted_key(:)
      if (.not. this%initialized) then
         if (present(error)) then
            call error%set(ERROR_VALIDATION, "Hash table not initialized")
         end if
         return
      end if
      ! Sort monomers for canonical key
      allocate (sorted_key(n))
      sorted_key = monomers(1:n)
      call sort(sorted_key)
      ! Compute hash
      hash_val = fnv_1a_hash(sorted_key)
      bucket = 1 + modulo(hash_val, int(this%table_size, int32))
      ! Check if this is the first entry in bucket
      if (.not. allocated(this%table(bucket)%key)) then
         ! First entry in this bucket - use the head entry
         allocate (this%table(bucket)%key(n))
         this%table(bucket)%key = sorted_key
         this%table(bucket)%value = fragment_idx
         this%n_entries = this%n_entries + 1
      else
         ! Bucket already has entries - chain new entry
         allocate (new_entry)
         allocate (new_entry%key(n))
         new_entry%key = sorted_key
         new_entry%value = fragment_idx
         new_entry%next => this%table(bucket)%next
         this%table(bucket)%next => new_entry
         this%n_entries = this%n_entries + 1
      end if
      deallocate (sorted_key)
   end subroutine fragment_lookup_insert
Call graph
fragment_lookup_insert calls fnv_1a_hash, error_set, sort
build_mbe_lookup_table calls fragment_lookup_insert
compute_mbe calls build_mbe_lookup_table
global_coordinator calls compute_mbe, global_coordinator
serial_fragment_processor calls compute_mbe, serial_fragment_processor
mbe_run_distributed calls global_coordinator
mbe_run_serial calls serial_fragment_processor