generate_fragment_list – metalquicha
generate_fragment_list Subroutine
10 statements
Source File
public recursive subroutine generate_fragment_list(monomers, max_level, polymers, count)
Generate all possible fragments (combinations of monomers) up to max_level Uses int64 for count to handle large numbers of fragments that overflow int32.
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: monomers(:)
integer(kind=default_int), intent(in) :: max_level
integer(kind=default_int), intent(inout) :: polymers(:,:)
integer(kind=int64), intent(inout) :: count
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=default_int), private :: n
integer(kind=default_int), private :: r
Source Code
   recursive subroutine generate_fragment_list(monomers, max_level, polymers, count)
      !! Generate all possible fragments (combinations of monomers) up to max_level
      !! Uses int64 for count to handle large numbers of fragments that overflow int32.
      integer(default_int), intent(in) :: monomers(:), max_level
      integer(default_int), intent(inout) :: polymers(:, :)
      integer(int64), intent(inout) :: count
      integer(default_int) :: r, n
      n = size(monomers, 1)
      do r = 2, max_level
         call combine(monomers, n, r, polymers, count)
      end do
   end subroutine generate_fragment_list
Call graph
generate_fragment_list calls combine
combine calls combine_util
combine_util calls combine_util
run_fragmented_calculation calls generate_fragment_list
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations