geometry_to_system_fragmented – metalquicha
geometry_to_system_fragmented Subroutine
7 statements
Source File
private subroutine geometry_to_system_fragmented(mqc_config, sys_geom, use_angstrom, error)
Convert geometry to system_geometry_t for fragmented calculation Supports both identical and variable-sized fragments
Arguments
Type Intent Optional Attributes Name
type(mqc_config_t), intent(in) :: mqc_config
type(system_geometry_t), intent(out) :: sys_geom
logical, intent(in) :: use_angstrom
type(error_t), intent(out) :: error
Calls
Called by
Source Code
   subroutine geometry_to_system_fragmented(mqc_config, sys_geom, use_angstrom, error)
      !! Convert geometry to system_geometry_t for fragmented calculation
      !! Supports both identical and variable-sized fragments
      type(mqc_config_t), intent(in) :: mqc_config
      type(system_geometry_t), intent(out) :: sys_geom
      logical, intent(in) :: use_angstrom
      type(error_t), intent(out) :: error
      call initialize_fragmented_system(mqc_config%nfrag, mqc_config%geometry, mqc_config%fragments, &
                                        mqc_config%charge, mqc_config%multiplicity, &
                                        mqc_config%allow_overlapping_fragments, use_angstrom, &
                                        sys_geom, error)
   end subroutine geometry_to_system_fragmented
Call graph
geometry_to_system_fragmented calls initialize_fragmented_system
initialize_fragmented_system calls check_fragment_overlap, element_symbol_to_number, error_add_context, error_has_error, to_bohr
check_fragment_overlap calls error_set, to_char
element_symbol_to_number calls to_lower, to_upper
config_to_system_geometry calls geometry_to_system_fragmented
run_multi_molecule_calculations calls config_to_system_geometry
main calls config_to_system_geometry, run_multi_molecule_calculations