get_basename – metalquicha
get_basename Function
11 statements
Source File
public function get_basename() result(basename)
Get the base name without “output_” prefix and “.json” suffix Example: “output_w1.json” -> “w1”
Arguments
None
Return Value character(len=256)
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: end_pos
integer, private :: start_pos
Source Code
   function get_basename() result(basename)
      !! Get the base name without "output_" prefix and ".json" suffix
      !! Example: "output_w1.json" -> "w1"
      character(len=256) :: basename
      integer :: start_pos, end_pos
      ! Remove "output_" prefix (7 characters)
      start_pos = 8
      ! Find ".json" suffix
      end_pos = index(output_json_filename, '.json', back=.true.) - 1
      if (end_pos > start_pos) then
         basename = output_json_filename(start_pos:end_pos)
      else
         basename = "unknown"
      end if
   end function get_basename
Call graph
print_detailed_breakdown_json calls get_basename
print_gmbe_json calls get_basename
print_gmbe_pie_json calls get_basename
print_unfragmented_json calls get_basename
write_vibrational_json_impl calls get_basename
compute_mbe calls print_detailed_breakdown_json, print_vibrational_json_mbe
gmbe_pie_coordinator calls print_gmbe_pie_json, print_vibrational_json_mbe
hessian_coordinator calls print_unfragmented_json, print_vibrational_json, hessian_coordinator
print_vibrational_json calls write_vibrational_json_impl
print_vibrational_json_mbe calls write_vibrational_json_impl
serial_gmbe_pie_processor calls print_gmbe_pie_json, print_vibrational_json_mbe
unfragmented_calculation calls print_unfragmented_json, print_vibrational_json, unfragmented_calculation
global_coordinator calls compute_mbe, global_coordinator
run_fragmented_calculation calls gmbe_pie_coordinator, serial_gmbe_pie_processor, global_coordinator, serial_fragment_processor
serial_fragment_processor calls compute_mbe, serial_fragment_processor
distributed_unfragmented_hessian calls hessian_coordinator, distributed_unfragmented_hessian
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
run_unfragmented_calculation calls unfragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation