get_nfrags – metalquicha
get_nfrags Function
10 statements
Source File
public pure function get_nfrags(n_monomers, max_level) result(n_expected_fragments)
Calculate total number of fragments for given system size and max level
Computes the sum of binomial coefficients C(n,k) for k=1 to max_level, representing all possible fragments from monomers to max_level-mers. Uses int64 to handle large fragment counts that overflow int32.
Arguments
Type Intent Optional Attributes Name
integer(kind=default_int), intent(in) :: n_monomers
Number of monomers in system
integer(kind=default_int), intent(in) :: max_level
Maximum fragment size
Return Value integer(kind=int64)
Total fragment count
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=default_int), private :: i
Loop counter
Source Code
   pure function get_nfrags(n_monomers, max_level) result(n_expected_fragments)
      !! Calculate total number of fragments for given system size and max level
      !!
      !! Computes the sum of binomial coefficients C(n,k) for k=1 to max_level,
      !! representing all possible fragments from monomers to max_level-mers.
      !! Uses int64 to handle large fragment counts that overflow int32.
      integer(default_int), intent(in) :: n_monomers  !! Number of monomers in system
      integer(default_int), intent(in) :: max_level   !! Maximum fragment size
      integer(int64) :: n_expected_fragments     !! Total fragment count
      integer(default_int) :: i  !! Loop counter
      n_expected_fragments = 0_int64
      do i = 1, max_level
         n_expected_fragments = n_expected_fragments + binomial(n_monomers, i)
      end do
   end function get_nfrags
Call graph
get_nfrags calls binomial
run_fragmented_calculation calls get_nfrags
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations