get_output_json_filename – metalquicha
get_output_json_filename Function
4 statements
Source File
public function get_output_json_filename() result(filename)
Get the current JSON output filename
Arguments
None
Return Value character(len=256)
Called by
Source Code
   function get_output_json_filename() result(filename)
      !! Get the current JSON output filename
      character(len=256) :: filename
      filename = trim(output_json_filename)
   end function get_output_json_filename
Call graph
print_detailed_breakdown_json calls get_output_json_filename
print_gmbe_json calls get_output_json_filename
print_gmbe_pie_json calls get_output_json_filename
print_unfragmented_json calls get_output_json_filename
run_multi_molecule_calculations calls get_output_json_filename, run_calculation
write_vibrational_json_impl calls get_output_json_filename
compute_mbe calls print_detailed_breakdown_json, print_vibrational_json_mbe
gmbe_pie_coordinator calls print_gmbe_pie_json, print_vibrational_json_mbe
hessian_coordinator calls print_unfragmented_json, print_vibrational_json, hessian_coordinator
print_vibrational_json calls write_vibrational_json_impl
print_vibrational_json_mbe calls write_vibrational_json_impl
serial_gmbe_pie_processor calls print_gmbe_pie_json, print_vibrational_json_mbe
unfragmented_calculation calls print_unfragmented_json, print_vibrational_json, unfragmented_calculation
main calls run_multi_molecule_calculations, run_calculation
global_coordinator calls compute_mbe, global_coordinator
run_fragmented_calculation calls gmbe_pie_coordinator, serial_gmbe_pie_processor, global_coordinator, serial_fragment_processor
serial_fragment_processor calls compute_mbe, serial_fragment_processor
distributed_unfragmented_hessian calls hessian_coordinator, distributed_unfragmented_hessian
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
run_unfragmented_calculation calls unfragmented_calculation
compute_energy_and_forces calls run_calculation