get_frag_level_name – metalquicha
get_frag_level_name Function
28 statements
Source File
private function get_frag_level_name(frag_level) result(level_name)
Map body level (n-mer) to descriptive name Supports up to decamers (10-mers), then falls back to “N-mers” format
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: frag_level
Return Value character(len=32)
Called by
Source Code
   function get_frag_level_name(frag_level) result(level_name)
      !! Map body level (n-mer) to descriptive name
      !! Supports up to decamers (10-mers), then falls back to "N-mers" format
      integer, intent(in) :: frag_level
      character(len=32) :: level_name
      select case (frag_level)
      case (1)
         level_name = "monomers"
      case (2)
         level_name = "dimers"
      case (3)
         level_name = "trimers"
      case (4)
         level_name = "tetramers"
      case (5)
         level_name = "pentamers"
      case (6)
         level_name = "hexamers"
      case (7)
         level_name = "heptamers"
      case (8)
         level_name = "octamers"
      case (9)
         level_name = "nonamers"
      case (10)
         level_name = "decamers"
      case default
         ! For levels > 10, use generic format
         write (level_name, '(i0,a)') frag_level, "-mers"
      end select
   end function get_frag_level_name
Call graph
print_detailed_breakdown calls get_frag_level_name
print_detailed_breakdown_json calls get_frag_level_name
compute_mbe_energy calls print_detailed_breakdown, print_detailed_breakdown_json
compute_mbe_energy_gradient calls print_detailed_breakdown, print_detailed_breakdown_json
compute_mbe_energy_gradient_hessian calls print_detailed_breakdown_json
global_coordinator calls compute_mbe_energy, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian
serial_fragment_processor calls compute_mbe_energy, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian
run_fragmented_calculation calls global_coordinator, serial_fragment_processor
run_calculation calls run_fragmented_calculation