get_molecule_name – metalquicha
get_molecule_name Function
18 statements
Source File
public function get_molecule_name(filename) result(name)
Extract molecule name from filename Example: “output_multi_structure_molecule_1.json” -> “molecule_1”
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: filename
Return Value character(len=256)
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: end_pos
integer, private :: start_pos
Source Code
   function get_molecule_name(filename) result(name)
      !! Extract molecule name from filename
      !! Example: "output_multi_structure_molecule_1.json" -> "molecule_1"
      character(len=*), intent(in) :: filename
      character(len=256) :: name
      integer :: start_pos, end_pos
      ! Find "_molecule_" or similar pattern
      start_pos = index(filename, '_molecule_')
      if (start_pos == 0) start_pos = index(filename, '_mol_')
      if (start_pos > 0) then
         start_pos = start_pos + 1  ! Skip leading underscore
         end_pos = index(filename, '.json') - 1
         if (end_pos > start_pos) then
            name = filename(start_pos:end_pos)
         else
            name = "unknown"
         end if
      else
         name = "unknown"
      end if
   end function get_molecule_name
Call graph
read_json_content calls get_molecule_name
merge_multi_molecule_json calls read_json_content
run_multi_molecule_calculations calls merge_multi_molecule_json
main calls run_multi_molecule_calculations