gmbe_run_distributed – metalquicha
gmbe_run_distributed Subroutine
29 statements
Source File
private subroutine gmbe_run_distributed(this, json_data)
Uses
pic_io
mqc_gmbe_fragment_distribution_scheme
pic_logger
mqc_mbe_fragment_distribution_scheme
omp_lib
Run distributed GMBE calculation
Type Bound
gmbe_context_t
Arguments
Type Intent Optional Attributes Name
class(gmbe_context_t), intent(inout) :: this
type(json_output_data_t), intent(out), optional :: json_data
Calls
Source Code
   subroutine gmbe_run_distributed(this, json_data)
      !! Run distributed GMBE calculation
      use mqc_gmbe_fragment_distribution_scheme, only: gmbe_pie_coordinator
      use mqc_mbe_fragment_distribution_scheme, only: node_coordinator, node_worker
      use pic_logger, only: logger => global_logger
      use pic_io, only: to_char
      use omp_lib, only: omp_set_num_threads, omp_get_max_threads
      class(gmbe_context_t), intent(inout) :: this
      type(json_output_data_t), intent(out), optional :: json_data
      if (.not. this%has_mpi()) then
         call logger%error("gmbe_run_distributed: resources not set in context")
         return
      end if
      ! Determine role based on MPI rank
      if (this%resources%mpi_comms%world_comm%leader() .and. &
          this%resources%mpi_comms%node_comm%leader()) then
         ! Global coordinator (rank 0, node leader on node 0)
         call omp_set_num_threads(omp_get_max_threads())
         call logger%verbose("Rank 0: Acting as GMBE PIE coordinator")
         call gmbe_pie_coordinator(this%resources, this%pie_atom_sets, this%pie_coefficients, &
                                   this%n_pie_terms, this%node_leader_ranks, this%num_nodes, &
                                   this%sys_geom, this%method_config, this%calc_type, json_data)
      else if (this%resources%mpi_comms%node_comm%leader()) then
         ! Node coordinator (node leader on other nodes)
         call logger%verbose("Rank "//to_char(this%resources%mpi_comms%world_comm%rank())// &
                             ": Acting as node coordinator")
         ! Note: node_coordinator works for both MBE and GMBE
         call node_coordinator(this%resources, this%method_config, this%calc_type)
      else
         ! Worker
         call omp_set_num_threads(1)
         call logger%verbose("Rank "//to_char(this%resources%mpi_comms%world_comm%rank())// &
                             ": Acting as worker")
         ! Note: node_worker works for both MBE and GMBE (fragment_type distinguishes)
         if (this%has_geometry()) then
            call node_worker(this%resources, this%sys_geom, this%method_config, this%calc_type)
         else
            call node_worker(this%resources, method_config=this%method_config, &
                             calc_type=this%calc_type)
         end if
      end if
   end subroutine gmbe_run_distributed
Call graph
gmbe_run_distributed calls error, node_coordinator, node_worker, leader, omp_get_max_threads, omp_set_num_threads, gmbe_pie_coordinator, mbe_base_has_geometry, mbe_base_has_mpi, to_char, verbose
node_coordinator calls node_coordinator, error, to_char, abort_comm, iprobe, irecv, isend, error_get_message, result_irecv, result_isend, recv
node_worker calls node_worker, error, to_char, abort_comm, irecv, isend, build_fragment_from_atom_list, fragment_destroy, do_fragment_work, build_fragment_from_indices, error_get_full_trace, error_has_error, result_isend, recv
gmbe_pie_coordinator calls error, to_char, verbose, abort_comm, cart_disp, configuration, fc_mdyne, force_constants, frequencies, get_elapsed_time, info, iprobe, irecv, isend, build_fragment_from_atom_list, compute_thermochemistry, compute_vibrational_analysis, energy_total, error_get_message, fragment_destroy, print_vibrational_analysis, redistribute_cap_dipole_derivatives, redistribute_cap_gradients, redistribute_cap_hessian, result_irecv, send_pie_term_to_node, send_pie_term_to_worker, reduced_masses, start
build_fragment_from_atom_list calls add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, error_has_error, fragment_compute_nelec
compute_thermochemistry calls compute_electronic_entropy, compute_moments_of_inertia, compute_partition_functions, compute_rotational_constants, compute_rotational_thermo, compute_translational_thermo, compute_vibrational_thermo, compute_zpe
compute_vibrational_analysis calls compute_cartesian_displacements, compute_force_constants, compute_ir_intensities, compute_reduced_masses, compute_vibrational_frequencies
energy_total calls mp2_total
fragment_destroy calls basis_set_destroy
print_vibrational_analysis calls info, compute_thermochemistry, element_number_to_symbol, print_thermochemistry, warning
result_irecv calls irecv, recv
send_pie_term_to_node calls isend
send_pie_term_to_worker calls isend
do_fragment_work calls do_fragment_work, to_char, configuration, error_add_context, error_set, calc_energy, calc_gradient, calc_hessian, calc_type_to_string, create_method, energy_reset, print_fragment_xyz
basis_set_destroy calls atomic_basis_destroy
build_fragment_from_indices calls add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, error_has_error, fragment_compute_nelec, calculate_monomer_distance
check_duplicate_atoms calls error, to_char, element_number_to_symbol, error_set
compute_cartesian_displacements calls element_mass
compute_ir_intensities calls element_mass
compute_moments_of_inertia calls to_char, warning, pic_syev, element_mass
compute_reduced_masses calls element_mass
compute_vibrational_frequencies calls error, warning, pic_syev, mass_weight_hessian, project_translation_rotation
compute_zpe calls to_char, warning
error_get_full_trace calls error_has_error
print_thermochemistry calls info
result_isend calls isend, send
atomic_basis_destroy calls cgto_destroy
calculate_monomer_distance calls to_angstrom
mass_weight_hessian calls element_mass
project_translation_rotation calls element_mass, pic_gesvd