gmbe_run_serial – metalquicha
gmbe_run_serial Subroutine
11 statements
Source File
private subroutine gmbe_run_serial(this, json_data)
Uses
mqc_gmbe_fragment_distribution_scheme
pic_logger
Run serial GMBE calculation
Type Bound
gmbe_context_t
Arguments
Type Intent Optional Attributes Name
class(gmbe_context_t), intent(inout) :: this
type(json_output_data_t), intent(out), optional :: json_data
Calls
Source Code
   subroutine gmbe_run_serial(this, json_data)
      !! Run serial GMBE calculation
      use mqc_gmbe_fragment_distribution_scheme, only: serial_gmbe_pie_processor
      use pic_logger, only: logger => global_logger
      class(gmbe_context_t), intent(inout) :: this
      type(json_output_data_t), intent(out), optional :: json_data
      if (.not. this%has_geometry()) then
         call logger%error("gmbe_run_serial: sys_geom required but not set")
         return
      end if
      call serial_gmbe_pie_processor(this%pie_atom_sets, this%pie_coefficients, &
                                     this%n_pie_terms, this%sys_geom, this%method_config, &
                                     this%calc_type, json_data)
   end subroutine gmbe_run_serial
Call graph
gmbe_run_serial calls error, mbe_base_has_geometry, serial_gmbe_pie_processor
serial_gmbe_pie_processor calls error, cart_disp, configuration, fc_mdyne, force_constants, frequencies, info, do_fragment_work, build_fragment_from_atom_list, calc_type_to_string, compute_thermochemistry, compute_vibrational_analysis, energy_total, error_get_full_trace, error_get_message, error_has_error, fragment_destroy, print_vibrational_analysis, redistribute_cap_dipole_derivatives, redistribute_cap_gradients, redistribute_cap_hessian, reduced_masses, to_char, verbose
do_fragment_work calls do_fragment_work, configuration, calc_type_to_string, to_char, error_add_context, calc_energy, calc_gradient, calc_hessian, create_method, energy_reset, error_set, print_fragment_xyz
build_fragment_from_atom_list calls error_has_error, add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
compute_thermochemistry calls compute_electronic_entropy, compute_moments_of_inertia, compute_partition_functions, compute_rotational_constants, compute_rotational_thermo, compute_translational_thermo, compute_vibrational_thermo, compute_zpe
compute_vibrational_analysis calls compute_cartesian_displacements, compute_force_constants, compute_ir_intensities, compute_reduced_masses, compute_vibrational_frequencies
energy_total calls mp2_total
error_get_full_trace calls error_has_error
fragment_destroy calls basis_set_destroy
print_vibrational_analysis calls info, compute_thermochemistry, element_number_to_symbol, print_thermochemistry, warning
basis_set_destroy calls atomic_basis_destroy
check_duplicate_atoms calls error, to_char, element_number_to_symbol, error_set
compute_cartesian_displacements calls element_mass
compute_ir_intensities calls element_mass
compute_moments_of_inertia calls to_char, warning, pic_syev, element_mass
compute_reduced_masses calls element_mass
compute_vibrational_frequencies calls error, warning, pic_syev, mass_weight_hessian, project_translation_rotation
compute_zpe calls to_char, warning
print_thermochemistry calls info
atomic_basis_destroy calls cgto_destroy
create_method calls factory_create
energy_reset calls mp2_reset
mass_weight_hessian calls element_mass
print_fragment_xyz calls info, to_char, element_number_to_symbol, to_angstrom
project_translation_rotation calls element_mass, pic_gesvd