hf_calc_gradient – metalquicha
hf_calc_gradient Subroutine
11 statements
Source File
private subroutine hf_calc_gradient(this, fragment, result)
Calculate energy gradient using Hartree-Fock method
Type Bound
hf_method_t
Arguments
Type Intent Optional Attributes Name
class(hf_method_t), intent(in) :: this
type(physical_fragment_t), intent(in) :: fragment
type(calculation_result_t), intent(out) :: result
Calls
Source Code
   subroutine hf_calc_gradient(this, fragment, result)
      !! Calculate energy gradient using Hartree-Fock method
      class(hf_method_t), intent(in) :: this
      type(physical_fragment_t), intent(in) :: fragment
      type(calculation_result_t), intent(out) :: result
      ! DUMMY IMPLEMENTATION
      ! TODO: Implement gradient calculation
      ! 1. Calculate energy (call calc_energy)
      ! 2. Calculate gradient using integral derivatives
      print *, "HF: Calculating gradient for fragment with", fragment%n_atoms, "atoms"
      ! First get energy
      call this%calc_energy(fragment, result)
      ! Allocate and fill dummy gradient
      allocate (result%gradient(3, fragment%n_atoms))
      result%gradient = 0.0_dp  ! Placeholder
      result%has_gradient = .true.
      print *, "HF: Dummy gradient allocated"
   end subroutine hf_calc_gradient
Call graph
hf_calc_gradient calls hf_calc_energy
hf_calc_energy calls energy_total
energy_total calls mp2_total