intersect_atom_lists – metalquicha
intersect_atom_lists Subroutine
18 statements
Source File
private subroutine intersect_atom_lists(atoms1, n1, atoms2, n2, intersection, n_intersect)
Compute intersection of two atom lists
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: atoms1(:)
integer, intent(in) :: n1
integer, intent(in) :: atoms2(:)
integer, intent(in) :: n2
integer, intent(out) :: intersection(:)
integer, intent(out) :: n_intersect
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
integer, private :: j
Source Code
   subroutine intersect_atom_lists(atoms1, n1, atoms2, n2, intersection, n_intersect)
      !! Compute intersection of two atom lists
      integer, intent(in) :: atoms1(:), n1, atoms2(:), n2
      integer, intent(out) :: intersection(:)
      integer, intent(out) :: n_intersect
      integer :: i, j
      n_intersect = 0
      do i = 1, n1
         if (atoms1(i) < 0) cycle
         do j = 1, n2
            if (atoms2(j) < 0) cycle
            if (atoms1(i) == atoms2(j)) then
               n_intersect = n_intersect + 1
               intersection(n_intersect) = atoms1(i)
               exit
            end if
         end do
      end do
   end subroutine intersect_atom_lists
Call graph
dfs_pie_accumulate calls intersect_atom_lists, dfs_pie_accumulate
gmbe_enumerate_pie_terms calls dfs_pie_accumulate
run_fragmented_calculation calls gmbe_enumerate_pie_terms
run_calculation calls run_fragmented_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation