is_shell_header – metalquicha
is_shell_header Function
12 statements
Source File
private pure function is_shell_header(line) result(res)
Check if a line is a shell header line (starts with S, P, D, F, G, H, I, or L)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: line
Return Value logical
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: dummy
character(len=1), private :: first_char
integer, private :: ios
Source Code
   pure function is_shell_header(line) result(res)
      !! Check if a line is a shell header line (starts with S, P, D, F, G, H, I, or L)
      character(len=*), intent(in) :: line
      logical :: res
      character(len=1) :: first_char
      integer :: ios, dummy
      res = .false.
      if (len_trim(line) == 0) return
      first_char = line(1:1)
      if (.not. any(first_char == ['S', 'P', 'D', 'F', 'G', 'H', 'I', 'L'])) return
      read (line(2:), *, iostat=ios) dummy
      res = (ios == 0)
   end function is_shell_header
Call graph
classify_line calls is_shell_header
count_shells_for_element calls classify_line
fill_element_basis calls classify_line
parse_element_basis calls count_shells_for_element, fill_element_basis
build_molecular_basis calls parse_element_basis