json_output_data_destroy – metalquicha
json_output_data_destroy Subroutine
19 statements
Source File
private subroutine json_output_data_destroy(this)
Clean up all allocated memory
Type Bound
json_output_data_t
Arguments
Type Intent Optional Attributes Name
class(json_output_data_t), intent(inout) :: this
Calls
Called by
Source Code
   subroutine json_output_data_destroy(this)
      !! Clean up all allocated memory
      class(json_output_data_t), intent(inout) :: this
      ! Common data
      if (allocated(this%gradient)) deallocate (this%gradient)
      if (allocated(this%hessian)) deallocate (this%hessian)
      if (allocated(this%dipole)) deallocate (this%dipole)
      ! Vibrational data
      if (allocated(this%frequencies)) deallocate (this%frequencies)
      if (allocated(this%reduced_masses)) deallocate (this%reduced_masses)
      if (allocated(this%force_constants)) deallocate (this%force_constants)
      if (allocated(this%ir_intensities)) deallocate (this%ir_intensities)
      ! MBE data
      if (allocated(this%polymers)) deallocate (this%polymers)
      if (allocated(this%fragment_energies)) deallocate (this%fragment_energies)
      if (allocated(this%delta_energies)) deallocate (this%delta_energies)
      if (allocated(this%sum_by_level)) deallocate (this%sum_by_level)
      if (allocated(this%fragment_distances)) deallocate (this%fragment_distances)
      ! GMBE PIE data
      if (allocated(this%pie_atom_sets)) deallocate (this%pie_atom_sets)
      if (allocated(this%pie_coefficients)) deallocate (this%pie_coefficients)
      if (allocated(this%pie_energies)) deallocate (this%pie_energies)
      call this%reset()
   end subroutine json_output_data_destroy
Call graph
json_output_data_destroy calls json_output_data_reset
run_calculation calls json_output_data_destroy
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations