map_fragment_to_system_dipole_derivatives – metalquicha
map_fragment_to_system_dipole_derivatives Subroutine
36 statements
Source File
private subroutine map_fragment_to_system_dipole_derivatives(frag_dipole_derivs, monomers, sys_geom, sys_dipole_derivs, bonds)
Uses
mqc_physical_fragment
mqc_config_parser
mqc_error
Map fragment dipole derivatives to system coordinates with hydrogen cap redistribution
Dipole derivatives have shape (3, 3*N) where each column corresponds to the derivative of dipole w.r.t. one Cartesian coordinate of one atom.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: frag_dipole_derivs(:,:)
(3, 3*natoms_frag)
integer, intent(in) :: monomers(:)
type(system_geometry_t), intent(in) :: sys_geom
real(kind=dp), intent(inout) :: sys_dipole_derivs(:,:)
(3, 3*total_atoms)
type(bond_t), intent(in), optional :: bonds(:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(error_t), private :: error
type(physical_fragment_t), private :: fragment
Source Code
   subroutine map_fragment_to_system_dipole_derivatives(frag_dipole_derivs, monomers, sys_geom, sys_dipole_derivs, bonds)
      !! Map fragment dipole derivatives to system coordinates with hydrogen cap redistribution
      !!
      !! Dipole derivatives have shape (3, 3*N) where each column corresponds to
      !! the derivative of dipole w.r.t. one Cartesian coordinate of one atom.
      use mqc_physical_fragment, only: build_fragment_from_indices, redistribute_cap_dipole_derivatives
      use mqc_config_parser, only: bond_t
      use mqc_error, only: error_t
      real(dp), intent(in) :: frag_dipole_derivs(:, :)  !! (3, 3*natoms_frag)
      integer, intent(in) :: monomers(:)
      type(system_geometry_t), intent(in) :: sys_geom
      real(dp), intent(inout) :: sys_dipole_derivs(:, :)  !! (3, 3*total_atoms)
      type(bond_t), intent(in), optional :: bonds(:)
      type(physical_fragment_t) :: fragment
      type(error_t) :: error
      ! Zero out
      sys_dipole_derivs = 0.0_dp
      if (present(bonds)) then
         ! Rebuild fragment to get localglobal mapping and cap information
         call build_fragment_from_indices(sys_geom, monomers, fragment, error, bonds)
         call redistribute_cap_dipole_derivatives(fragment, frag_dipole_derivs, sys_dipole_derivs)
         call fragment%destroy()
      else
         ! Code path for fragments without hydrogen caps
         ! Map fragment dipole derivative columns to system positions (fixed-size monomers only)
         block
            integer :: i_mon, i_atom
            integer :: frag_atom_idx, sys_atom_idx
            integer :: frag_col_start, sys_col_start
            integer :: n_monomers
            n_monomers = size(monomers)
            frag_atom_idx = 0
            ! Map each monomer's atoms
            do i_mon = 1, n_monomers
               do i_atom = 1, sys_geom%atoms_per_monomer
                  frag_atom_idx = frag_atom_idx + 1
                  sys_atom_idx = (monomers(i_mon) - 1)*sys_geom%atoms_per_monomer + i_atom
                  frag_col_start = (frag_atom_idx - 1)*3 + 1
                  sys_col_start = (sys_atom_idx - 1)*3 + 1
                  ! Copy the 3 columns (x, y, z derivatives) for this atom
                  sys_dipole_derivs(:, sys_col_start:sys_col_start + 2) = &
                     frag_dipole_derivs(:, frag_col_start:frag_col_start + 2)
               end do
            end do
         end block
      end if
   end subroutine map_fragment_to_system_dipole_derivatives
Call graph
map_fragment_to_system_dipole_derivatives calls build_fragment_from_indices, fragment_destroy, redistribute_cap_dipole_derivatives
build_fragment_from_indices calls add_hydrogen_caps, calculate_monomer_distance, check_duplicate_atoms, count_hydrogen_caps, error_add_context, error_has_error, fragment_compute_nelec
fragment_destroy calls basis_set_destroy
basis_set_destroy calls atomic_basis_destroy
calculate_monomer_distance calls to_angstrom
check_duplicate_atoms calls error, element_number_to_symbol, error_set, to_char
atomic_basis_destroy calls cgto_destroy
compute_mbe calls map_fragment_to_system_dipole_derivatives, compute_mbe_dipole_derivatives
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives
global_coordinator calls compute_mbe, global_coordinator
serial_fragment_processor calls compute_mbe, serial_fragment_processor
run_fragmented_calculation calls global_coordinator, serial_fragment_processor
run_calculation calls run_fragmented_calculation