mbe_run_serial – metalquicha
mbe_run_serial Subroutine
11 statements
Source File
private subroutine mbe_run_serial(this, json_data)
Uses
mqc_mbe_fragment_distribution_scheme
pic_logger
Run serial MBE calculation
Type Bound
mbe_context_t
Arguments
Type Intent Optional Attributes Name
class(mbe_context_t), intent(inout) :: this
type(json_output_data_t), intent(out), optional :: json_data
Calls
Source Code
   subroutine mbe_run_serial(this, json_data)
      !! Run serial MBE calculation
      use mqc_mbe_fragment_distribution_scheme, only: serial_fragment_processor
      use pic_logger, only: logger => global_logger
      class(mbe_context_t), intent(inout) :: this
      type(json_output_data_t), intent(out), optional :: json_data
      if (.not. this%has_geometry()) then
         call logger%error("mbe_run_serial: sys_geom required but not set")
         return
      end if
      call serial_fragment_processor(this%total_fragments, this%polymers, this%max_level, &
                                     this%sys_geom, this%method_config, this%calc_type, json_data)
   end subroutine mbe_run_serial
Call graph
mbe_run_serial calls error, serial_fragment_processor, mbe_base_has_geometry
serial_fragment_processor calls serial_fragment_processor, error, configuration, get_elapsed_time, info, do_fragment_work, omp_get_max_threads, omp_set_num_threads, build_fragment_from_indices, calc_type_to_string, compute_mbe, energy_total, error_get_full_trace, error_get_message, error_has_error, fragment_destroy, mbe_result_allocate_dipole, mbe_result_allocate_gradient, mbe_result_allocate_hessian, start, to_char, verbose
do_fragment_work calls do_fragment_work, configuration, calc_type_to_string, to_char, error_add_context, calc_energy, calc_gradient, calc_hessian, create_method, energy_reset, error_set, print_fragment_xyz
build_fragment_from_indices calls error_has_error, add_hydrogen_caps, calculate_monomer_distance, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
compute_mbe calls error, configuration, info, energy_total, to_char, abort_comm, cart_disp, fc_mdyne, force_constants, frequencies, get_message, has_error, build_mbe_lookup_table, compute_mbe_delta, compute_mbe_dipole, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian, compute_thermochemistry, compute_vibrational_analysis, fragment_lookup_destroy, map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, print_detailed_breakdown, print_mbe_energy_breakdown, print_mbe_gradient_info, print_vibrational_analysis, reduced_masses, warning
energy_total calls mp2_total
error_get_full_trace calls error_has_error
fragment_destroy calls basis_set_destroy
basis_set_destroy calls atomic_basis_destroy
build_mbe_lookup_table calls get_elapsed_time, error_has_error, start, to_char, error_add_context, debug, fragment_lookup_init, fragment_lookup_insert
calculate_monomer_distance calls to_angstrom
check_duplicate_atoms calls error, to_char, element_number_to_symbol, error_set
compute_mbe_delta calls error, abort_comm, fragment_lookup_find, get_next_combination
compute_mbe_dipole calls error, abort_comm, fragment_lookup_find, get_next_combination
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives, fragment_lookup_find, get_next_combination
compute_mbe_gradient calls error, abort_comm, map_fragment_to_system_gradient, fragment_lookup_find, get_next_combination
compute_mbe_hessian calls map_fragment_to_system_hessian, fragment_lookup_find, get_next_combination
compute_thermochemistry calls compute_electronic_entropy, compute_moments_of_inertia, compute_partition_functions, compute_rotational_constants, compute_rotational_thermo, compute_translational_thermo, compute_vibrational_thermo, compute_zpe
compute_vibrational_analysis calls compute_cartesian_displacements, compute_force_constants, compute_ir_intensities, compute_reduced_masses, compute_vibrational_frequencies
map_fragment_to_system_dipole_derivatives calls build_fragment_from_indices, fragment_destroy, redistribute_cap_dipole_derivatives
map_fragment_to_system_gradient calls error, configuration, build_fragment_from_indices, error_get_full_trace, error_has_error, fragment_destroy, abort_comm, debug, redistribute_cap_gradients
map_fragment_to_system_hessian calls build_fragment_from_indices, fragment_destroy, redistribute_cap_hessian
print_detailed_breakdown calls verbose, warning, header, level_name, get_frag_level_name
print_mbe_energy_breakdown calls info
print_mbe_gradient_info calls info, to_char
print_vibrational_analysis calls info, compute_thermochemistry, warning, element_number_to_symbol, print_thermochemistry