mbe_base_has_geometry – metalquicha
mbe_base_has_geometry Function
4 statements
Source File
private pure function mbe_base_has_geometry(this)
Check if system geometry is available
Type Bound
many_body_expansion_t
Arguments
Type Intent Optional Attributes Name
class(many_body_expansion_t), intent(in) :: this
Return Value logical
Called by
Source Code
   pure logical function mbe_base_has_geometry(this)
      !! Check if system geometry is available
      class(many_body_expansion_t), intent(in) :: this
      mbe_base_has_geometry = allocated(this%sys_geom)
   end function mbe_base_has_geometry
Call graph
gmbe_run_distributed calls mbe_base_has_geometry
gmbe_run_serial calls mbe_base_has_geometry
mbe_run_distributed calls mbe_base_has_geometry
mbe_run_serial calls mbe_base_has_geometry