mbe_result_allocate_gradient – metalquicha
mbe_result_allocate_gradient Subroutine
7 statements
Source File
private subroutine mbe_result_allocate_gradient(this, total_atoms)
Allocate gradient array for total_atoms
Type Bound
mbe_result_t
Arguments
Type Intent Optional Attributes Name
class(mbe_result_t), intent(inout) :: this
integer, intent(in) :: total_atoms
Called by
Source Code
   subroutine mbe_result_allocate_gradient(this, total_atoms)
      !! Allocate gradient array for total_atoms
      class(mbe_result_t), intent(inout) :: this
      integer, intent(in) :: total_atoms
      if (allocated(this%gradient)) deallocate (this%gradient)
      allocate (this%gradient(3, total_atoms))
      this%gradient = 0.0_dp
   end subroutine mbe_result_allocate_gradient
Call graph
serial_fragment_processor calls mbe_result_allocate_gradient, serial_fragment_processor
mbe_run_serial calls serial_fragment_processor