method_type_to_string – metalquicha
method_type_to_string Function
30 statements
Source File
public pure function method_type_to_string(method_type) result(method_str)
Convert method type integer constant to string
Provides human-readable string representation of method type.
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: method_type
Input integer constant
Return Value character(len=:), allocatable
Output string representation
Called by
Source Code
   pure function method_type_to_string(method_type) result(method_str)
      !! Convert method type integer constant to string
      !!
      !! Provides human-readable string representation of method type.
      integer(int32), intent(in) :: method_type         !! Input integer constant
      character(len=:), allocatable :: method_str       !! Output string representation
      select case (method_type)
         ! Semi-empirical
      case (METHOD_TYPE_GFN1)
         method_str = "gfn1"
      case (METHOD_TYPE_GFN2)
         method_str = "gfn2"
         ! SCF methods
      case (METHOD_TYPE_HF)
         method_str = "hf"
      case (METHOD_TYPE_DFT)
         method_str = "dft"
         ! Multi-reference
      case (METHOD_TYPE_MCSCF)
         method_str = "mcscf"
         ! Perturbation theory
      case (METHOD_TYPE_MP2)
         method_str = "mp2"
      case (METHOD_TYPE_MP2_F12)
         method_str = "mp2-f12"
         ! Coupled cluster
      case (METHOD_TYPE_CCSD)
         method_str = "ccsd"
      case (METHOD_TYPE_CCSD_T)
         method_str = "ccsd(t)"
      case (METHOD_TYPE_CCSD_F12)
         method_str = "ccsd-f12"
      case (METHOD_TYPE_CCSD_T_F12)
         method_str = "ccsd(t)-f12"
      case default
         method_str = "unknown"
      end select
   end function method_type_to_string
Call graph
configure_xtb calls method_type_to_string
factory_create calls configure_xtb
create_method calls factory_create
do_fragment_work calls create_method, do_fragment_work
hessian_coordinator calls create_method, hessian_coordinator
hessian_worker calls create_method, hessian_worker