molecule_to_system_geometry – metalquicha
molecule_to_system_geometry Subroutine
65 statements
Source File
private subroutine molecule_to_system_geometry(mol, sys_geom, use_angstrom, allow_overlapping, error)
Uses
mqc_config_parser
Convert a molecule_t to system_geometry_t Handles both unfragmented (nfrag=0) and fragmented molecules
Arguments
Type Intent Optional Attributes Name
type(molecule_t), intent(in) :: mol
type(system_geometry_t), intent(out) :: sys_geom
logical, intent(in) :: use_angstrom
logical, intent(in) :: allow_overlapping
type(error_t), intent(out) :: error
Calls
Called by
Variables
Type Visibility Attributes Name Initial
logical, private :: all_same_size
integer, private :: atoms_in_first_frag
integer, private :: i
integer, private :: j
integer, private :: max_frag_size
Source Code
   subroutine molecule_to_system_geometry(mol, sys_geom, use_angstrom, allow_overlapping, error)
      !! Convert a molecule_t to system_geometry_t
      !! Handles both unfragmented (nfrag=0) and fragmented molecules
      use mqc_config_parser, only: molecule_t
      type(molecule_t), intent(in) :: mol
      type(system_geometry_t), intent(out) :: sys_geom
      logical, intent(in) :: use_angstrom
      type(error_t), intent(out) :: error
      logical, intent(in) :: allow_overlapping
      integer :: i, j, atoms_in_first_frag, max_frag_size
      logical :: all_same_size
      ! Check if geometry is loaded
      if (mol%geometry%natoms == 0) then
         call error%set(ERROR_VALIDATION, "No geometry loaded in molecule")
         return
      end if
      if (mol%nfrag == 0) then
         ! Unfragmented molecule
         call geometry_to_system_unfragmented(mol%geometry, sys_geom, use_angstrom)
         sys_geom%charge = mol%charge
         sys_geom%multiplicity = mol%multiplicity
      else
         ! Fragmented molecule
         sys_geom%n_monomers = mol%nfrag
         sys_geom%total_atoms = mol%geometry%natoms
         sys_geom%charge = mol%charge
         sys_geom%multiplicity = mol%multiplicity
         ! Allocate fragment info arrays
         allocate (sys_geom%fragment_sizes(mol%nfrag))
         allocate (sys_geom%fragment_charges(mol%nfrag))
         allocate (sys_geom%fragment_multiplicities(mol%nfrag))
         ! Get fragment sizes
         max_frag_size = 0
         atoms_in_first_frag = size(mol%fragments(1)%indices)
         all_same_size = .true.
         do i = 1, mol%nfrag
            sys_geom%fragment_sizes(i) = size(mol%fragments(i)%indices)
            sys_geom%fragment_charges(i) = mol%fragments(i)%charge
            sys_geom%fragment_multiplicities(i) = mol%fragments(i)%multiplicity
            max_frag_size = max(max_frag_size, sys_geom%fragment_sizes(i))
            if (sys_geom%fragment_sizes(i) /= atoms_in_first_frag) then
               all_same_size = .false.
            end if
         end do
         ! Allocate fragment_atoms array
         allocate (sys_geom%fragment_atoms(max_frag_size, mol%nfrag))
         sys_geom%fragment_atoms = -1  ! Initialize with invalid index
         ! Store fragment atom indices (0-indexed from input file)
         do i = 1, mol%nfrag
            do j = 1, sys_geom%fragment_sizes(i)
               sys_geom%fragment_atoms(j, i) = mol%fragments(i)%indices(j)
            end do
         end do
         ! Check for overlapping fragments if not allowed
         if (.not. allow_overlapping) then
            call check_fragment_overlap(mol%fragments, mol%nfrag, error)
            if (error%has_error()) return
         end if
         ! Set atoms_per_monomer: use common size if identical, else 0
         if (all_same_size) then
            sys_geom%atoms_per_monomer = atoms_in_first_frag
         else
            sys_geom%atoms_per_monomer = 0  ! Signal variable-sized fragments
         end if
         allocate (sys_geom%element_numbers(sys_geom%total_atoms))
         allocate (sys_geom%coordinates(3, sys_geom%total_atoms))
         ! Convert element symbols to atomic numbers
         do i = 1, sys_geom%total_atoms
            sys_geom%element_numbers(i) = element_symbol_to_number(mol%geometry%elements(i))
         end do
         ! Store coordinates (convert to Bohr if needed)
         if (use_angstrom) then
            sys_geom%coordinates = to_bohr(mol%geometry%coords)
         else
            sys_geom%coordinates = mol%geometry%coords
         end if
      end if
   end subroutine molecule_to_system_geometry
Call graph
molecule_to_system_geometry calls check_fragment_overlap, element_symbol_to_number, error_has_error, error_set, geometry_to_system_unfragmented, to_bohr
check_fragment_overlap calls error_set, to_char
element_symbol_to_number calls to_lower, to_upper
geometry_to_system_unfragmented calls element_symbol_to_number, to_bohr
config_to_system_geometry calls molecule_to_system_geometry
run_multi_molecule_calculations calls config_to_system_geometry
main calls config_to_system_geometry, run_multi_molecule_calculations