mp2_reset – metalquicha
mp2_reset Subroutine
5 statements
Source File
private subroutine mp2_reset(this)
Reset both MP2 components to zero
Type Bound
mp2_energy_t
Arguments
Type Intent Optional Attributes Name
class(mp2_energy_t), intent(inout) :: this
Called by
Source Code
   subroutine mp2_reset(this)
      !! Reset both MP2 components to zero
      class(mp2_energy_t), intent(inout) :: this
      this%ss = 0.0_dp
      this%os = 0.0_dp
   end subroutine mp2_reset
Call graph
energy_reset calls mp2_reset
do_fragment_work calls energy_reset, xtb_calc_hessian
result_reset calls energy_reset
node_worker calls do_fragment_work
result_destroy calls result_reset
serial_fragment_processor calls do_fragment_work
serial_gmbe_pie_processor calls do_fragment_work
unfragmented_calculation calls do_fragment_work, result_destroy
compute_energy_and_forces calls result_destroy
hessian_coordinator calls result_destroy
hessian_worker calls result_destroy
run_fragmented_calculation calls node_worker, serial_fragment_processor, serial_gmbe_pie_processor
run_unfragmented_calculation calls unfragmented_calculation
xtb_calc_hessian calls result_destroy
distributed_unfragmented_hessian calls hessian_coordinator, hessian_worker
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation