next_prime_internal – metalquicha
next_prime_internal Function
18 statements
Source File
private pure function next_prime_internal(n) result(p)
Find next prime number >= n (simple implementation)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
Return Value integer
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
logical, private :: is_prime
Source Code
   pure function next_prime_internal(n) result(p)
      !! Find next prime number >= n (simple implementation)
      integer, intent(in) :: n
      integer :: p, i
      logical :: is_prime
      p = max(n, 2)
      if (modulo(p, 2) == 0) p = p + 1
      do
         is_prime = .true.
         do i = 3, int(sqrt(real(p))) + 1, 2
            if (modulo(p, i) == 0) then
               is_prime = .false.
               exit
            end if
         end do
         if (is_prime) return
         p = p + 2
      end do
   end function next_prime_internal
Call graph
fragment_lookup_init calls next_prime_internal
compute_mbe_energy calls fragment_lookup_init
compute_mbe_energy_gradient calls fragment_lookup_init
compute_mbe_energy_gradient_hessian calls fragment_lookup_init
global_coordinator calls compute_mbe_energy, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian
serial_fragment_processor calls compute_mbe_energy, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian
run_fragmented_calculation calls global_coordinator, serial_fragment_processor
run_calculation calls run_fragmented_calculation