node_worker – metalquicha
node_worker Module Subroutine
58 statements
Source File
module subroutine node_worker(resources, sys_geom, method, calc_type, bonds) Interface →
Uses
mqc_error
Node worker for processing fragments assigned by node coordinator
Arguments
Type Intent Optional Attributes Name
type(resources_t), intent(in) :: resources
type(system_geometry_t), intent(in), optional :: sys_geom
integer(kind=int32), intent(in) :: method
integer(kind=int32), intent(in) :: calc_type
type(bond_t), intent(in), optional :: bonds(:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: dummy_msg
type(error_t), private :: error
integer(kind=int64), private :: fragment_idx
integer(kind=int32), private, allocatable :: fragment_indices(:)
integer(kind=int32), private :: fragment_size
integer(kind=int32), private :: fragment_type
0 = monomer (indices), 1 = intersection (atom list)
type(physical_fragment_t), private :: phys_frag
type(request_t), private :: req
type(calculation_result_t), private :: result
type(MPI_Status), private :: status
Source Code
   module subroutine node_worker(resources, sys_geom, method, calc_type, bonds)
      !! Node worker for processing fragments assigned by node coordinator
      use mqc_error, only: error_t
      type(resources_t), intent(in) :: resources
      type(system_geometry_t), intent(in), optional :: sys_geom
      integer(int32), intent(in) :: method
      integer(int32), intent(in) :: calc_type
      type(bond_t), intent(in), optional :: bonds(:)
      integer(int64) :: fragment_idx
      integer(int32) :: fragment_size, dummy_msg
      integer(int32) :: fragment_type  !! 0 = monomer (indices), 1 = intersection (atom list)
      integer(int32), allocatable :: fragment_indices(:)
      type(calculation_result_t) :: result
      type(MPI_Status) :: status
      type(physical_fragment_t) :: phys_frag
      type(error_t) :: error
      ! MPI request handles for non-blocking operations
      type(request_t) :: req
      dummy_msg = 0
      do
         call isend(resources%mpi_comms%node_comm, dummy_msg, 0, TAG_WORKER_REQUEST, req)
         call wait(req)
         call irecv(resources%mpi_comms%node_comm, fragment_idx, 0, MPI_ANY_TAG, req)
         call wait(req, status)
         select case (status%MPI_TAG)
         case (TAG_WORKER_FRAGMENT)
            ! Receive fragment type (0 = monomer indices, 1 = intersection atom list)
            call irecv(resources%mpi_comms%node_comm, fragment_type, 0, TAG_WORKER_FRAGMENT, req)
            call wait(req)
            call irecv(resources%mpi_comms%node_comm, fragment_size, 0, TAG_WORKER_FRAGMENT, req)
            call wait(req)
            ! Note: must use blocking recv for allocatable arrays since size is unknown
            allocate (fragment_indices(fragment_size))
            call recv(resources%mpi_comms%node_comm, fragment_indices, 0, TAG_WORKER_FRAGMENT, status)
            ! Build physical fragment based on type
            if (present(sys_geom)) then
               if (fragment_type == 0) then
                  ! Monomer: fragment_indices are monomer indices
                  call build_fragment_from_indices(sys_geom, fragment_indices, phys_frag, error, bonds)
               else
                  ! Intersection: fragment_indices are atom indices
                  call build_fragment_from_atom_list(sys_geom, fragment_indices, fragment_size, phys_frag, error, bonds)
               end if
               if (error%has_error()) then
                  call logger%error(error%get_full_trace())
                  call abort_comm(resources%mpi_comms%world_comm, 1)
               end if
               ! Process the chemistry fragment with physical geometry
               call do_fragment_work(fragment_idx, result, method, phys_frag, calc_type, resources%mpi_comms%world_comm)
               call phys_frag%destroy()
            else
               ! Process without physical geometry (old behavior)
       call do_fragment_work(fragment_idx, result, method, calc_type=calc_type, world_comm=resources%mpi_comms%world_comm)
            end if
            ! Send result back to coordinator
            call result_isend(result, resources%mpi_comms%node_comm, 0, TAG_WORKER_SCALAR_RESULT, req)
            call wait(req)
            ! Clean up result
            call result%destroy()
            deallocate (fragment_indices)
         case (TAG_WORKER_FINISH)
            exit
         case default
            ! Unexpected MPI tag - this should not happen in normal operation
            call logger%error("Worker received unexpected MPI tag: "//to_char(status%MPI_TAG))
            call logger%error("Expected TAG_WORKER_FRAGMENT or TAG_WORKER_FINISH")
            call abort_comm(resources%mpi_comms%world_comm, 1)
         end select
      end do
   end subroutine node_worker
Call graph
node_worker calls abort_comm, error, do_fragment_work, irecv, isend, build_fragment_from_atom_list, build_fragment_from_indices, error_get_full_trace, error_has_error, fragment_destroy, result_isend, recv, to_char, node_worker
do_fragment_work calls do_fragment_work, to_char, error_add_context, configuration, calc_type_to_string, energy_reset, error_set, method_type_to_string, print_fragment_xyz, xtb_calc_energy, xtb_calc_gradient, xtb_calc_hessian
build_fragment_from_atom_list calls error_has_error, add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
build_fragment_from_indices calls error_has_error, add_hydrogen_caps, calculate_monomer_distance, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
error_get_full_trace calls error_has_error
fragment_destroy calls basis_set_destroy
result_isend calls isend, send
basis_set_destroy calls atomic_basis_destroy
calculate_monomer_distance calls to_angstrom
check_duplicate_atoms calls error, to_char, element_number_to_symbol, error_set
atomic_basis_destroy calls cgto_destroy
energy_reset calls mp2_reset
print_fragment_xyz calls to_char, element_number_to_symbol, to_angstrom, info
xtb_calc_energy calls error_set, dpat, new, new_gfn1_calculator, new_gfn2_calculator, new_wavefunction, add_solvation_to_calc, energy_total, qat, xtb_singlepoint
xtb_calc_gradient calls error_set, dpat, new, new_gfn1_calculator, new_gfn2_calculator, new_wavefunction, add_solvation_to_calc, energy_total, qat, xtb_singlepoint
xtb_calc_hessian calls to_char, error_set, xtb_calc_gradient, info, finite_diff_dipole_derivatives, finite_diff_hessian_from_gradients, generate_perturbed_geometries, result_destroy
add_solvation_to_calc calls new_solvation, new_solvation_cds, new_solvation_shift, get_solvent_dielectric, push_back
energy_total calls mp2_total
generate_perturbed_geometries calls copy_and_displace_geometry
result_destroy calls result_reset
run_fragmented_calculation calls node_worker
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations