parse_connectivity_section – metalquicha
parse_connectivity_section Subroutine
6 statements
Source File
private subroutine parse_connectivity_section(unit, config, error)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
type(mqc_config_t), intent(inout) :: config
type(error_t), intent(out) :: error
Calls
Called by
Source Code
   subroutine parse_connectivity_section(unit, config, error)
      integer, intent(in) :: unit
      type(mqc_config_t), intent(inout) :: config
      type(error_t), intent(out) :: error
      call parse_connectivity_generic(unit, config%nbonds, config%nbroken, config%bonds, error)
   end subroutine parse_connectivity_section
Call graph
parse_connectivity_section calls parse_connectivity_generic
parse_connectivity_generic calls error_set, skip_to_end, strip_comment
skip_to_end calls error_set, strip_comment
read_mqc_file calls parse_connectivity_section
main calls read_mqc_file