parse_fragments_section – metalquicha
parse_fragments_section Subroutine
6 statements
Source File
private subroutine parse_fragments_section(unit, config, error)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
type(mqc_config_t), intent(inout) :: config
type(error_t), intent(out) :: error
Calls
Called by
Source Code
   subroutine parse_fragments_section(unit, config, error)
      integer, intent(in) :: unit
      type(mqc_config_t), intent(inout) :: config
      type(error_t), intent(out) :: error
      call parse_fragments_generic(unit, config%nfrag, config%fragments, error)
   end subroutine parse_fragments_section
Call graph
parse_fragments_section calls parse_fragments_generic
parse_fragments_generic calls error_add_context, error_has_error, error_set, parse_fragment, skip_to_end, strip_comment
parse_fragment calls error_add_context, error_has_error, error_set, strip_comment, parse_indices_line
skip_to_end calls error_set, strip_comment
parse_indices_line calls error_set
read_mqc_file calls parse_fragments_section
main calls read_mqc_file