parse_structure_generic – metalquicha
parse_structure_generic Module Subroutine
31 statements
Source File
module subroutine parse_structure_generic(unit, charge, multiplicity, error) Interface →
Generic parser for %structure section (works for both config and molecule)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
integer, intent(inout) :: charge
integer, intent(inout) :: multiplicity
type(error_t), intent(out) :: error
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: eq_pos
integer, private :: io_stat
character(len=MAX_LINE_LEN), private :: key
character(len=MAX_LINE_LEN), private :: line
character(len=MAX_LINE_LEN), private :: value
Source Code
   module subroutine parse_structure_generic(unit, charge, multiplicity, error)
      !! Generic parser for %structure section (works for both config and molecule)
      integer, intent(in) :: unit
      integer, intent(inout) :: charge, multiplicity
      type(error_t), intent(out) :: error
      character(len=MAX_LINE_LEN) :: line, key, value
      integer :: io_stat, eq_pos
      do
         read (unit, '(A)', iostat=io_stat) line
         if (io_stat /= 0) then
            call error%set(ERROR_IO, "Unexpected end of file in %structure section")
            return
         end if
         line = adjustl(line)
         if (len_trim(line) == 0) cycle
         if (line(1:1) == '#' .or. line(1:1) == '!') cycle
         if (trim(strip_comment(line)) == 'end') exit
         eq_pos = index(line, '=')
         if (eq_pos == 0) cycle
         key = adjustl(line(1:eq_pos - 1))
         value = adjustl(line(eq_pos + 1:))
         select case (trim(key))
         case ('charge')
            read (value, *, iostat=io_stat) charge
         case ('multiplicity')
            read (value, *, iostat=io_stat) multiplicity
         case default
            call error%set(ERROR_PARSE, "Unknown key in %structure section: "//trim(key))
            return
         end select
      end do
   end subroutine parse_structure_generic
Call graph
parse_structure_generic calls error_set, strip_comment, parse_structure_generic
parse_molecule_structure calls parse_structure_generic
parse_structure_section calls parse_structure_generic, parse_structure_section
parse_single_molecule calls parse_molecule_structure
parse_molecules_section calls parse_single_molecule, parse_molecules_section
read_mqc_file calls parse_structure_section
main calls read_mqc_file