parse_geometry_section – metalquicha
parse_geometry_section Module Subroutine
6 statements
Source File
module subroutine parse_geometry_section(unit, config, error) Interface →
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
type(mqc_config_t), intent(inout) :: config
type(error_t), intent(out) :: error
Calls
Called by
Source Code
   module subroutine parse_geometry_section(unit, config, error)
      integer, intent(in) :: unit
      type(mqc_config_t), intent(inout) :: config
      type(error_t), intent(out) :: error
      call parse_geometry_generic(unit, config%geometry, error)
   end subroutine parse_geometry_section
Call graph
parse_geometry_section calls parse_geometry_generic, parse_geometry_section
parse_geometry_generic calls parse_geometry_generic, error_set, strip_comment
read_mqc_file calls parse_geometry_section
main calls read_mqc_file