parse_shell_header – metalquicha
parse_shell_header Subroutine
10 statements
Source File
private pure subroutine parse_shell_header(line, ang_mom, nfunc, stat)
Parse shell header line (e.g., “S 2” or “L 3”)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: line
character(len=1), intent(out) :: ang_mom
integer, intent(out) :: nfunc
integer, intent(out) :: stat
Called by
Variables
Type Visibility Attributes Name Initial
character(len=256), private :: line_trim
Source Code
   pure subroutine parse_shell_header(line, ang_mom, nfunc, stat)
      !! Parse shell header line (e.g., "S 2" or "L 3")
      character(len=*), intent(in) :: line
      character(len=1), intent(out) :: ang_mom
      integer, intent(out) :: nfunc
      integer, intent(out) :: stat
      character(len=256) :: line_trim
      line_trim = adjustl(line)
      ang_mom = line_trim(1:1)
      ! Read the number of functions
      read (line_trim(2:), *, iostat=stat) nfunc
   end subroutine parse_shell_header
Call graph
fill_element_basis calls parse_shell_header
parse_element_basis calls fill_element_basis
build_molecular_basis calls parse_element_basis