parse_element_basis – metalquicha
parse_element_basis Subroutine
19 statements
Source File
public pure subroutine parse_element_basis(basis_string, element_name, atom_basis, stat, errmsg)
Parse basis set for a specific element from a GAMESS formatted basis string
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: basis_string
character(len=*), intent(in) :: element_name
type(atomic_basis_type), intent(out) :: atom_basis
integer, intent(out) :: stat
character(len=:), intent(out), allocatable :: errmsg
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: nshells
Source Code
   pure subroutine parse_element_basis(basis_string, element_name, atom_basis, stat, errmsg)
      !! Parse basis set for a specific element from a GAMESS formatted basis string
      character(len=*), intent(in) :: basis_string
      character(len=*), intent(in) :: element_name
      type(atomic_basis_type), intent(out) :: atom_basis
      integer, intent(out) :: stat
      character(len=:), allocatable, intent(out) :: errmsg
      integer :: nshells
      stat = 0
      ! Pass 1: Find the element and count its shells
      call count_shells_for_element(basis_string, element_name, nshells, stat, errmsg)
      if (stat /= 0) return
      if (nshells == 0) then
         stat = 1
         errmsg = "Element "//trim(element_name)//" not found in basis file"
         return
      end if
      ! ! Allocate shells
      atom_basis%element = trim(element_name)
      call atom_basis%allocate_shells(nshells)
      ! ! Pass 2: Parse and fill shell data
      call fill_element_basis(basis_string, element_name, atom_basis, stat, errmsg)
   end subroutine parse_element_basis
Call graph
parse_element_basis calls allocate_basis_shells, count_shells_for_element, fill_element_basis
count_shells_for_element calls classify_line, get_next_line, strings_equal
fill_element_basis calls ang_mom_char_to_int, cgto_allocate_arrays, classify_line, get_next_line, parse_function_line, parse_shell_header, strings_equal
classify_line calls is_blank_or_control, is_function_line, is_shell_header
build_molecular_basis calls parse_element_basis