parse_single_molecule – metalquicha
parse_single_molecule Subroutine
45 statements
Source File
subroutine parse_single_molecule(unit, mol, error)
Parse a single %molecule block with its sections
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
type(molecule_t), intent(inout) :: mol
type(error_t), intent(out) :: error
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: eq_pos
integer, private :: io_stat
character(len=MAX_LINE_LEN), private :: key
character(len=MAX_LINE_LEN), private :: line
character(len=MAX_LINE_LEN), private :: value
Source Code
   subroutine parse_single_molecule(unit, mol, error)
      !! Parse a single %molecule block with its sections
      integer, intent(in) :: unit
      type(molecule_t), intent(inout) :: mol
      type(error_t), intent(out) :: error
      character(len=MAX_LINE_LEN) :: line, key, value
      integer :: io_stat, eq_pos
      do
         read (unit, '(A)', iostat=io_stat) line
         if (io_stat /= 0) then
            call error%set(ERROR_IO, "Unexpected end of file in %molecule")
            return
         end if
         line = adjustl(line)
         if (len_trim(line) == 0) cycle
         if (line(1:1) == '#' .or. line(1:1) == '!') cycle
         if (trim(strip_comment(line)) == 'end') exit
         ! Check for key=value pairs (like name)
         eq_pos = index(line, '=')
         if (eq_pos > 0) then
            key = adjustl(line(1:eq_pos - 1))
            value = adjustl(line(eq_pos + 1:))
            if (trim(key) == 'name') then
               mol%name = trim(value)
               cycle
            end if
         end if
         ! Check for subsections
         if (line(1:1) == '%') then
            select case (trim(line))
            case ('%structure')
               call parse_molecule_structure(unit, mol, error)
            case ('%geometry')
               call parse_molecule_geometry(unit, mol, error)
            case ('%fragments')
               call parse_molecule_fragments(unit, mol, error)
            case ('%connectivity')
               call parse_molecule_connectivity(unit, mol, error)
            case default
               ! Skip unknown subsections
               call skip_to_end(unit, error)
            end select
            if (error%has_error()) then
               call error%add_context("mqc_config_parser:parse_single_molecule")
               return
            end if
         end if
      end do
   end subroutine parse_single_molecule
Call graph
parse_single_molecule calls error_add_context, error_has_error, error_set, parse_molecule_connectivity, parse_molecule_fragments, parse_molecule_geometry, parse_molecule_structure, skip_to_end, strip_comment
parse_molecule_connectivity calls parse_connectivity_generic
parse_molecule_fragments calls parse_fragments_generic
parse_molecule_geometry calls parse_geometry_generic
parse_molecule_structure calls parse_structure_generic
skip_to_end calls error_set, strip_comment
parse_connectivity_generic calls parse_connectivity_generic, error_set, skip_to_end, strip_comment
parse_fragments_generic calls parse_fragments_generic, error_add_context, error_has_error, error_set, skip_to_end, strip_comment, parse_fragment
parse_geometry_generic calls parse_geometry_generic, error_set, strip_comment
parse_structure_generic calls parse_structure_generic, error_set, strip_comment
parse_fragment calls error_add_context, error_has_error, error_set, strip_comment, parse_indices_line
parse_molecules_section calls parse_single_molecule, parse_molecules_section
read_mqc_file calls parse_molecules_section
main calls read_mqc_file