parse_fragment – metalquicha
parse_fragment Subroutine
53 statements
Source File
private subroutine parse_fragment(unit, fragment, error)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
type(input_fragment_t), intent(inout) :: fragment
type(error_t), intent(out) :: error
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: eq_pos
logical, private :: in_indices
integer, private :: io_stat
character(len=MAX_LINE_LEN), private :: key
character(len=MAX_LINE_LEN), private :: line
character(len=MAX_LINE_LEN), private :: value
Source Code
   subroutine parse_fragment(unit, fragment, error)
      integer, intent(in) :: unit
      type(input_fragment_t), intent(inout) :: fragment
      type(error_t), intent(out) :: error
      character(len=MAX_LINE_LEN) :: line, key, value
      integer :: io_stat, eq_pos
      logical :: in_indices
      in_indices = .false.
      do
         read (unit, '(A)', iostat=io_stat) line
         if (io_stat /= 0) then
            call error%set(ERROR_IO, "Unexpected end of file in %fragment")
            return
         end if
         line = adjustl(line)
         if (len_trim(line) == 0) cycle
         if (line(1:1) == '#' .or. line(1:1) == '!') cycle
         if (trim(strip_comment(line)) == 'end') then
            if (in_indices) then
               in_indices = .false.
               cycle
            else
               exit
            end if
         end if
         if (trim(line) == '%indices') then
            in_indices = .true.
            cycle
         end if
         if (in_indices) then
            ! Read indices
            call parse_indices_line(line, fragment, error)
            if (error%has_error()) then
               call error%add_context("mqc_config_parser:parse_single_fragment_section")
               return
            end if
         else
            eq_pos = index(line, '=')
            if (eq_pos > 0) then
               key = adjustl(line(1:eq_pos - 1))
               value = adjustl(line(eq_pos + 1:))
               select case (trim(key))
               case ('charge')
                  read (value, *, iostat=io_stat) fragment%charge
               case ('multiplicity')
                  read (value, *, iostat=io_stat) fragment%multiplicity
               case default
                  call error%set(ERROR_PARSE, "Unknown key in fragment properties: "//trim(key))
                  return
               end select
            end if
         end if
      end do
   end subroutine parse_fragment
Call graph
parse_fragment calls error_add_context, error_has_error, error_set, parse_indices_line, strip_comment
parse_indices_line calls error_set
parse_fragments_generic calls parse_fragment
parse_fragments_section calls parse_fragments_generic
parse_molecule_fragments calls parse_fragments_generic
parse_single_molecule calls parse_molecule_fragments
read_mqc_file calls parse_fragments_section, parse_molecules_section
parse_molecules_section calls parse_single_molecule
main calls read_mqc_file