parse_molecule_fragments – metalquicha
parse_molecule_fragments Subroutine
6 statements
Source File
subroutine parse_molecule_fragments(unit, mol, error)
Parse %fragments section for a molecule
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
type(molecule_t), intent(inout) :: mol
type(error_t), intent(out) :: error
Calls
Called by
Source Code
   subroutine parse_molecule_fragments(unit, mol, error)
      !! Parse %fragments section for a molecule
      integer, intent(in) :: unit
      type(molecule_t), intent(inout) :: mol
      type(error_t), intent(out) :: error
      call parse_fragments_generic(unit, mol%nfrag, mol%fragments, error)
   end subroutine parse_molecule_fragments
Call graph
parse_molecule_fragments calls parse_fragments_generic
parse_fragments_generic calls parse_fragments_generic, error_add_context, error_has_error, error_set, parse_fragment, skip_to_end, strip_comment
parse_fragment calls error_add_context, error_has_error, error_set, strip_comment, parse_indices_line
skip_to_end calls error_set, strip_comment
parse_indices_line calls error_set
parse_single_molecule calls parse_molecule_fragments
parse_molecules_section calls parse_single_molecule, parse_molecules_section
read_mqc_file calls parse_molecules_section
main calls read_mqc_file