parse_molecule_connectivity – metalquicha
parse_molecule_connectivity Subroutine
6 statements
Source File
private subroutine parse_molecule_connectivity(unit, mol, error)
Parse %connectivity section for a molecule
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
type(molecule_t), intent(inout) :: mol
type(error_t), intent(out) :: error
Calls
Called by
Source Code
   subroutine parse_molecule_connectivity(unit, mol, error)
      !! Parse %connectivity section for a molecule
      integer, intent(in) :: unit
      type(molecule_t), intent(inout) :: mol
      type(error_t), intent(out) :: error
      call parse_connectivity_generic(unit, mol%nbonds, mol%nbroken, mol%bonds, error)
   end subroutine parse_molecule_connectivity
Call graph
parse_molecule_connectivity calls parse_connectivity_generic
parse_connectivity_generic calls error_set, skip_to_end, strip_comment
skip_to_end calls error_set, strip_comment
parse_single_molecule calls parse_molecule_connectivity
parse_molecules_section calls parse_single_molecule
read_mqc_file calls parse_molecules_section
main calls read_mqc_file