parse_molecule_structure – metalquicha
parse_molecule_structure Subroutine
6 statements
Source File
private subroutine parse_molecule_structure(unit, mol, error)
Parse %structure section for a molecule
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
type(molecule_t), intent(inout) :: mol
type(error_t), intent(out) :: error
Calls
Called by
Source Code
   subroutine parse_molecule_structure(unit, mol, error)
      !! Parse %structure section for a molecule
      integer, intent(in) :: unit
      type(molecule_t), intent(inout) :: mol
      type(error_t), intent(out) :: error
      call parse_structure_generic(unit, mol%charge, mol%multiplicity, error)
   end subroutine parse_molecule_structure
Call graph
parse_molecule_structure calls parse_structure_generic
parse_structure_generic calls error_set, strip_comment
parse_single_molecule calls parse_molecule_structure
parse_molecules_section calls parse_single_molecule
read_mqc_file calls parse_molecules_section
main calls read_mqc_file