print_vibrational_json – metalquicha
print_vibrational_json Subroutine
25 statements
Source File
public subroutine print_vibrational_json(result, frequencies, reduced_masses, force_constants, thermo, ir_intensities)
Write vibrational analysis and thermochemistry results to JSON file Wrapper that extracts values from calculation_result_t and calls the implementation
Arguments
Type Intent Optional Attributes Name
type(calculation_result_t), intent(in) :: result
real(kind=dp), intent(in) :: frequencies(:)
real(kind=dp), intent(in) :: reduced_masses(:)
real(kind=dp), intent(in) :: force_constants(:)
type(thermochemistry_result_t), intent(in) :: thermo
real(kind=dp), intent(in), optional :: ir_intensities(:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=dp), private :: energy_val
real(kind=dp), private :: grad_norm
real(kind=dp), private :: hess_norm
Source Code
   subroutine print_vibrational_json(result, frequencies, reduced_masses, force_constants, &
                                     thermo, ir_intensities)
      !! Write vibrational analysis and thermochemistry results to JSON file
      !! Wrapper that extracts values from calculation_result_t and calls the implementation
      type(calculation_result_t), intent(in) :: result
      real(dp), intent(in) :: frequencies(:)
      real(dp), intent(in) :: reduced_masses(:)
      real(dp), intent(in) :: force_constants(:)
      type(thermochemistry_result_t), intent(in) :: thermo
      real(dp), intent(in), optional :: ir_intensities(:)
      real(dp) :: energy_val, grad_norm, hess_norm
      ! Extract energy
      if (result%has_energy) then
         energy_val = result%energy%total()
      else
         energy_val = 0.0_dp
      end if
      ! Compute norms if available
      if (result%has_gradient) then
         grad_norm = sqrt(sum(result%gradient**2))
      end if
      if (result%has_hessian) then
         hess_norm = sqrt(sum(result%hessian**2))
      end if
      ! Call implementation with extracted values
      if (present(ir_intensities)) then
         call write_vibrational_json_impl(energy_val, result%has_energy, &
                                          result%dipole, result%has_dipole, &
                                          grad_norm, result%has_gradient, &
                                          hess_norm, result%has_hessian, &
                                          frequencies, reduced_masses, force_constants, &
                                          thermo, ir_intensities)
      else
         call write_vibrational_json_impl(energy_val, result%has_energy, &
                                          result%dipole, result%has_dipole, &
                                          grad_norm, result%has_gradient, &
                                          hess_norm, result%has_hessian, &
                                          frequencies, reduced_masses, force_constants, &
                                          thermo)
      end if
   end subroutine print_vibrational_json
Call graph
print_vibrational_json calls energy_total, write_vibrational_json_impl
energy_total calls mp2_total
write_vibrational_json_impl calls add, create_object, destroy, error, info, initialize, get_basename, get_output_json_filename
hessian_coordinator calls print_vibrational_json, hessian_coordinator
unfragmented_calculation calls print_vibrational_json, unfragmented_calculation
distributed_unfragmented_hessian calls hessian_coordinator, distributed_unfragmented_hessian
run_unfragmented_calculation calls unfragmented_calculation, distributed_unfragmented_hessian
run_calculation calls run_unfragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation