print_unfragmented_json – metalquicha
print_unfragmented_json Subroutine
35 statements
Source File
public subroutine print_unfragmented_json(result)
Write unfragmented calculation results to output JSON file Uses json-fortran for clean, maintainable JSON output
Arguments
Type Intent Optional Attributes Name
type(calculation_result_t), intent(in) :: result
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=256), private :: basename
type(json_value), private, pointer :: dipole_obj
integer, private :: io_stat
integer, private :: iunit
type(json_core), private :: json
type(json_value), private, pointer :: main_obj
character(len=256), private :: output_file
type(json_value), private, pointer :: root
Source Code
   subroutine print_unfragmented_json(result)
      !! Write unfragmented calculation results to output JSON file
      !! Uses json-fortran for clean, maintainable JSON output
      type(calculation_result_t), intent(in) :: result
      type(json_core) :: json
      type(json_value), pointer :: root, main_obj, dipole_obj
      integer :: iunit, io_stat
      character(len=256) :: output_file, basename
      output_file = get_output_json_filename()
      basename = get_basename()
      call json%initialize(real_format=JSON_REAL_FORMAT)
      call json%create_object(root, '')
      call json%create_object(main_obj, trim(basename))
      call json%add(root, main_obj)
      if (result%has_energy) call json%add(main_obj, 'total_energy', result%energy%total())
      if (result%has_dipole) then
         call json%create_object(dipole_obj, 'dipole')
         call json%add(main_obj, dipole_obj)
         call json%add(dipole_obj, 'x', result%dipole(1))
         call json%add(dipole_obj, 'y', result%dipole(2))
         call json%add(dipole_obj, 'z', result%dipole(3))
         call json%add(dipole_obj, 'magnitude_debye', norm2(result%dipole)*AU_TO_DEBYE)
      end if
      if (result%has_gradient) call json%add(main_obj, 'gradient_norm', sqrt(sum(result%gradient**2)))
      if (result%has_hessian) call json%add(main_obj, 'hessian_frobenius_norm', sqrt(sum(result%hessian**2)))
      call logger%info("Writing JSON output to "//trim(output_file))
      open (newunit=iunit, file=trim(output_file), status='replace', action='write', iostat=io_stat)
      if (io_stat /= 0) then
         call logger%error("Failed to open "//trim(output_file)//" for writing")
         call json%destroy(root)
         return
      end if
      call json%print(root, iunit)
      close (iunit)
      call json%destroy(root)
      call logger%info("JSON output written successfully to "//trim(output_file))
   end subroutine print_unfragmented_json
Call graph
print_unfragmented_json calls add, create_object, destroy, error, info, initialize, energy_total, get_basename, get_output_json_filename
energy_total calls mp2_total
hessian_coordinator calls print_unfragmented_json, hessian_coordinator
unfragmented_calculation calls print_unfragmented_json, unfragmented_calculation
distributed_unfragmented_hessian calls hessian_coordinator, distributed_unfragmented_hessian
run_unfragmented_calculation calls unfragmented_calculation, distributed_unfragmented_hessian
run_calculation calls run_unfragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation