print_fragment_xyz – metalquicha
print_fragment_xyz Subroutine
18 statements
Source File
public subroutine print_fragment_xyz(fragment_idx, phys_frag)
Print fragment geometry in XYZ format
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fragment_idx
type(physical_fragment_t), intent(in) :: phys_frag
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=256), private :: coord_line
integer, private :: i
character(len=2), private :: symbol
Source Code
   subroutine print_fragment_xyz(fragment_idx, phys_frag)
      !! Print fragment geometry in XYZ format
      integer, intent(in) :: fragment_idx
      type(physical_fragment_t), intent(in) :: phys_frag
      integer :: i
      character(len=2) :: symbol
      character(len=256) :: coord_line
      call logger%info("=========================================")
      call logger%info(" Fragment "//to_char(fragment_idx))
      call logger%info(" Number of atoms: "//to_char(phys_frag%n_atoms))
      call logger%info(" Coordinates in Angstroms:")
      call logger%info("-----------------------------------------")
      do i = 1, phys_frag%n_atoms
         symbol = element_number_to_symbol(phys_frag%element_numbers(i))
         ! Convert from Bohr back to Angstroms for printing
         write (coord_line, '(a2,3f15.8)') symbol, to_angstrom(phys_frag%coordinates(1:3, i))
         call logger%info(trim(coord_line))
      end do
      call logger%info("=========================================")
   end subroutine print_fragment_xyz
Call graph
print_fragment_xyz calls info, element_number_to_symbol, to_angstrom, to_char
do_fragment_work calls print_fragment_xyz
node_worker calls do_fragment_work
serial_fragment_processor calls do_fragment_work
serial_gmbe_pie_processor calls do_fragment_work
serial_gmbe_processor calls do_fragment_work
unfragmented_calculation calls do_fragment_work
run_fragmented_calculation calls node_worker, serial_fragment_processor, serial_gmbe_pie_processor
run_unfragmented_calculation calls unfragmented_calculation
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation