print_gmbe_json – metalquicha
print_gmbe_json Subroutine
113 statements
Source File
public subroutine print_gmbe_json(n_monomers, monomer_indices, monomer_results, n_intersections, intersection_results, intersection_sets, intersection_levels, total_energy)
Write GMBE calculation results to output JSON file Outputs structured JSON with monomers, intersections, and total energy Intersection parameters are optional and should be omitted when n_intersections=0
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n_monomers
integer, intent(in) :: monomer_indices(:)
type(calculation_result_t), intent(in) :: monomer_results(:)
integer, intent(in) :: n_intersections
type(calculation_result_t), intent(in), optional :: intersection_results(:)
integer, intent(in), optional :: intersection_sets(:,:)
(n_monomers, n_intersections)
integer, intent(in), optional :: intersection_levels(:)
real(kind=dp), intent(in) :: total_energy
Calls
Variables
Type Visibility Attributes Name Initial
character(len=256), private :: basename
logical, private :: first_intersection
logical, private :: first_level
integer, private :: i
integer, private :: io_stat
integer, private :: j
character(len=512), private :: json_line
integer, private :: k
integer, private :: level_count
integer, private :: max_level
character(len=256), private :: output_file
integer, private :: unit
Source Code
   subroutine print_gmbe_json(n_monomers, monomer_indices, monomer_results, &
                              n_intersections, intersection_results, &
                              intersection_sets, intersection_levels, total_energy)
      !! Write GMBE calculation results to output JSON file
      !! Outputs structured JSON with monomers, intersections, and total energy
      !! Intersection parameters are optional and should be omitted when n_intersections=0
      integer, intent(in) :: n_monomers
      integer, intent(in) :: monomer_indices(:)
      type(calculation_result_t), intent(in) :: monomer_results(:)
      integer, intent(in) :: n_intersections
      type(calculation_result_t), intent(in), optional :: intersection_results(:)
      integer, intent(in), optional :: intersection_sets(:, :)  !! (n_monomers, n_intersections)
      integer, intent(in), optional :: intersection_levels(:)
      real(dp), intent(in) :: total_energy
      integer :: i, j, k, max_level, unit, io_stat
      character(len=512) :: json_line
      character(len=256) :: output_file, basename
      logical :: first_level, first_intersection
      integer :: level_count
      output_file = get_output_json_filename()
      basename = get_basename()
      open (newunit=unit, file=trim(output_file), status='replace', action='write', iostat=io_stat)
      if (io_stat /= 0) then
         call logger%error("Failed to open "//trim(output_file)//" for writing")
         return
      end if
      call logger%info("Writing GMBE JSON output to "//trim(output_file))
      write (unit, '(a)') "{"
      write (json_line, '(a,a,a)') '  "', trim(basename), '": {'
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f20.10,a)') '    "total_energy": ', total_energy, ','
      write (unit, '(a)') trim(json_line)
      ! Monomers section
      write (unit, '(a)') '    "monomers": {'
      write (json_line, '(a,i0,a)') '      "count": ', n_monomers, ','
      write (unit, '(a)') trim(json_line)
      write (unit, '(a)') '      "fragments": ['
      do i = 1, n_monomers
         write (unit, '(a)') '        {'
         write (json_line, '(a,i0,a)') '          "index": ', monomer_indices(i), ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f20.10)') '          "energy": ', monomer_results(i)%energy%total()
         write (unit, '(a)') trim(json_line)
         if (i < n_monomers) then
            write (unit, '(a)') '        },'
         else
            write (unit, '(a)') '        }'
         end if
      end do
      write (unit, '(a)') '      ]'
      ! Add comma after monomers if we have intersections
      if (n_intersections > 0 .and. present(intersection_results) .and. &
          present(intersection_sets) .and. present(intersection_levels)) then
         write (unit, '(a)') '    },'
      else
         write (unit, '(a)') '    }'
      end if
      ! Intersections section
      if (n_intersections > 0 .and. present(intersection_results) .and. &
          present(intersection_sets) .and. present(intersection_levels)) then
         max_level = maxval(intersection_levels)
         write (unit, '(a)') '    "intersections": {'
         write (json_line, '(a,i0,a)') '      "total_count": ', n_intersections, ','
         write (unit, '(a)') trim(json_line)
         write (unit, '(a)') '      "levels": ['
         first_level = .true.
         do k = 2, max_level
            ! Count intersections at this level
            level_count = 0
            do i = 1, n_intersections
               if (intersection_levels(i) == k) level_count = level_count + 1
            end do
            if (level_count > 0) then
               if (.not. first_level) then
                  write (unit, '(a)') '        },'
               end if
               first_level = .false.
               write (unit, '(a)') '        {'
               write (json_line, '(a,i0,a)') '          "level": ', k, ','
               write (unit, '(a)') trim(json_line)
               write (json_line, '(a,i0,a)') '          "count": ', level_count, ','
               write (unit, '(a)') trim(json_line)
               write (unit, '(a)') '          "fragments": ['
               first_intersection = .true.
               do i = 1, n_intersections
                  if (intersection_levels(i) == k) then
                     if (.not. first_intersection) then
                        write (unit, '(a)') '            },'
                     end if
                     first_intersection = .false.
                     write (unit, '(a)') '            {'
                     ! Write indices
                     json_line = '              "indices": ['
                     do j = 1, n_monomers
                        if (intersection_sets(j, i) > 0) then
                           if (j > 1 .and. intersection_sets(j - 1, i) > 0) then
                              write (json_line, '(a,a,i0)') trim(json_line), ', ', intersection_sets(j, i)
                           else
                              write (json_line, '(a,i0)') trim(json_line), intersection_sets(j, i)
                           end if
                        end if
                     end do
                     write (json_line, '(a,a)') trim(json_line), '],'
                     write (unit, '(a)') trim(json_line)
                     write (json_line, '(a,f20.10)') '              "energy": ', intersection_results(i)%energy%total()
                     write (unit, '(a)') trim(json_line)
                  end if
               end do
               if (.not. first_intersection) then
                  write (unit, '(a)') '            }'
               end if
               write (unit, '(a)') '          ]'
            end if
         end do
         if (.not. first_level) then
            write (unit, '(a)') '        }'
         end if
         write (unit, '(a)') '      ]'
         write (unit, '(a)') '    }'
      end if
      write (unit, '(a)') '  }'
      write (unit, '(a)') '}'
      close (unit)
      call logger%info("GMBE JSON output written successfully to "//trim(output_file))
   end subroutine print_gmbe_json
Call graph
print_gmbe_json calls error, info, energy_total, get_basename, get_output_json_filename
energy_total calls mp2_total