print_detailed_breakdown_json – metalquicha
print_detailed_breakdown_json Subroutine
123 statements
Source File
public subroutine print_detailed_breakdown_json(polymers, fragment_count, max_level, energies, delta_energies, sum_by_level, total_energy, total_gradient, total_hessian, results)
Uses
mqc_result_types
Write detailed energy breakdown to results.json file Outputs structured JSON with all fragment energies and deltaE corrections Optionally includes total gradient and Hessian if provided Uses int64 for fragment_count to handle large fragment counts that overflow int32.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: polymers(:,:)
integer(kind=int64), intent(in) :: fragment_count
integer, intent(in) :: max_level
real(kind=dp), intent(in) :: energies(:)
real(kind=dp), intent(in) :: delta_energies(:)
real(kind=dp), intent(in) :: sum_by_level(:)
real(kind=dp), intent(in) :: total_energy
real(kind=dp), intent(in), optional :: total_gradient(:,:)
(3, total_atoms)
real(kind=dp), intent(in), optional :: total_hessian(:,:)
(3total_atoms, 3total_atoms)
type(calculation_result_t), intent(in), optional :: results(:)
Fragment results with distance info
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=256), private :: basename
integer(kind=int64), private :: count_by_level
logical, private :: first_fragment
logical, private :: first_level
integer, private :: frag_level
integer, private :: fragment_size
integer(kind=int64), private :: i
integer, private :: iatom
integer, private :: io_stat
integer, private :: j
character(len=512), private :: json_line
character(len=32), private :: level_name
character(len=256), private :: output_file
integer, private :: total_atoms
integer, private :: unit
Source Code
   subroutine print_detailed_breakdown_json(polymers, fragment_count, max_level, &
                                            energies, delta_energies, sum_by_level, total_energy, &
                                            total_gradient, total_hessian, results)
      !! Write detailed energy breakdown to results.json file
      !! Outputs structured JSON with all fragment energies and deltaE corrections
      !! Optionally includes total gradient and Hessian if provided
      !! Uses int64 for fragment_count to handle large fragment counts that overflow int32.
      use mqc_result_types, only: calculation_result_t
      integer, intent(in) :: polymers(:, :), max_level
      integer(int64), intent(in) :: fragment_count
      real(dp), intent(in) :: energies(:), delta_energies(:)
      real(dp), intent(in) :: sum_by_level(:), total_energy
      real(dp), intent(in), optional :: total_gradient(:, :)  !! (3, total_atoms)
      real(dp), intent(in), optional :: total_hessian(:, :)  !! (3*total_atoms, 3*total_atoms)
      type(calculation_result_t), intent(in), optional :: results(:)  !! Fragment results with distance info
      integer(int64) :: i
      integer :: fragment_size, j, frag_level, unit, io_stat, iatom
      character(len=512) :: json_line
      integer(int64) :: count_by_level
      logical :: first_level, first_fragment
      character(len=32) :: level_name
      integer :: total_atoms
      character(len=256) :: output_file, basename
      output_file = get_output_json_filename()
      basename = get_basename()
      open (newunit=unit, file=trim(output_file), status='replace', action='write', iostat=io_stat)
      if (io_stat /= 0) then
         call logger%error("Failed to open "//trim(output_file)//" for writing")
         return
      end if
      call logger%info("Writing JSON output to "//trim(output_file))
      ! Warn if we have very high fragmentation levels
      if (max_level > 10) then
         call logger%warning("Fragment levels exceed decamers (10-mers). JSON will use generic N-mers notation.")
      end if
      write (unit, '(a)') "{"
      write (json_line, '(a,a,a)') '  "', trim(basename), '": {'
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f20.10,a)') '    "total_energy": ', total_energy, ','
      write (unit, '(a)') trim(json_line)
      write (unit, '(a)') '    "levels": ['
      first_level = .true.
      do frag_level = 1, max_level
         count_by_level = 0_int64
         do i = 1_int64, fragment_count
            fragment_size = count(polymers(i, :) > 0)
            if (fragment_size == frag_level) count_by_level = count_by_level + 1_int64
         end do
         if (count_by_level > 0_int64) then
            if (.not. first_level) then
               write (unit, '(a)') '      },'
            end if
            first_level = .false.
            write (unit, '(a)') '      {'
            level_name = get_frag_level_name(frag_level)
            write (json_line, '(a,i0,a)') '        "frag_level": ', frag_level, ','
            write (unit, '(a)') trim(json_line)
            write (json_line, '(a,a,a)') '        "name": "', trim(level_name), '",'
            write (unit, '(a)') trim(json_line)
            write (json_line, '(a,i0,a)') '        "count": ', count_by_level, ','
            write (unit, '(a)') trim(json_line)
            write (json_line, '(a,f20.10,a)') '        "total_energy": ', sum_by_level(frag_level), ','
            write (unit, '(a)') trim(json_line)
            write (unit, '(a)') '        "fragments": ['
            first_fragment = .true.
            do i = 1_int64, fragment_count
               fragment_size = count(polymers(i, :) > 0)
               if (fragment_size == frag_level) then
                  if (.not. first_fragment) then
                     write (unit, '(a)') '          },'
                  end if
                  first_fragment = .false.
                  write (unit, '(a)') '          {'
                  json_line = '            "indices": ['
                  do j = 1, fragment_size
                     if (j > 1) then
                        write (json_line, '(a,a,i0)') trim(json_line), ', ', polymers(i, j)
                     else
                        write (json_line, '(a,i0)') trim(json_line), polymers(i, j)
                     end if
                  end do
                  write (json_line, '(a,a)') trim(json_line), '],'
                  write (unit, '(a)') trim(json_line)
                  write (json_line, '(a,f20.10,a)') '            "energy": ', energies(i), ','
                  write (unit, '(a)') trim(json_line)
                  ! Add distance field if available
                  if (present(results)) then
                     write (json_line, '(a,f20.10)') '            "distance": ', results(i)%distance
                     if (frag_level > 1) then
                        write (json_line, '(a,a)') trim(json_line), ','
                        write (unit, '(a)') trim(json_line)
                        write (json_line, '(a,f20.10)') '            "delta_energy": ', delta_energies(i)
                     end if
                  else
                     if (frag_level > 1) then
                        write (json_line, '(a,f20.10)') '            "delta_energy": ', delta_energies(i)
                     end if
                  end if
                  write (unit, '(a)') trim(json_line)
               end if
            end do
            if (.not. first_fragment) then
               write (unit, '(a)') '          }'
            end if
            write (unit, '(a)') '        ]'
         end if
      end do
      if (.not. first_level) then
         write (unit, '(a)') '      }'
      end if
      ! Close levels array (with comma if we have more fields)
      if (present(total_gradient) .or. present(total_hessian)) then
         write (unit, '(a)') '    ],'
      else
         write (unit, '(a)') '    ]'
      end if
      ! Add gradient norm if present (inside basename object)
      if (present(total_gradient)) then
         write (json_line, '(a,f20.10)') '    "gradient_norm": ', sqrt(sum(total_gradient**2))
         if (present(total_hessian)) then
            write (json_line, '(a,a)') trim(json_line), ','
         end if
         write (unit, '(a)') trim(json_line)
      end if
      ! Add Hessian Frobenius norm if present (inside basename object)
      if (present(total_hessian)) then
         write (json_line, '(a,f20.10)') '    "hessian_frobenius_norm": ', sqrt(sum(total_hessian**2))
         write (unit, '(a)') trim(json_line)
      end if
      ! Close basename object
      write (unit, '(a)') '  }'
      ! Close outer object
      write (unit, '(a)') '}'
      close (unit)
      call logger%info("JSON output written successfully to "//trim(output_file))
   end subroutine print_detailed_breakdown_json
Call graph
print_detailed_breakdown_json calls error, info, get_basename, get_frag_level_name, get_output_json_filename, warning
compute_mbe_energy calls print_detailed_breakdown_json
compute_mbe_energy_gradient calls print_detailed_breakdown_json
compute_mbe_energy_gradient_hessian calls print_detailed_breakdown_json
global_coordinator calls compute_mbe_energy, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian
serial_fragment_processor calls compute_mbe_energy, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian, serial_fragment_processor
run_fragmented_calculation calls serial_fragment_processor
run_calculation calls run_fragmented_calculation