print_gmbe_pie_json – metalquicha
print_gmbe_pie_json Subroutine
79 statements
Source File
public subroutine print_gmbe_pie_json(pie_atom_sets, pie_coefficients, pie_energies, n_pie_terms, total_energy, total_gradient, total_hessian)
Write GMBE PIE calculation results to output JSON file Outputs structured JSON with PIE terms (atom sets with coefficients and energies) Optionally includes total gradient and Hessian norms
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: pie_atom_sets(:,:)
Unique atom sets (max_atoms, n_pie_terms)
integer, intent(in) :: pie_coefficients(:)
PIE coefficient for each term
real(kind=dp), intent(in) :: pie_energies(:)
Raw energy for each term
integer, intent(in) :: n_pie_terms
real(kind=dp), intent(in) :: total_energy
real(kind=dp), intent(in), optional :: total_gradient(:,:)
(3, total_atoms)
real(kind=dp), intent(in), optional :: total_hessian(:,:)
(3total_atoms, 3total_atoms)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
character(len=256), private :: basename
logical, private :: first_term
integer, private :: i
integer, private :: io_stat
integer, private :: j
character(len=512), private :: json_line
integer, private :: max_atoms
integer, private :: n_atoms
integer, private :: n_nonzero_terms
character(len=256), private :: output_file
integer, private :: unit
Source Code
   subroutine print_gmbe_pie_json(pie_atom_sets, pie_coefficients, pie_energies, n_pie_terms, total_energy, &
                                  total_gradient, total_hessian)
      !! Write GMBE PIE calculation results to output JSON file
      !! Outputs structured JSON with PIE terms (atom sets with coefficients and energies)
      !! Optionally includes total gradient and Hessian norms
      integer, intent(in) :: pie_atom_sets(:, :)  !! Unique atom sets (max_atoms, n_pie_terms)
      integer, intent(in) :: pie_coefficients(:)  !! PIE coefficient for each term
      real(dp), intent(in) :: pie_energies(:)  !! Raw energy for each term
      integer, intent(in) :: n_pie_terms
      real(dp), intent(in) :: total_energy
      real(dp), intent(in), optional :: total_gradient(:, :)  !! (3, total_atoms)
      real(dp), intent(in), optional :: total_hessian(:, :)  !! (3*total_atoms, 3*total_atoms)
      integer :: i, j, max_atoms, n_atoms
      integer :: unit, io_stat
      integer :: n_nonzero_terms
      logical :: first_term
      character(len=512) :: json_line
      character(len=256) :: output_file, basename
      output_file = get_output_json_filename()
      basename = get_basename()
      open (newunit=unit, file=trim(output_file), status='replace', action='write', iostat=io_stat)
      if (io_stat /= 0) then
         call logger%error("Failed to open "//trim(output_file)//" for writing")
         return
      end if
      call logger%info("Writing GMBE PIE JSON output to "//trim(output_file))
      write (unit, '(a)') "{"
      write (json_line, '(a,a,a)') '  "', trim(basename), '": {'
      write (unit, '(a)') trim(json_line)
      write (json_line, '(a,f20.10,a)') '    "total_energy": ', total_energy, ','
      write (unit, '(a)') trim(json_line)
      ! Add gradient if present
      if (present(total_gradient)) then
         write (json_line, '(a,f20.10,a)') '    "gradient_norm": ', sqrt(sum(total_gradient**2)), ','
         write (unit, '(a)') trim(json_line)
      end if
      ! Add Hessian if present
      if (present(total_hessian)) then
         write (json_line, '(a,f20.10,a)') '    "hessian_frobenius_norm": ', sqrt(sum(total_hessian**2)), ','
         write (unit, '(a)') trim(json_line)
      end if
      ! PIE terms section
      ! First count non-zero coefficient terms
      n_nonzero_terms = 0
      do i = 1, n_pie_terms
         if (pie_coefficients(i) /= 0) n_nonzero_terms = n_nonzero_terms + 1
      end do
      write (unit, '(a)') '    "pie_terms": {'
      write (json_line, '(a,i0,a)') '      "count": ', n_nonzero_terms, ','
      write (unit, '(a)') trim(json_line)
      write (unit, '(a)') '      "terms": ['
      max_atoms = size(pie_atom_sets, 1)
      first_term = .true.
      do i = 1, n_pie_terms
         ! Skip terms with zero coefficient
         if (pie_coefficients(i) == 0) cycle
         if (.not. first_term) write (unit, '(a)') '        },'
         first_term = .false.
         write (unit, '(a)') '        {'
         ! Extract atom list size
         n_atoms = 0
         do while (n_atoms < max_atoms .and. pie_atom_sets(n_atoms + 1, i) >= 0)
            n_atoms = n_atoms + 1
         end do
         ! Write atom indices
         json_line = '          "atom_indices": ['
         do j = 1, n_atoms
            if (j > 1) then
               write (json_line, '(a,a,i0)') trim(json_line), ', ', pie_atom_sets(j, i)
            else
               write (json_line, '(a,i0)') trim(json_line), pie_atom_sets(j, i)
            end if
         end do
         write (json_line, '(a,a)') trim(json_line), '],'
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,i0,a)') '          "coefficient": ', pie_coefficients(i), ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f20.10,a)') '          "energy": ', pie_energies(i), ','
         write (unit, '(a)') trim(json_line)
         write (json_line, '(a,f20.10)') '          "weighted_energy": ', &
            real(pie_coefficients(i), dp)*pie_energies(i)
         write (unit, '(a)') trim(json_line)
      end do
      if (.not. first_term) write (unit, '(a)') '        }'
      write (unit, '(a)') '      ]'
      write (unit, '(a)') '    }'
      write (unit, '(a)') '  }'
      write (unit, '(a)') '}'
      close (unit)
      call logger%info("GMBE PIE JSON output written successfully to "//trim(output_file))
   end subroutine print_gmbe_pie_json
Call graph
print_gmbe_pie_json calls error, info, get_basename, get_output_json_filename
gmbe_pie_coordinator calls print_gmbe_pie_json
serial_gmbe_pie_processor calls print_gmbe_pie_json
run_fragmented_calculation calls gmbe_pie_coordinator, serial_gmbe_pie_processor
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations