print_vibrational_json_mbe – metalquicha
print_vibrational_json_mbe Subroutine
20 statements
Source File
public subroutine print_vibrational_json_mbe(mbe_result, frequencies, reduced_masses, force_constants, thermo, ir_intensities)
Write vibrational analysis and thermochemistry results to JSON file for MBE calculations Wrapper that extracts values from mbe_result_t and calls the implementation
Arguments
Type Intent Optional Attributes Name
type(mbe_result_t), intent(in) :: mbe_result
real(kind=dp), intent(in) :: frequencies(:)
real(kind=dp), intent(in) :: reduced_masses(:)
real(kind=dp), intent(in) :: force_constants(:)
type(thermochemistry_result_t), intent(in) :: thermo
real(kind=dp), intent(in), optional :: ir_intensities(:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
real(kind=dp), private :: grad_norm
real(kind=dp), private :: hess_norm
Source Code
   subroutine print_vibrational_json_mbe(mbe_result, frequencies, reduced_masses, force_constants, &
                                         thermo, ir_intensities)
      !! Write vibrational analysis and thermochemistry results to JSON file for MBE calculations
      !! Wrapper that extracts values from mbe_result_t and calls the implementation
      type(mbe_result_t), intent(in) :: mbe_result
      real(dp), intent(in) :: frequencies(:)
      real(dp), intent(in) :: reduced_masses(:)
      real(dp), intent(in) :: force_constants(:)
      type(thermochemistry_result_t), intent(in) :: thermo
      real(dp), intent(in), optional :: ir_intensities(:)
      real(dp) :: grad_norm, hess_norm
      ! Compute norms if available
      if (mbe_result%has_gradient) then
         grad_norm = sqrt(sum(mbe_result%gradient**2))
      end if
      if (mbe_result%has_hessian) then
         hess_norm = sqrt(sum(mbe_result%hessian**2))
      end if
      ! Call implementation with extracted values
      ! mbe_result_t stores energy directly as total_energy
      if (present(ir_intensities)) then
         call write_vibrational_json_impl(mbe_result%total_energy, mbe_result%has_energy, &
                                          mbe_result%dipole, mbe_result%has_dipole, &
                                          grad_norm, mbe_result%has_gradient, &
                                          hess_norm, mbe_result%has_hessian, &
                                          frequencies, reduced_masses, force_constants, &
                                          thermo, ir_intensities)
      else
         call write_vibrational_json_impl(mbe_result%total_energy, mbe_result%has_energy, &
                                          mbe_result%dipole, mbe_result%has_dipole, &
                                          grad_norm, mbe_result%has_gradient, &
                                          hess_norm, mbe_result%has_hessian, &
                                          frequencies, reduced_masses, force_constants, &
                                          thermo)
      end if
   end subroutine print_vibrational_json_mbe
Call graph
print_vibrational_json_mbe calls write_vibrational_json_impl
write_vibrational_json_impl calls add, create_object, destroy, error, info, initialize, get_basename, get_output_json_filename
compute_mbe calls print_vibrational_json_mbe
gmbe_pie_coordinator calls print_vibrational_json_mbe
serial_gmbe_pie_processor calls print_vibrational_json_mbe
global_coordinator calls compute_mbe, global_coordinator
run_fragmented_calculation calls gmbe_pie_coordinator, serial_gmbe_pie_processor, global_coordinator, serial_fragment_processor
serial_fragment_processor calls compute_mbe, serial_fragment_processor
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations