process_chemistry_fragment – metalquicha
process_chemistry_fragment Subroutine
33 statements
Source File
public subroutine process_chemistry_fragment(fragment_idx, fragment_indices, fragment_size, matrix_size, water_energy, C_flat, method, phys_frag, verbosity)
Process a single fragment for quantum chemistry calculation
Performs energy and gradient calculation on a molecular fragment using specified quantum chemistry method (GFN-xTB variants).
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: fragment_idx
Fragment index for identification
integer, intent(in) :: fragment_indices(fragment_size)
Monomer indices comprising this fragment
integer, intent(in) :: fragment_size
Number of monomers in fragment
integer, intent(in) :: matrix_size
Size of gradient matrix (natoms*3)
real(kind=dp), intent(out) :: water_energy
Computed energy for this fragment
real(kind=dp), intent(out), allocatable :: C_flat(:)
Flattened gradient array
character(len=*), intent(in) :: method
QC method (gfn1, gfn2)
type(physical_fragment_t), intent(in), optional :: phys_frag
Fragment geometry
integer, intent(in), optional :: verbosity
Verbosity level (0=silent, 1=verbose)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(calculation_result_t), private :: result
Computation results
integer, private :: verb_level
Local verbosity setting
type(xtb_method_t), private :: xtb_calc
XTB calculator instance
Source Code
   subroutine process_chemistry_fragment(fragment_idx, fragment_indices, fragment_size, matrix_size, &
                                         water_energy, C_flat, method, phys_frag, verbosity)
      !! Process a single fragment for quantum chemistry calculation
      !!
      !! Performs energy and gradient calculation on a molecular fragment using
      !! specified quantum chemistry method (GFN-xTB variants).
      integer, intent(in) :: fragment_idx        !! Fragment index for identification
      integer, intent(in) :: fragment_size       !! Number of monomers in fragment
      integer, intent(in) :: fragment_indices(fragment_size)  !! Monomer indices comprising this fragment
      integer, intent(in) :: matrix_size         !! Size of gradient matrix (natoms*3)
      real(dp), intent(out) :: water_energy      !! Computed energy for this fragment
      real(dp), allocatable, intent(out) :: C_flat(:)  !! Flattened gradient array
      character(len=*), intent(in) :: method     !! QC method (gfn1, gfn2)
      type(physical_fragment_t), intent(in), optional :: phys_frag  !! Fragment geometry
      integer, intent(in), optional :: verbosity  !! Verbosity level (0=silent, 1=verbose)
      integer :: verb_level  !! Local verbosity setting
#ifndef MQC_WITHOUT_TBLITE
      type(xtb_method_t) :: xtb_calc  !! XTB calculator instance
#endif
      type(calculation_result_t) :: result  !! Computation results
      ! Set verbosity level (default is 0 for silent operation)
      if (present(verbosity)) then
         verb_level = verbosity
      else
         verb_level = 0
      end if
      ! Print fragment geometry if provided
      if (present(phys_frag)) then
         if (verb_level == 1) then
            call print_fragment_xyz(fragment_idx, phys_frag)
         end if
#ifndef MQC_WITHOUT_TBLITE
         ! Setup XTB method
         xtb_calc%variant = method
         xtb_calc%verbose = (verb_level > 0)
         ! Run the calculation using the method API
         call xtb_calc%calc_energy(phys_frag, result)
         water_energy = result%energy
         ! Clean up result
         call result%destroy()
#else
         call logger%error("XTB method requested but tblite support not compiled in")
         call logger%error("Please rebuild with -DMQC_ENABLE_TBLITE=ON")
         error stop "tblite support not available"
#endif
      else
         water_energy = 0.0_dp
      end if      ! Return empty vector for C_flat
      allocate (C_flat(1))
      C_flat(1) = 0.0_dp
   end subroutine process_chemistry_fragment
Call graph
process_chemistry_fragment calls print_fragment_xyz, result_destroy, xtb_calc_energy
print_fragment_xyz calls info, element_number_to_symbol, to_angstrom, to_char
result_destroy calls result_reset
xtb_calc_energy calls new, new_gfn1_calculator, new_gfn2_calculator, new_wavefunction, xtb_singlepoint
node_worker calls process_chemistry_fragment
unfragmented_calculation calls process_chemistry_fragment
run_fragmented_calculation calls node_worker
run_unfragmented_calculation calls unfragmented_calculation
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
main calls run_calculation