result_destroy – metalquicha
result_destroy Subroutine
8 statements
Source File
private subroutine result_destroy(this)
Clean up allocated memory in calculation_result_t
Type Bound
calculation_result_t
Arguments
Type Intent Optional Attributes Name
class(calculation_result_t), intent(inout) :: this
Calls
Called by
Source Code
   subroutine result_destroy(this)
      !! Clean up allocated memory in calculation_result_t
      class(calculation_result_t), intent(inout) :: this
      if (allocated(this%gradient)) deallocate (this%gradient)
      if (allocated(this%sigma)) deallocate (this%sigma)
      if (allocated(this%hessian)) deallocate (this%hessian)
      if (allocated(this%dipole)) deallocate (this%dipole)
      call this%reset()
   end subroutine result_destroy
Call graph
result_destroy calls result_reset
result_reset calls energy_reset
energy_reset calls mp2_reset
compute_energy_and_forces calls result_destroy, run_calculation
hessian_coordinator calls result_destroy
hessian_worker calls result_destroy
unfragmented_calculation calls result_destroy, do_fragment_work
xtb_calc_hessian calls result_destroy
distributed_unfragmented_hessian calls hessian_coordinator, hessian_worker
do_fragment_work calls xtb_calc_hessian
run_unfragmented_calculation calls unfragmented_calculation, distributed_unfragmented_hessian
node_worker calls do_fragment_work
run_calculation calls run_unfragmented_calculation, run_fragmented_calculation
serial_fragment_processor calls do_fragment_work
serial_gmbe_pie_processor calls do_fragment_work
run_fragmented_calculation calls node_worker, serial_fragment_processor, serial_gmbe_pie_processor
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations