run_calculation – metalquicha
run_calculation Subroutine
90 statements
Source File
public subroutine run_calculation(resources, config, sys_geom, bonds, result_out, all_ranks_write_json)
Main calculation dispatcher - routes to fragmented or unfragmented calculation
Determines calculation type based on nlevel and dispatches to appropriate calculation routine with proper MPI setup and validation. If result_out is present, returns result instead of writing JSON (for dynamics/optimization)
Arguments
Type Intent Optional Attributes Name
type(resources_t), intent(in) :: resources
Resources container (MPI comms, etc.)
type(driver_config_t), intent(in) :: config
Driver configuration
type(system_geometry_t), intent(in) :: sys_geom
System geometry and fragment info
type(bond_t), intent(in), optional :: bonds(:)
Bond connectivity information
type(calculation_result_t), intent(out), optional :: result_out
Optional result output
logical, intent(in), optional :: all_ranks_write_json
If true, all ranks write JSON (for multi-molecule)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: i
Loop counter
type(json_output_data_t), private :: json_data
Cached output data for centralized JSON writing
integer, private :: max_level
Maximum fragment level (nlevel from config)
logical, private :: should_write_json
Whether this rank should write JSON
Source Code
   subroutine run_calculation(resources, config, sys_geom, bonds, result_out, all_ranks_write_json)
      !! Main calculation dispatcher - routes to fragmented or unfragmented calculation
      !!
      !! Determines calculation type based on nlevel and dispatches to appropriate
      !! calculation routine with proper MPI setup and validation.
      !! If result_out is present, returns result instead of writing JSON (for dynamics/optimization)
      type(resources_t), intent(in) :: resources  !! Resources container (MPI comms, etc.)
      type(driver_config_t), intent(in) :: config  !! Driver configuration
      type(system_geometry_t), intent(in) :: sys_geom  !! System geometry and fragment info
      type(bond_t), intent(in), optional :: bonds(:)  !! Bond connectivity information
      type(calculation_result_t), intent(out), optional :: result_out  !! Optional result output
      logical, intent(in), optional :: all_ranks_write_json  !! If true, all ranks write JSON (for multi-molecule)
      ! Local variables
      integer :: max_level   !! Maximum fragment level (nlevel from config)
      integer :: i  !! Loop counter
      type(json_output_data_t) :: json_data  !! Cached output data for centralized JSON writing
      logical :: should_write_json  !! Whether this rank should write JSON
      ! Set XTB solvation options from config (before any calculations)
      if (allocated(config%solvent) .or. config%dielectric > 0.0_dp) then
         if (allocated(config%solvation_model)) then
            call set_xtb_options(solvent=config%solvent, solvation_model=config%solvation_model, &
                                 use_cds=config%use_cds, use_shift=config%use_shift, &
                                 dielectric=config%dielectric, cpcm_nang=config%cpcm_nang, &
                                 cpcm_rscale=config%cpcm_rscale)
         else
            call set_xtb_options(solvent=config%solvent, solvation_model="alpb", &
                                 use_cds=config%use_cds, use_shift=config%use_shift, &
                                 dielectric=config%dielectric, cpcm_nang=config%cpcm_nang, &
                                 cpcm_rscale=config%cpcm_rscale)
         end if
         if (resources%mpi_comms%world_comm%rank() == 0) then
            if (allocated(config%solvation_model)) then
               if (trim(config%solvation_model) == 'cpcm') then
                  if (config%dielectric > 0.0_dp) then
                     call logger%info("XTB solvation enabled: cpcm with dielectric = "//to_char(config%dielectric))
                  else
                     call logger%info("XTB solvation enabled: cpcm with "//config%solvent)
                  end if
                  call logger%info("  CPCM grid points (nang): "//to_char(config%cpcm_nang))
                  call logger%info("  CPCM radii scale: "//to_char(config%cpcm_rscale))
               else
                  call logger%info("XTB solvation enabled: "//trim(config%solvation_model)//" with "//config%solvent)
                  if (config%use_cds) call logger%info("  CDS (non-polar) terms: enabled")
                  if (config%use_shift) call logger%info("  Solution state shift: enabled")
               end if
            else
               call logger%info("XTB solvation enabled: alpb with "//config%solvent)
               if (config%use_cds) call logger%info("  CDS (non-polar) terms: enabled")
               if (config%use_shift) call logger%info("  Solution state shift: enabled")
            end if
         end if
      else
         call set_xtb_options(use_cds=config%use_cds, use_shift=config%use_shift)
      end if
      ! Set max_level from config
      max_level = config%nlevel
      if (resources%mpi_comms%world_comm%rank() == 0) then
         call logger%info("============================================")
         call logger%info("Loaded geometry:")
         call logger%info("  Total monomers: "//to_char(sys_geom%n_monomers))
         call logger%info("  Atoms per monomer: "//to_char(sys_geom%atoms_per_monomer))
         call logger%info("  Total atoms: "//to_char(sys_geom%total_atoms))
         call logger%info("  Fragment level: "//to_char(max_level))
         call logger%info("============================================")
      end if
      ! Warn if overlapping fragments flag is set but nlevel=0
      if (config%allow_overlapping_fragments .and. max_level == 0) then
         if (resources%mpi_comms%world_comm%rank() == 0) then
            call logger%warning("allow_overlapping_fragments is set to true, but nlevel=0")
            call logger%warning("Running unfragmented calculation - overlapping fragments flag will be ignored")
         end if
      end if
      ! GMBE (overlapping fragments) with inclusion-exclusion principle
      ! GMBE(1): Base fragments are monomers
      ! GMBE(N): Base fragments are N-mers (e.g., dimers for N=2)
      ! Algorithm: Generate primaries, use DFS to enumerate overlapping cliques,
      ! accumulate PIE coefficients per unique atom set, evaluate each once
      if (max_level == 0) then
         call omp_set_num_threads(1)
         if (present(result_out)) then
            ! For dynamics/optimization: return result directly, no JSON output
            call run_unfragmented_calculation(resources%mpi_comms%world_comm, sys_geom, &
                                              config%method, config%calc_type, bonds, config, result_out)
         else
            ! Normal mode: collect json_data for centralized output
            call run_unfragmented_calculation(resources%mpi_comms%world_comm, sys_geom, &
                                              config%method, config%calc_type, bonds, config, &
                                              json_data=json_data)
         end if
      else
         if (present(result_out)) then
            ! For fragmented calculations with result_out (future use)
            call run_fragmented_calculation(resources, config%method, config%calc_type, sys_geom, max_level, &
                                            config%allow_overlapping_fragments, &
                                            config%max_intersection_level, bonds, config)
         else
            ! Normal mode: collect json_data for centralized output
            call run_fragmented_calculation(resources, config%method, config%calc_type, sys_geom, max_level, &
                                            config%allow_overlapping_fragments, &
                                            config%max_intersection_level, bonds, config, json_data)
         end if
      end if
      ! Centralized JSON output (rank 0 only by default, or all ranks if all_ranks_write_json is set)
      if (.not. present(result_out)) then
         ! Check if JSON output should be skipped
         if (config%skip_json_output) then
            if (resources%mpi_comms%world_comm%rank() == 0) then
               call logger%info("Skipping JSON output (skip_json_output = true)")
            end if
         else
            ! Determine if this rank should write JSON
            should_write_json = (resources%mpi_comms%world_comm%rank() == 0)
            if (present(all_ranks_write_json)) then
               if (all_ranks_write_json) should_write_json = .true.
            end if
            if (should_write_json) then
               if (json_data%output_mode /= OUTPUT_MODE_NONE) then
                  call write_json_output(json_data)
                  call json_data%destroy()
               end if
            end if
         end if
      end if
   end subroutine run_calculation
Call graph
run_calculation calls info, omp_set_num_threads, json_output_data_destroy, run_fragmented_calculation, run_unfragmented_calculation, set_xtb_options, write_json_output, to_char, warning
json_output_data_destroy calls json_output_data_reset
run_fragmented_calculation calls info, omp_set_num_threads, to_char, abort_comm, allgather, bcast, error, global_coordinator, node_coordinator, node_worker, serial_fragment_processor, leader, omp_get_max_threads, apply_distance_screening, binomial, combine, create_monomer_list, error_get_message, error_has_error, generate_fragment_list, get_nfrags, gmbe_enumerate_pie_terms, gmbe_pie_coordinator, serial_gmbe_pie_processor, sort_fragments_by_size, verbose
run_unfragmented_calculation calls info, to_char, distributed_unfragmented_hessian, unfragmented_calculation, calc_type_to_string, verbose
write_json_output calls error, write_gmbe_pie_json_impl, write_mbe_breakdown_json_impl, write_unfragmented_json_impl, write_vibrational_json_impl
distributed_unfragmented_hessian calls distributed_unfragmented_hessian, barrier, hessian_coordinator, hessian_worker
global_coordinator calls global_coordinator, info, to_char, abort_comm, error, error_get_message, verbose, destroy, get_elapsed_time, iprobe, irecv, isend, result_irecv, start, allocate_dipole, allocate_gradient, allocate_hessian, debug, compute_mbe, send_fragment_to_node, send_fragment_to_worker
node_coordinator calls node_coordinator, to_char, abort_comm, error, error_get_message, iprobe, irecv, isend, result_irecv, result_isend, recv
node_worker calls node_worker, to_char, abort_comm, error, error_has_error, do_fragment_work, irecv, isend, build_fragment_from_atom_list, error_get_full_trace, fragment_destroy, build_fragment_from_indices, result_isend, recv
serial_fragment_processor calls serial_fragment_processor, info, omp_set_num_threads, to_char, error, omp_get_max_threads, calc_type_to_string, error_get_message, error_has_error, verbose, configuration, get_elapsed_time, do_fragment_work, energy_total, error_get_full_trace, fragment_destroy, start, build_fragment_from_indices, compute_mbe, mbe_result_allocate_dipole, mbe_result_allocate_gradient, mbe_result_allocate_hessian
unfragmented_calculation calls unfragmented_calculation, info, to_char, error, error_get_message, error_has_error, cart_disp, configuration, fc_mdyne, force_constants, frequencies, do_fragment_work, compute_thermochemistry, compute_vibrational_analysis, energy_total, error_get_full_trace, print_vibrational_analysis, reduced_masses, eigenvalues, ir_intensities, check_duplicate_atoms, compute_vibrational_frequencies, fragment_compute_nelec, result_destroy, projected_hessian
apply_distance_screening calls info, to_char, fragment_should_be_screened
combine calls combine_util
generate_fragment_list calls combine
get_nfrags calls binomial
gmbe_enumerate_pie_terms calls info, to_char, error_has_error, atom_list, compute_polymer_atoms, dfs_pie_accumulate, error_set
gmbe_pie_coordinator calls info, to_char, abort_comm, error, error_get_message, verbose, cart_disp, configuration, fc_mdyne, force_constants, frequencies, get_elapsed_time, iprobe, irecv, isend, build_fragment_from_atom_list, compute_thermochemistry, compute_vibrational_analysis, energy_total, fragment_destroy, print_vibrational_analysis, redistribute_cap_dipole_derivatives, redistribute_cap_gradients, redistribute_cap_hessian, result_irecv, send_pie_term_to_node, send_pie_term_to_worker, reduced_masses, start
serial_gmbe_pie_processor calls info, to_char, error, calc_type_to_string, error_get_message, error_has_error, verbose, cart_disp, configuration, fc_mdyne, force_constants, frequencies, do_fragment_work, build_fragment_from_atom_list, compute_thermochemistry, compute_vibrational_analysis, energy_total, error_get_full_trace, fragment_destroy, print_vibrational_analysis, redistribute_cap_dipole_derivatives, redistribute_cap_gradients, redistribute_cap_hessian, reduced_masses
sort_fragments_by_size calls info, sort_index
write_gmbe_pie_json_impl calls info, error, add, create_array, create_object, destroy, initialize, get_basename, get_output_json_filename
write_mbe_breakdown_json_impl calls info, warning, error, add, create_array, create_object, destroy, initialize, get_basename, get_frag_level_name, get_output_json_filename
write_unfragmented_json_impl calls info, error, add, create_object, destroy, initialize, get_basename, get_output_json_filename
write_vibrational_json_impl calls info, error, add, create_object, destroy, initialize, get_basename, get_output_json_filename
do_fragment_work calls do_fragment_work, to_char, calc_type_to_string, configuration, error_set, error_add_context, energy_reset, method_type_to_string, print_fragment_xyz, xtb_calc_energy, xtb_calc_gradient, xtb_calc_hessian
build_fragment_from_atom_list calls error_has_error, add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
combine_util calls combine_util
compute_thermochemistry calls compute_electronic_entropy, compute_moments_of_inertia, compute_partition_functions, compute_rotational_constants, compute_rotational_thermo, compute_translational_thermo, compute_vibrational_thermo, compute_zpe
compute_vibrational_analysis calls compute_cartesian_displacements, compute_force_constants, compute_ir_intensities, compute_reduced_masses, compute_vibrational_frequencies
dfs_pie_accumulate calls error_has_error, dfs_pie_accumulate, new_clique, atom_sets_equal, grow_pie_storage, intersect_atom_lists, test_intersect
energy_total calls mp2_total
error_get_full_trace calls error_has_error
fragment_destroy calls basis_set_destroy
fragment_should_be_screened calls calculate_monomer_distance, get_next_combination
print_vibrational_analysis calls info, warning, compute_thermochemistry, element_number_to_symbol, print_thermochemistry
result_irecv calls irecv, recv
send_pie_term_to_node calls isend
send_pie_term_to_worker calls isend
hessian_coordinator calls hessian_coordinator
hessian_worker calls hessian_worker
basis_set_destroy calls atomic_basis_destroy
build_fragment_from_indices calls error_has_error, add_hydrogen_caps, calculate_monomer_distance, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
calculate_monomer_distance calls to_angstrom
check_duplicate_atoms calls to_char, error, error_set, element_number_to_symbol
compute_cartesian_displacements calls element_mass
compute_ir_intensities calls element_mass
compute_mbe calls info, to_char, warning, abort_comm, error, cart_disp, configuration, fc_mdyne, force_constants, frequencies, compute_thermochemistry, compute_vibrational_analysis, energy_total, print_vibrational_analysis, reduced_masses, get_message, has_error, build_mbe_lookup_table, compute_mbe_delta, compute_mbe_dipole, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian, fragment_lookup_destroy, map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, print_detailed_breakdown, print_mbe_energy_breakdown, print_mbe_gradient_info
compute_moments_of_inertia calls to_char, warning, pic_syev, element_mass
compute_reduced_masses calls element_mass
compute_vibrational_frequencies calls warning, error, pic_syev, mass_weight_hessian, project_translation_rotation
compute_zpe calls to_char, warning
grow_pie_storage calls to_char, error_set
print_thermochemistry calls info
result_destroy calls result_reset
result_isend calls isend, send
send_fragment_to_node calls isend
send_fragment_to_worker calls isend
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations