run_unfragmented_calculation – metalquicha
run_unfragmented_calculation Subroutine
37 statements
Source File
private subroutine run_unfragmented_calculation(world_comm, sys_geom, method, calc_type, bonds, driver_config, result_out)
Handle unfragmented calculation (nlevel=0)
For single-molecule mode: Only rank 0 runs (validates single rank) For multi-molecule mode: ALL ranks can run (each with their own molecule) For Hessian calculations with multiple ranks: Uses distributed parallelization If result_out is present, returns result instead of writing JSON
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: world_comm
Global MPI communicator
type(system_geometry_t), intent(in) :: sys_geom
Complete system geometry
integer(kind=int32), intent(in) :: method
Quantum chemistry method
integer(kind=int32), intent(in) :: calc_type
Calculation type
type(bond_t), intent(in), optional :: bonds(:)
Bond connectivity information
type(driver_config_t), intent(in), optional :: driver_config
Driver configuration
type(calculation_result_t), intent(out), optional :: result_out
Optional result output
Calls
Called by
Source Code
   subroutine run_unfragmented_calculation(world_comm, sys_geom, method, calc_type, bonds, driver_config, result_out)
      !! Handle unfragmented calculation (nlevel=0)
      !!
      !! For single-molecule mode: Only rank 0 runs (validates single rank)
      !! For multi-molecule mode: ALL ranks can run (each with their own molecule)
      !! For Hessian calculations with multiple ranks: Uses distributed parallelization
      !! If result_out is present, returns result instead of writing JSON
      type(comm_t), intent(in) :: world_comm  !! Global MPI communicator
      type(system_geometry_t), intent(in) :: sys_geom  !! Complete system geometry
      integer(int32), intent(in) :: method  !! Quantum chemistry method
      integer(int32), intent(in) :: calc_type  !! Calculation type
      type(bond_t), intent(in), optional :: bonds(:)  !! Bond connectivity information
      type(driver_config_t), intent(in), optional :: driver_config  !! Driver configuration
      type(calculation_result_t), intent(out), optional :: result_out  !! Optional result output
      ! For Hessian calculations with multiple ranks, use distributed approach
      if (calc_type == CALC_TYPE_HESSIAN .and. world_comm%size() > 1) then
         if (world_comm%rank() == 0) then
            call logger%info(" ")
            call logger%info("Running distributed unfragmented Hessian calculation")
            call logger%info("  MPI ranks: "//to_char(world_comm%size()))
            call logger%info(" ")
         end if
         call distributed_unfragmented_hessian(world_comm, sys_geom, method, driver_config)
         return
      end if
      ! Check if this is multi-molecule mode or single-molecule mode
      ! In multi-molecule mode, each rank processes its own molecule
      ! In single-molecule mode, only rank 0 should work
      if (world_comm%size() == 1 .or. world_comm%rank() == 0) then
         ! Either single-rank calculation, or rank 0 in multi-rank setup
         call logger%info(" ")
         call logger%info("Running unfragmented calculation")
         call logger%info("  Calculation type: "//calc_type_to_string(calc_type))
         call logger%info(" ")
         if (present(driver_config)) then
            call unfragmented_calculation(sys_geom, method, calc_type, bonds, result_out, &
                                          driver_config%hessian%temperature, driver_config%hessian%pressure)
         else
            call unfragmented_calculation(sys_geom, method, calc_type, bonds, result_out)
         end if
      else if (sys_geom%total_atoms > 0) then
         ! Multi-molecule mode: non-zero rank with a molecule
         call logger%verbose("Rank "//to_char(world_comm%rank())//": Running unfragmented calculation")
         if (present(driver_config)) then
            call unfragmented_calculation(sys_geom, method, calc_type, bonds, result_out, &
                                          driver_config%hessian%temperature, driver_config%hessian%pressure)
         else
            call unfragmented_calculation(sys_geom, method, calc_type, bonds, result_out)
         end if
      end if
   end subroutine run_unfragmented_calculation
Call graph
run_unfragmented_calculation calls info, distributed_unfragmented_hessian, unfragmented_calculation, calc_type_to_string, to_char, verbose
distributed_unfragmented_hessian calls distributed_unfragmented_hessian, barrier, hessian_coordinator, hessian_worker
unfragmented_calculation calls unfragmented_calculation, info, to_char, cart_disp, configuration, eigenvalues, error, fc_mdyne, force_constants, frequencies, do_fragment_work, ir_intensities, check_duplicate_atoms, compute_thermochemistry, compute_vibrational_analysis, compute_vibrational_frequencies, energy_total, error_get_full_trace, error_get_message, error_has_error, fragment_compute_nelec, print_unfragmented_json, print_vibrational_analysis, print_vibrational_json, result_destroy, projected_hessian, reduced_masses
do_fragment_work calls do_fragment_work, calc_type_to_string, to_char, configuration, error_set, energy_reset, error_add_context, method_type_to_string, print_fragment_xyz, xtb_calc_energy, xtb_calc_gradient, xtb_calc_hessian
hessian_coordinator calls hessian_coordinator, info, to_char, cart_disp, configuration, fc_mdyne, force_constants, ir_intensities, compute_thermochemistry, compute_vibrational_analysis, compute_vibrational_frequencies, energy_total, fragment_compute_nelec, print_unfragmented_json, print_vibrational_analysis, print_vibrational_json, result_destroy, reduced_masses, get_elapsed_time, iprobe, irecv, isend, finite_diff_dipole_derivatives, finite_diff_hessian_from_gradients, method_type_to_string, xtb_calc_gradient, recv, start, vib_freqs
hessian_worker calls hessian_worker, to_char, error, error_get_message, fragment_compute_nelec, result_destroy, abort_comm, irecv, isend, copy_and_displace_geometry, method_type_to_string, xtb_calc_gradient, send
check_duplicate_atoms calls to_char, error, element_number_to_symbol, error_set
compute_thermochemistry calls compute_electronic_entropy, compute_moments_of_inertia, compute_partition_functions, compute_rotational_constants, compute_rotational_thermo, compute_translational_thermo, compute_vibrational_thermo, compute_zpe
compute_vibrational_analysis calls compute_vibrational_frequencies, compute_cartesian_displacements, compute_force_constants, compute_ir_intensities, compute_reduced_masses
compute_vibrational_frequencies calls error, pic_syev, mass_weight_hessian, project_translation_rotation, warning
energy_total calls mp2_total
error_get_full_trace calls error_has_error
print_unfragmented_json calls info, error, energy_total, add, create_object, destroy, initialize, get_basename, get_output_json_filename
print_vibrational_analysis calls info, compute_thermochemistry, element_number_to_symbol, print_thermochemistry, warning
print_vibrational_json calls energy_total, write_vibrational_json_impl
result_destroy calls result_reset
compute_cartesian_displacements calls element_mass
compute_ir_intensities calls element_mass
compute_moments_of_inertia calls to_char, pic_syev, warning, element_mass
compute_reduced_masses calls element_mass
compute_zpe calls to_char, warning
mass_weight_hessian calls element_mass
print_thermochemistry calls info
project_translation_rotation calls pic_gesvd, element_mass
result_reset calls energy_reset, error_clear
write_vibrational_json_impl calls info, error, add, create_object, destroy, initialize, get_basename, get_output_json_filename
run_calculation calls run_unfragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations