run_multi_molecule_calculations – metalquicha
run_multi_molecule_calculations Subroutine
141 statements
Source File
public subroutine run_multi_molecule_calculations(resources, mqc_config)
Uses
mqc_config_adapter
mqc_io_helpers
mqc_error
mqc_config_parser
mqc_json
Run calculations for multiple molecules with MPI parallelization Each molecule is independent, so assign one molecule per rank
Arguments
Type Intent Optional Attributes Name
type(resources_t), intent(in) :: resources
type(mqc_config_t), intent(in) :: mqc_config
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: color
type(driver_config_t), private :: config
type(error_t), private :: error
logical, private :: has_fragmented_molecules
integer, private :: imol
character(len=256), private, allocatable :: individual_json_files(:)
character(len=:), private, allocatable :: mol_name
type(resources_t), private :: mol_resources
integer, private :: molecules_processed
integer, private :: my_rank
integer, private :: num_ranks
type(system_geometry_t), private :: sys_geom
Source Code
   subroutine run_multi_molecule_calculations(resources, mqc_config)
      !! Run calculations for multiple molecules with MPI parallelization
      !! Each molecule is independent, so assign one molecule per rank
      use mqc_config_parser, only: mqc_config_t
      use mqc_config_adapter, only: config_to_system_geometry
      use mqc_error, only: error_t
      use mqc_io_helpers, only: set_molecule_suffix, get_output_json_filename
      use mqc_json, only: merge_multi_molecule_json
      type(resources_t), intent(in) :: resources
      type(mqc_config_t), intent(in) :: mqc_config
      type(driver_config_t) :: config
      type(system_geometry_t) :: sys_geom
      type(resources_t) :: mol_resources
      type(error_t) :: error
      integer :: imol, my_rank, num_ranks, color
      integer :: molecules_processed
      character(len=:), allocatable :: mol_name
      logical :: has_fragmented_molecules
      character(len=256), allocatable :: individual_json_files(:)
      my_rank = resources%mpi_comms%world_comm%rank()
      num_ranks = resources%mpi_comms%world_comm%size()
      ! Allocate array to track individual JSON files for merging
      allocate (individual_json_files(mqc_config%nmol))
      ! Check if any molecules have fragments (nlevel > 0)
      has_fragmented_molecules = .false.
      do imol = 1, mqc_config%nmol
         if (mqc_config%molecules(imol)%nfrag > 0) then
            has_fragmented_molecules = .true.
            exit
         end if
      end do
      if (my_rank == 0) then
         call logger%info(" ")
         call logger%info("============================================")
         call logger%info("Multi-molecule mode: "//to_char(mqc_config%nmol)//" molecules")
         call logger%info("MPI ranks: "//to_char(num_ranks))
         if (has_fragmented_molecules) then
            call logger%info("Mode: Sequential execution (fragmented molecules detected)")
            call logger%info("  Each molecule will use all "//to_char(num_ranks)//" rank(s) for its calculation")
         else if (num_ranks == 1) then
            call logger%info("Mode: Sequential execution (single rank)")
         else if (num_ranks > mqc_config%nmol) then
            call logger%info("Mode: Parallel execution (one molecule per rank)")
            call logger%info("Note: More ranks than molecules - ranks "//to_char(mqc_config%nmol)// &
                             " to "//to_char(num_ranks - 1)//" will be idle")
         else
            call logger%info("Mode: Parallel execution (one molecule per rank)")
         end if
         call logger%info("============================================")
         call logger%info(" ")
      end if
      ! Determine execution mode:
      ! 1. Sequential: Single rank OR fragmented molecules (each molecule needs all ranks)
      ! 2. Parallel: Multiple ranks AND unfragmented molecules (distribute molecules across ranks)
      molecules_processed = 0
      if (num_ranks == 1 .or. has_fragmented_molecules) then
         ! Sequential mode: process all molecules one after another
         ! Each molecule uses all available ranks for its calculation
         do imol = 1, mqc_config%nmol
            ! Determine molecule name for logging
            if (allocated(mqc_config%molecules(imol)%name)) then
               mol_name = mqc_config%molecules(imol)%name
            else
               mol_name = "molecule_"//to_char(imol)
            end if
            if (my_rank == 0) then
               call logger%info(" ")
               call logger%info("--------------------------------------------")
               call logger%info("Processing molecule "//to_char(imol)//"/"//to_char(mqc_config%nmol)//": "//mol_name)
               call logger%info("--------------------------------------------")
            end if
            ! Convert to driver configuration for this molecule
            call config_to_driver(mqc_config, config, molecule_index=imol)
            ! Convert geometry for this molecule
            call config_to_system_geometry(mqc_config, sys_geom, error, molecule_index=imol)
            if (error%has_error()) then
               call error%add_context("mqc_driver:run_multi_molecule_calculation")
               if (my_rank == 0) then
                  call logger%error("Error converting geometry for "//mol_name//": "//error%get_full_trace())
               end if
               call abort_comm(resources%mpi_comms%world_comm, 1)
            end if
            ! Set output filename suffix for this molecule
            call set_molecule_suffix("_"//trim(mol_name))
            ! Run calculation for this molecule
            call run_calculation(resources, config, sys_geom, mqc_config%molecules(imol)%bonds)
            ! Track the JSON filename for later merging
            individual_json_files(imol) = get_output_json_filename()
            ! Clean up for this molecule
            call sys_geom%destroy()
            if (my_rank == 0) then
               call logger%info("Completed molecule "//to_char(imol)//"/"//to_char(mqc_config%nmol)//": "//mol_name)
            end if
            molecules_processed = molecules_processed + 1
         end do
      else
         ! Multiple ranks: distribute molecules across ranks in round-robin fashion
         molecules_processed = 0
         do imol = 1, mqc_config%nmol
            ! This rank processes molecules where (imol - 1) mod num_ranks == my_rank
            if (mod(imol - 1, num_ranks) == my_rank) then
               ! Determine molecule name for logging
               if (allocated(mqc_config%molecules(imol)%name)) then
                  mol_name = mqc_config%molecules(imol)%name
               else
                  mol_name = "molecule_"//to_char(imol)
               end if
               call logger%info(" ")
               call logger%info("--------------------------------------------")
               call logger%info("Rank "//to_char(my_rank)//": Processing molecule "//to_char(imol)// &
                                "/"//to_char(mqc_config%nmol)//": "//mol_name)
               call logger%info("--------------------------------------------")
               ! Convert to driver configuration for this molecule
               call config_to_driver(mqc_config, config, molecule_index=imol)
               ! Convert geometry for this molecule
               call config_to_system_geometry(mqc_config, sys_geom, error, molecule_index=imol)
               if (error%has_error()) then
                  call error%add_context("mqc_driver:run_multi_molecule_calculation")
  call logger%error("Rank "//to_char(my_rank)//": Error converting geometry for "//mol_name//": "//error%get_full_trace())
                  call abort_comm(resources%mpi_comms%world_comm, 1)
               end if
               ! Set output filename suffix for this molecule
               call set_molecule_suffix("_"//trim(mol_name))
               ! Run calculation for this molecule (all ranks write JSON in parallel mode)
               call run_calculation(resources, config, sys_geom, mqc_config%molecules(imol)%bonds, &
                                    all_ranks_write_json=.true.)
               ! Track the JSON filename for later merging
               individual_json_files(imol) = get_output_json_filename()
               ! Clean up for this molecule
               call sys_geom%destroy()
               call logger%info("Rank "//to_char(my_rank)//": Completed molecule "//to_char(imol)// &
                                "/"//to_char(mqc_config%nmol)//": "//mol_name)
               molecules_processed = molecules_processed + 1
            end if
         end do
         if (molecules_processed == 0) then
            ! Idle rank - no molecules assigned
            call logger%verbose("Rank "//to_char(my_rank)//": No molecules assigned (idle)")
         end if
      end if
      ! Synchronize all ranks
      call resources%mpi_comms%world_comm%barrier()
      ! In parallel execution, rank 0 needs to reconstruct all JSON filenames for merging
      ! since each rank only populated its own entry
      if (my_rank == 0 .and. num_ranks > 1 .and. .not. has_fragmented_molecules) then
         ! Rank 0 constructs filenames for all molecules
         do imol = 1, mqc_config%nmol
            ! Get molecule name
            if (allocated(mqc_config%molecules(imol)%name)) then
               mol_name = mqc_config%molecules(imol)%name
            else
               mol_name = "molecule_"//to_char(imol)
            end if
            ! Construct JSON filename pattern: output_<basename>_<molname>.json
            ! This mirrors what get_output_json_filename() returns after set_molecule_suffix()
            call set_molecule_suffix("_"//trim(mol_name))
            individual_json_files(imol) = get_output_json_filename()
         end do
      end if
      ! Merge individual JSON files into one combined file (rank 0 only)
      if (my_rank == 0) then
         call merge_multi_molecule_json(individual_json_files, mqc_config%nmol)
      end if
      if (my_rank == 0) then
         call logger%info(" ")
         call logger%info("============================================")
         call logger%info("All "//to_char(mqc_config%nmol)//" molecules completed")
         if (has_fragmented_molecules) then
            call logger%info("Execution: Sequential (each molecule used all ranks)")
         else if (num_ranks == 1) then
            call logger%info("Execution: Sequential (single rank)")
         else if (num_ranks > mqc_config%nmol) then
           call logger%info("Execution: Parallel (active ranks: "//to_char(mqc_config%nmol)//"/"//to_char(num_ranks)//")")
         else
            call logger%info("Execution: Parallel (all ranks active)")
         end if
         call logger%info("============================================")
      end if
   end subroutine run_multi_molecule_calculations
Call graph
run_multi_molecule_calculations calls abort_comm, barrier, error, info, config_to_driver, config_to_system_geometry, error_add_context, error_get_full_trace, error_has_error, get_output_json_filename, merge_multi_molecule_json, run_calculation, set_molecule_suffix, system_destroy, to_char, verbose
config_to_system_geometry calls error_add_context, error_has_error, error_set, geometry_to_system_fragmented, geometry_to_system_unfragmented, molecule_to_system_geometry
error_get_full_trace calls error_has_error
merge_multi_molecule_json calls error, info, to_char, read_json_content
run_calculation calls info, to_char, omp_set_num_threads, json_output_data_destroy, run_fragmented_calculation, run_unfragmented_calculation, set_xtb_options, write_json_output, warning
geometry_to_system_fragmented calls initialize_fragmented_system
geometry_to_system_unfragmented calls element_symbol_to_number, to_bohr
json_output_data_destroy calls json_output_data_reset
molecule_to_system_geometry calls error_set, geometry_to_system_unfragmented, initialize_fragmented_system
read_json_content calls error, get_molecule_name
run_fragmented_calculation calls abort_comm, error, info, error_has_error, to_char, verbose, omp_set_num_threads, allgather, bcast, global_coordinator, node_coordinator, node_worker, serial_fragment_processor, leader, omp_get_max_threads, apply_distance_screening, binomial, combine, create_monomer_list, error_get_message, generate_fragment_list, get_nfrags, gmbe_enumerate_pie_terms, gmbe_pie_coordinator, serial_gmbe_pie_processor, sort_fragments_by_size
run_unfragmented_calculation calls info, to_char, verbose, distributed_unfragmented_hessian, unfragmented_calculation, calc_type_to_string
write_json_output calls error, write_gmbe_pie_json_impl, write_mbe_breakdown_json_impl, write_unfragmented_json_impl, write_vibrational_json_impl
distributed_unfragmented_hessian calls distributed_unfragmented_hessian, barrier, hessian_coordinator, hessian_worker
global_coordinator calls global_coordinator, abort_comm, error, info, to_char, verbose, error_get_message, destroy, get_elapsed_time, iprobe, irecv, isend, result_irecv, start, allocate_dipole, allocate_gradient, allocate_hessian, debug, compute_mbe, send_fragment_to_node, send_fragment_to_worker
node_coordinator calls node_coordinator, abort_comm, error, to_char, error_get_message, iprobe, irecv, isend, result_irecv, result_isend, recv
node_worker calls node_worker, abort_comm, error, error_get_full_trace, error_has_error, to_char, do_fragment_work, irecv, isend, build_fragment_from_atom_list, fragment_destroy, build_fragment_from_indices, result_isend, recv
serial_fragment_processor calls serial_fragment_processor, error, info, error_get_full_trace, error_has_error, to_char, verbose, omp_set_num_threads, omp_get_max_threads, calc_type_to_string, error_get_message, configuration, get_elapsed_time, do_fragment_work, energy_total, fragment_destroy, start, build_fragment_from_indices, compute_mbe, mbe_result_allocate_dipole, mbe_result_allocate_gradient, mbe_result_allocate_hessian
unfragmented_calculation calls unfragmented_calculation, error, info, error_get_full_trace, error_has_error, to_char, error_get_message, cart_disp, configuration, fc_mdyne, force_constants, frequencies, do_fragment_work, compute_thermochemistry, compute_vibrational_analysis, energy_total, print_vibrational_analysis, reduced_masses, eigenvalues, ir_intensities, check_duplicate_atoms, compute_vibrational_frequencies, fragment_compute_nelec, result_destroy, projected_hessian
apply_distance_screening calls info, to_char, fragment_should_be_screened
combine calls combine_util
element_symbol_to_number calls to_lower, to_upper
generate_fragment_list calls combine
get_nfrags calls binomial
gmbe_enumerate_pie_terms calls info, error_has_error, to_char, error_set, atom_list, compute_polymer_atoms, dfs_pie_accumulate
gmbe_pie_coordinator calls abort_comm, error, info, to_char, verbose, error_get_message, cart_disp, configuration, fc_mdyne, force_constants, frequencies, get_elapsed_time, iprobe, irecv, isend, build_fragment_from_atom_list, compute_thermochemistry, compute_vibrational_analysis, energy_total, fragment_destroy, print_vibrational_analysis, redistribute_cap_dipole_derivatives, redistribute_cap_gradients, redistribute_cap_hessian, result_irecv, send_pie_term_to_node, send_pie_term_to_worker, reduced_masses, start
initialize_fragmented_system calls error_add_context, error_has_error, element_symbol_to_number, to_bohr, check_fragment_overlap
serial_gmbe_pie_processor calls error, info, error_get_full_trace, error_has_error, to_char, verbose, calc_type_to_string, error_get_message, cart_disp, configuration, fc_mdyne, force_constants, frequencies, do_fragment_work, build_fragment_from_atom_list, compute_thermochemistry, compute_vibrational_analysis, energy_total, fragment_destroy, print_vibrational_analysis, redistribute_cap_dipole_derivatives, redistribute_cap_gradients, redistribute_cap_hessian, reduced_masses
sort_fragments_by_size calls info, sort_index
write_gmbe_pie_json_impl calls error, info, get_output_json_filename, add, create_array, create_object, destroy, initialize, get_basename
write_mbe_breakdown_json_impl calls error, info, get_output_json_filename, warning, add, create_array, create_object, destroy, initialize, get_basename, get_frag_level_name
write_unfragmented_json_impl calls error, info, get_output_json_filename, add, create_object, destroy, initialize, get_basename
write_vibrational_json_impl calls error, info, get_output_json_filename, add, create_object, destroy, initialize, get_basename
do_fragment_work calls do_fragment_work
build_fragment_from_atom_list calls error_add_context, error_has_error, add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, fragment_compute_nelec
check_fragment_overlap calls to_char, error_set
combine_util calls combine_util
compute_thermochemistry calls compute_electronic_entropy, compute_moments_of_inertia, compute_partition_functions, compute_rotational_constants, compute_rotational_thermo, compute_translational_thermo, compute_vibrational_thermo, compute_zpe
compute_vibrational_analysis calls compute_cartesian_displacements, compute_force_constants, compute_ir_intensities, compute_reduced_masses, compute_vibrational_frequencies
dfs_pie_accumulate calls error_has_error, dfs_pie_accumulate, new_clique, atom_sets_equal, grow_pie_storage, intersect_atom_lists, test_intersect
energy_total calls mp2_total
fragment_destroy calls basis_set_destroy
fragment_should_be_screened calls calculate_monomer_distance, get_next_combination
print_vibrational_analysis calls info, warning, compute_thermochemistry, element_number_to_symbol, print_thermochemistry
result_irecv calls irecv, recv
send_pie_term_to_node calls isend
send_pie_term_to_worker calls isend
main calls run_multi_molecule_calculations