run_fragmented_calculation – metalquicha
run_fragmented_calculation Subroutine
136 statements
Source File
private subroutine run_fragmented_calculation(resources, method, calc_type, sys_geom, max_level, allow_overlapping_fragments, max_intersection_level, bonds, driver_config)
Handle fragmented calculation (nlevel > 0)
Generates fragments, distributes work across MPI processes organized in nodes, and coordinates many-body expansion calculation using hierarchical parallelism. If allow_overlapping_fragments=true, uses GMBE with intersection correction.
Arguments
Type Intent Optional Attributes Name
type(resources_t), intent(in) :: resources
Resources container (MPI comms, etc.)
integer(kind=int32), intent(in) :: method
Quantum chemistry method
integer(kind=int32), intent(in) :: calc_type
Calculation type
type(system_geometry_t), intent(in) :: sys_geom
System geometry and fragment info
integer, intent(in) :: max_level
Maximum fragment level for MBE
logical, intent(in) :: allow_overlapping_fragments
Use GMBE for overlapping fragments
integer, intent(in) :: max_intersection_level
Maximum k-way intersection depth for GMBE
type(bond_t), intent(in), optional :: bonds(:)
Bond connectivity information
type(driver_config_t), intent(in) :: driver_config
Driver configuration with cutoffs
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private, allocatable :: all_node_leader_ranks(:)
Node leader status for all ranks
integer, private :: global_node_rank
Global rank if this process leads a node, -1 otherwise
integer, private :: i
Loop counters
integer, private, allocatable :: intersection_levels(:)
Level k of each intersection (n_intersections)
integer, private, allocatable :: intersection_sets(:,:)
k-tuples for each intersection (n_monomers, n_intersections)
integer, private, allocatable :: intersections(:,:)
Intersection atom lists (max_atoms, n_intersections)
integer, private :: j
Loop counters
integer, private, allocatable :: monomers(:)
Temporary monomer list for fragment generation
integer(kind=int64), private :: n_expected_frags
Expected number of fragments based on combinatorics (int64 to handle large systems)
integer, private :: n_intersections
Counts for GMBE
integer, private :: n_monomers
Counts for GMBE
integer(kind=int64), private :: n_pie_terms
Number of unique PIE terms
integer, private :: n_primaries
Number of primary polymers
integer(kind=int64), private :: n_primaries_i64
For binomial calculation
integer(kind=int64), private :: n_rows
Number of rows needed for polymers array (int64 to handle large systems)
integer, private, allocatable :: node_leader_ranks(:)
Ranks of processes that lead each node
integer, private :: num_nodes
Number of compute nodes
integer, private, allocatable :: pie_atom_sets(:,:)
Unique atom sets (max_atoms, n_pie_terms)
integer, private, allocatable :: pie_coefficients(:)
PIE coefficient for each term
type(error_t), private :: pie_error
Error from PIE enumeration
integer, private, allocatable :: polymers(:,:)
Fragment composition array (fragment, monomer_indices)
integer(kind=int64), private :: total_fragments
Total number of fragments generated (int64 to handle large systems)
Source Code
   subroutine run_fragmented_calculation(resources, method, calc_type, sys_geom, max_level, &
                                         allow_overlapping_fragments, max_intersection_level, bonds, driver_config)
      !! Handle fragmented calculation (nlevel > 0)
      !!
      !! Generates fragments, distributes work across MPI processes organized in nodes,
      !! and coordinates many-body expansion calculation using hierarchical parallelism.
      !! If allow_overlapping_fragments=true, uses GMBE with intersection correction.
      type(resources_t), intent(in) :: resources  !! Resources container (MPI comms, etc.)
      integer(int32), intent(in) :: method  !! Quantum chemistry method
      integer(int32), intent(in) :: calc_type  !! Calculation type
      type(system_geometry_t), intent(in) :: sys_geom  !! System geometry and fragment info
      integer, intent(in) :: max_level    !! Maximum fragment level for MBE
      logical, intent(in) :: allow_overlapping_fragments  !! Use GMBE for overlapping fragments
      integer, intent(in) :: max_intersection_level  !! Maximum k-way intersection depth for GMBE
      type(bond_t), intent(in), optional :: bonds(:)  !! Bond connectivity information
      type(driver_config_t), intent(in) :: driver_config  !! Driver configuration with cutoffs
      integer(int64) :: total_fragments  !! Total number of fragments generated (int64 to handle large systems)
      integer, allocatable :: polymers(:, :)  !! Fragment composition array (fragment, monomer_indices)
      integer :: num_nodes   !! Number of compute nodes
      integer :: i, j        !! Loop counters
      integer, allocatable :: node_leader_ranks(:)  !! Ranks of processes that lead each node
      integer, allocatable :: monomers(:)     !! Temporary monomer list for fragment generation
      integer(int64) :: n_expected_frags  !! Expected number of fragments based on combinatorics (int64 to handle large systems)
      integer(int64) :: n_rows      !! Number of rows needed for polymers array (int64 to handle large systems)
      integer :: global_node_rank  !! Global rank if this process leads a node, -1 otherwise
      integer, allocatable :: all_node_leader_ranks(:)  !! Node leader status for all ranks
      ! GMBE-specific variables (old approach - kept for compatibility)
      integer, allocatable :: intersections(:, :)  !! Intersection atom lists (max_atoms, n_intersections)
      integer, allocatable :: intersection_sets(:, :)  !! k-tuples for each intersection (n_monomers, n_intersections)
      integer, allocatable :: intersection_levels(:)  !! Level k of each intersection (n_intersections)
      integer :: n_intersections, n_monomers  !! Counts for GMBE
      ! GMBE PIE-based variables (new approach)
      integer :: n_primaries  !! Number of primary polymers
      integer(int64) :: n_primaries_i64  !! For binomial calculation
      integer, allocatable :: pie_atom_sets(:, :)  !! Unique atom sets (max_atoms, n_pie_terms)
      integer, allocatable :: pie_coefficients(:)  !! PIE coefficient for each term
      integer(int64) :: n_pie_terms  !! Number of unique PIE terms
      type(error_t) :: pie_error  !! Error from PIE enumeration
      ! Generate fragments
      if (resources%mpi_comms%world_comm%rank() == 0) then
         if (allow_overlapping_fragments) then
            ! GMBE mode: PIE-based inclusion-exclusion
            ! GMBE(1): primaries are monomers
            ! GMBE(N): primaries are N-mers (e.g., dimers for N=2)
            ! Generate primaries
            if (max_level == 1) then
               ! GMBE(1): primaries are base monomers
               n_primaries = sys_geom%n_monomers
               allocate (polymers(n_primaries, 1))
               do i = 1, n_primaries
                  polymers(i, 1) = i
               end do
            else
               ! GMBE(N): primaries are all C(M, N) N-tuples
               n_primaries_i64 = binomial(sys_geom%n_monomers, max_level)
               n_primaries = int(n_primaries_i64)
               allocate (monomers(sys_geom%n_monomers))
               allocate (polymers(n_primaries, max_level))
               polymers = 0
               call create_monomer_list(monomers)
               total_fragments = 0_int64
               call combine(monomers, sys_geom%n_monomers, max_level, polymers, total_fragments)
               n_primaries = int(total_fragments)
               deallocate (monomers)
               ! Apply distance-based screening to primaries if cutoffs are provided
               if (max_level > 1) then
                  ! Only screen if primaries are n-mers (not for GMBE(1) where primaries are monomers)
                  total_fragments = int(n_primaries, int64)
                  call apply_distance_screening(polymers, total_fragments, sys_geom, driver_config, max_level)
                  n_primaries = int(total_fragments)
               end if
               ! Sort primaries by size (largest first)
               ! TODO: Currently disabled - see comment in MBE section above
               ! total_fragments = int(n_primaries, int64)
               call sort_fragments_by_size(polymers, total_fragments, max_level)
            end if
            call logger%info("Generated "//to_char(n_primaries)//" primary "//to_char(max_level)//"-mers for GMBE("// &
                             to_char(max_level)//")")
            ! Use DFS to enumerate PIE terms with coefficients
            call gmbe_enumerate_pie_terms(sys_geom, polymers, n_primaries, max_level, max_intersection_level, &
                                          pie_atom_sets, pie_coefficients, n_pie_terms, pie_error)
            if (pie_error%has_error()) then
               call logger%error("GMBE PIE enumeration failed: "//pie_error%get_message())
               call abort_comm(resources%mpi_comms%world_comm, 1)
            end if
            call logger%info("GMBE PIE enumeration complete: "//to_char(n_pie_terms)//" unique subsystems to evaluate")
            ! For now: total_fragments = n_pie_terms (each PIE term is a subsystem to evaluate)
            total_fragments = n_pie_terms
         else
            ! Standard MBE mode
            ! Calculate expected number of fragments
            n_expected_frags = get_nfrags(sys_geom%n_monomers, max_level)
            n_rows = n_expected_frags
            ! Allocate monomer list and polymers array
            allocate (monomers(sys_geom%n_monomers))
            allocate (polymers(n_rows, max_level))
            polymers = 0
            ! Create monomer list [1, 2, 3, ..., n_monomers]
            call create_monomer_list(monomers)
            ! Generate all fragments (includes monomers in polymers array)
            total_fragments = 0_int64
            ! First add monomers
            do i = 1, sys_geom%n_monomers
               total_fragments = total_fragments + 1_int64
               polymers(total_fragments, 1) = i
            end do
            ! Then add n-mers for n >= 2
            call generate_fragment_list(monomers, max_level, polymers, total_fragments)
            deallocate (monomers)
            ! Apply distance-based screening if cutoffs are provided
            call apply_distance_screening(polymers, total_fragments, sys_geom, driver_config, max_level)
            ! Sort fragments by size (largest first) for better load balancing
            ! TODO: Currently disabled - MBE assembly is now order-independent (uses nested loops),
            ! but sorting still causes "Subset not found" errors in real validation cases.
            ! Unit tests pass with arbitrary order, so there may be an issue with the hash table
            ! or fragment generation in production code. Needs investigation.
            call sort_fragments_by_size(polymers, total_fragments, max_level)
            call logger%info("Generated fragments:")
            call logger%info("  Total fragments: "//to_char(total_fragments))
            call logger%info("  Max level: "//to_char(max_level))
         end if
      end if
      ! Broadcast total_fragments to all ranks
      call bcast(resources%mpi_comms%world_comm, total_fragments, 1, 0)
      ! Determine node leaders
      global_node_rank = -1
      if (resources%mpi_comms%node_comm%rank() == 0) global_node_rank = resources%mpi_comms%world_comm%rank()
      allocate (all_node_leader_ranks(resources%mpi_comms%world_comm%size()))
      call allgather(resources%mpi_comms%world_comm, global_node_rank, all_node_leader_ranks)
      num_nodes = count(all_node_leader_ranks /= -1)
      if (resources%mpi_comms%world_comm%rank() == 0) then
         call logger%info("Running with "//to_char(num_nodes)//" node(s)")
      end if
      allocate (node_leader_ranks(num_nodes))
      i = 0
      do j = 1, resources%mpi_comms%world_comm%size()
         if (all_node_leader_ranks(j) /= -1) then
            i = i + 1
            node_leader_ranks(i) = all_node_leader_ranks(j)
         end if
      end do
      deallocate (all_node_leader_ranks)
      ! Execute appropriate role
      if (resources%mpi_comms%world_comm%size() == 1) then
         ! Single rank: process fragments serially
         call logger%info("Running in serial mode (single MPI rank)")
         if (allow_overlapping_fragments) then
            ! GMBE serial processing with PIE coefficients
          call serial_gmbe_pie_processor(pie_atom_sets, pie_coefficients, n_pie_terms, sys_geom, method, calc_type, bonds)
         else
            ! Standard MBE serial processing
            call serial_fragment_processor(total_fragments, polymers, max_level, sys_geom, method, calc_type, bonds)
         end if
      else if (resources%mpi_comms%world_comm%leader() .and. resources%mpi_comms%node_comm%leader()) then
         ! Global coordinator (rank 0, node leader on node 0)
         call omp_set_num_threads(omp_get_max_threads())
         call logger%verbose("Rank 0: Acting as global coordinator")
         if (allow_overlapping_fragments) then
            ! GMBE MPI processing - PIE-based approach
            call gmbe_pie_coordinator(resources, pie_atom_sets, pie_coefficients, n_pie_terms, &
                                      node_leader_ranks, num_nodes, sys_geom, method, calc_type, bonds)
         else
            ! Standard MBE MPI processing
            call global_coordinator(resources, total_fragments, polymers, max_level, &
                                    node_leader_ranks, num_nodes, sys_geom, calc_type, bonds)
         end if
      else if (resources%mpi_comms%node_comm%leader()) then
         ! Node coordinator (node leader on other nodes)
         call logger%verbose("Rank "//to_char(resources%mpi_comms%world_comm%rank())//": Acting as node coordinator")
         ! Node coordinator works for both MBE and GMBE (receives fragments from global coordinator)
         call node_coordinator(resources, calc_type)
      else
         ! Worker
         call omp_set_num_threads(1)
         call logger%verbose("Rank "//to_char(resources%mpi_comms%world_comm%rank())//": Acting as worker")
         ! Worker processes work for both MBE and GMBE (fragment_type distinguishes them)
         call node_worker(resources, sys_geom, method, calc_type, bonds)
      end if
      ! Cleanup
      if (resources%mpi_comms%world_comm%rank() == 0) then
         if (allocated(polymers)) deallocate (polymers)
         if (allocated(node_leader_ranks)) deallocate (node_leader_ranks)
         if (allocated(intersections)) deallocate (intersections)
         if (allocated(intersection_sets)) deallocate (intersection_sets)
         if (allocated(intersection_levels)) deallocate (intersection_levels)
         if (allocated(pie_atom_sets)) deallocate (pie_atom_sets)
         if (allocated(pie_coefficients)) deallocate (pie_coefficients)
      end if
   end subroutine run_fragmented_calculation
Call graph
run_fragmented_calculation calls abort_comm, allgather, bcast, error, info, global_coordinator, node_coordinator, node_worker, serial_fragment_processor, leader, omp_get_max_threads, omp_set_num_threads, apply_distance_screening, binomial, combine, create_monomer_list, error_get_message, error_has_error, generate_fragment_list, get_nfrags, gmbe_enumerate_pie_terms, gmbe_pie_coordinator, serial_gmbe_pie_processor, sort_fragments_by_size, to_char, verbose
global_coordinator calls global_coordinator, abort_comm, error, info, error_get_message, to_char, verbose, get_elapsed_time, iprobe, irecv, isend, result_irecv, start, allocate_dipole, allocate_gradient, allocate_hessian, debug, destroy, compute_mbe, send_fragment_to_node, send_fragment_to_worker
node_coordinator calls node_coordinator, abort_comm, error, error_get_message, to_char, iprobe, irecv, isend, result_irecv, result_isend, recv
node_worker calls node_worker, abort_comm, error, error_has_error, to_char, do_fragment_work, irecv, isend, build_fragment_from_atom_list, error_get_full_trace, fragment_destroy, build_fragment_from_indices, result_isend, recv
serial_fragment_processor calls serial_fragment_processor, error, info, omp_get_max_threads, omp_set_num_threads, error_get_message, error_has_error, to_char, verbose, configuration, get_elapsed_time, do_fragment_work, calc_type_to_string, energy_total, error_get_full_trace, fragment_destroy, start, build_fragment_from_indices, compute_mbe, mbe_result_allocate_dipole, mbe_result_allocate_gradient, mbe_result_allocate_hessian
apply_distance_screening calls info, to_char, calculate_monomer_distance
combine calls combine_util
generate_fragment_list calls combine
get_nfrags calls binomial
gmbe_enumerate_pie_terms calls info, error_has_error, to_char, atom_list, compute_polymer_atoms, dfs_pie_accumulate, error_set
gmbe_pie_coordinator calls abort_comm, error, info, error_get_message, to_char, verbose, cart_disp, configuration, fc_mdyne, force_constants, frequencies, get_elapsed_time, iprobe, irecv, isend, build_fragment_from_atom_list, compute_thermochemistry, compute_vibrational_analysis, energy_total, fragment_destroy, print_gmbe_pie_json, print_vibrational_analysis, print_vibrational_json_mbe, redistribute_cap_dipole_derivatives, redistribute_cap_gradients, redistribute_cap_hessian, result_irecv, send_pie_term_to_node, send_pie_term_to_worker, reduced_masses, start
serial_gmbe_pie_processor calls error, info, error_get_message, error_has_error, to_char, verbose, cart_disp, configuration, fc_mdyne, force_constants, frequencies, do_fragment_work, build_fragment_from_atom_list, calc_type_to_string, compute_thermochemistry, compute_vibrational_analysis, energy_total, error_get_full_trace, fragment_destroy, print_gmbe_pie_json, print_vibrational_analysis, print_vibrational_json_mbe, redistribute_cap_dipole_derivatives, redistribute_cap_gradients, redistribute_cap_hessian, reduced_masses
sort_fragments_by_size calls info, sort_index
do_fragment_work calls do_fragment_work, to_char, configuration, calc_type_to_string, error_set, error_add_context, energy_reset, method_type_to_string, print_fragment_xyz, xtb_calc_energy, xtb_calc_gradient, xtb_calc_hessian
build_fragment_from_atom_list calls error_has_error, add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
calculate_monomer_distance calls to_angstrom
combine_util calls combine_util
compute_thermochemistry calls compute_electronic_entropy, compute_moments_of_inertia, compute_partition_functions, compute_rotational_constants, compute_rotational_thermo, compute_translational_thermo, compute_vibrational_thermo, compute_zpe
compute_vibrational_analysis calls compute_cartesian_displacements, compute_force_constants, compute_ir_intensities, compute_reduced_masses, compute_vibrational_frequencies
dfs_pie_accumulate calls error_has_error, dfs_pie_accumulate, new_clique, atom_sets_equal, grow_pie_storage, intersect_atom_lists, test_intersect
energy_total calls mp2_total
error_get_full_trace calls error_has_error
fragment_destroy calls basis_set_destroy
print_gmbe_pie_json calls error, info, add, create_array, create_object, destroy, initialize, get_basename, get_output_json_filename
print_vibrational_analysis calls info, compute_thermochemistry, element_number_to_symbol, print_thermochemistry, warning
print_vibrational_json_mbe calls write_vibrational_json_impl
result_irecv calls irecv, recv
send_pie_term_to_node calls isend
send_pie_term_to_worker calls isend
basis_set_destroy calls atomic_basis_destroy
build_fragment_from_indices calls error_has_error, calculate_monomer_distance, add_hydrogen_caps, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
check_duplicate_atoms calls error, to_char, error_set, element_number_to_symbol
compute_cartesian_displacements calls element_mass
compute_ir_intensities calls element_mass
compute_mbe calls abort_comm, error, info, to_char, cart_disp, configuration, fc_mdyne, force_constants, frequencies, compute_thermochemistry, compute_vibrational_analysis, energy_total, print_vibrational_analysis, print_vibrational_json_mbe, reduced_masses, warning, get_message, has_error, build_mbe_lookup_table, compute_mbe_delta, compute_mbe_dipole, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian, fragment_lookup_destroy, map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, print_detailed_breakdown, print_detailed_breakdown_json, print_mbe_energy_breakdown, print_mbe_gradient_info
compute_moments_of_inertia calls to_char, warning, pic_syev, element_mass
compute_reduced_masses calls element_mass
compute_vibrational_frequencies calls error, warning, pic_syev, mass_weight_hessian, project_translation_rotation
compute_zpe calls to_char, warning
grow_pie_storage calls to_char, error_set
print_thermochemistry calls info
result_isend calls isend, send
send_fragment_to_node calls isend
send_fragment_to_worker calls isend
write_vibrational_json_impl calls error, info, add, create_object, destroy, initialize, get_basename, get_output_json_filename
atomic_basis_destroy calls cgto_destroy
build_mbe_lookup_table calls error_has_error, to_char, get_elapsed_time, start, debug, error_add_context, fragment_lookup_init, fragment_lookup_insert
compute_mbe_delta calls abort_comm, error, fragment_lookup_find, get_next_combination
compute_mbe_dipole calls abort_comm, error, fragment_lookup_find, get_next_combination
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives, fragment_lookup_find, get_next_combination
compute_mbe_gradient calls abort_comm, error, map_fragment_to_system_gradient, fragment_lookup_find, get_next_combination
compute_mbe_hessian calls map_fragment_to_system_hessian, fragment_lookup_find, get_next_combination
energy_reset calls mp2_reset
map_fragment_to_system_dipole_derivatives calls fragment_destroy, redistribute_cap_dipole_derivatives, build_fragment_from_indices
map_fragment_to_system_gradient calls abort_comm, error, error_has_error, configuration, error_get_full_trace, fragment_destroy, redistribute_cap_gradients, debug, build_fragment_from_indices
map_fragment_to_system_hessian calls fragment_destroy, redistribute_cap_hessian, build_fragment_from_indices
mass_weight_hessian calls element_mass
print_detailed_breakdown calls verbose, warning, header, level_name, get_frag_level_name
print_detailed_breakdown_json calls error, info, add, create_array, create_object, destroy, initialize, get_basename, get_output_json_filename, warning, get_frag_level_name
print_fragment_xyz calls info, to_char, element_number_to_symbol, to_angstrom
print_mbe_energy_breakdown calls info
print_mbe_gradient_info calls info, to_char
project_translation_rotation calls element_mass, pic_gesvd
xtb_calc_energy calls energy_total, error_set, dpat, new, new_gfn1_calculator, new_gfn2_calculator, new_wavefunction, add_solvation_to_calc, qat, xtb_singlepoint
xtb_calc_gradient calls energy_total, error_set, dpat, new, new_gfn1_calculator, new_gfn2_calculator, new_wavefunction, add_solvation_to_calc, qat, xtb_singlepoint
xtb_calc_hessian calls info, to_char, error_set, xtb_calc_gradient, finite_diff_dipole_derivatives, finite_diff_hessian_from_gradients, generate_perturbed_geometries, result_destroy
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations