send_fragment_to_worker – metalquicha
send_fragment_to_worker Subroutine
21 statements
Source File
private subroutine send_fragment_to_worker(node_comm, fragment_idx, polymers, dest_rank)
Send fragment data to local worker Uses int64 for fragment_idx to handle large fragment indices that overflow int32.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: node_comm
integer(kind=int64), intent(in) :: fragment_idx
integer, intent(in) :: polymers(:,:)
integer, intent(in) :: dest_rank
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: fragment_idx_int32
integer, private, allocatable :: fragment_indices(:)
integer, private :: fragment_size
type(request_t), private :: req(3)
Source Code
   subroutine send_fragment_to_worker(node_comm, fragment_idx, polymers, dest_rank)
      !! Send fragment data to local worker
      !! Uses int64 for fragment_idx to handle large fragment indices that overflow int32.
      type(comm_t), intent(in) :: node_comm
      integer(int64), intent(in) :: fragment_idx
      integer, intent(in) :: dest_rank
      integer, intent(in) :: polymers(:, :)
      integer :: fragment_size
      integer, allocatable :: fragment_indices(:)
      type(request_t) :: req(3)
      integer(int32) :: fragment_idx_int32
      fragment_size = count(polymers(fragment_idx, :) > 0)
      allocate (fragment_indices(fragment_size))
      fragment_indices = polymers(fragment_idx, 1:fragment_size)
      ! TODO: serialize the data for better performance
      fragment_idx_int32 = int(fragment_idx, kind=int32)
      call isend(node_comm, fragment_idx_int32, dest_rank, TAG_WORKER_FRAGMENT, req(1))
      call isend(node_comm, fragment_size, dest_rank, TAG_WORKER_FRAGMENT, req(2))
      call isend(node_comm, fragment_indices, dest_rank, TAG_WORKER_FRAGMENT, req(3))
      ! Wait for all sends to complete
      call wait(req(1))
      call wait(req(2))
      call wait(req(3))
      deallocate (fragment_indices)
   end subroutine send_fragment_to_worker
Call graph
send_fragment_to_worker calls isend
global_coordinator calls send_fragment_to_worker
run_fragmented_calculation calls global_coordinator
run_calculation calls run_fragmented_calculation
main calls run_calculation