send_fragment_to_node – metalquicha
send_fragment_to_node Subroutine
25 statements
Source File
subroutine send_fragment_to_node(world_comm, fragment_idx, polymers, dest_rank)
Send fragment data to remote node coordinator Uses int64 for fragment_idx to handle large fragment indices that overflow int32.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: world_comm
integer(kind=int64), intent(in) :: fragment_idx
integer, intent(in) :: polymers(:,:)
integer, intent(in) :: dest_rank
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int64), private :: fragment_idx_int64
integer, private, allocatable :: fragment_indices(:)
integer, private :: fragment_size
integer(kind=int32), private :: fragment_type
type(request_t), private :: req(4)
Source Code
   subroutine send_fragment_to_node(world_comm, fragment_idx, polymers, dest_rank)
      !! Send fragment data to remote node coordinator
      !! Uses int64 for fragment_idx to handle large fragment indices that overflow int32.
      type(comm_t), intent(in) :: world_comm
      integer(int64), intent(in) :: fragment_idx
      integer, intent(in) :: dest_rank
      integer, intent(in) :: polymers(:, :)
      integer :: fragment_size
      integer(int32) :: fragment_type
      integer, allocatable :: fragment_indices(:)
      type(request_t) :: req(4)
      integer(int64) :: fragment_idx_int64
      fragment_size = count(polymers(fragment_idx, :) > 0)
      allocate (fragment_indices(fragment_size))
      fragment_indices = polymers(fragment_idx, 1:fragment_size)
      ! Standard MBE always uses monomer indices (type 0)
      fragment_type = 0
      ! TODO: serialize the data for better performance
      fragment_idx_int64 = int(fragment_idx, kind=int64)
      call isend(world_comm, fragment_idx_int64, dest_rank, TAG_NODE_FRAGMENT, req(1))
      call isend(world_comm, fragment_type, dest_rank, TAG_NODE_FRAGMENT, req(2))
      call isend(world_comm, fragment_size, dest_rank, TAG_NODE_FRAGMENT, req(3))
      call isend(world_comm, fragment_indices, dest_rank, TAG_NODE_FRAGMENT, req(4))
      ! Wait for all sends to complete
      call wait(req(1))
      call wait(req(2))
      call wait(req(3))
      call wait(req(4))
      deallocate (fragment_indices)
   end subroutine send_fragment_to_node
Call graph
send_fragment_to_node calls isend
global_coordinator calls send_fragment_to_node, global_coordinator
run_fragmented_calculation calls global_coordinator
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation