serial_fragment_processor – metalquicha
serial_fragment_processor Module Subroutine
86 statements
Source File
module subroutine serial_fragment_processor(total_fragments, polymers, max_level, sys_geom, method, calc_type, bonds) Interface →
Uses
mqc_error
mqc_result_types
Process all fragments serially in single-rank mode This is used when running with only 1 MPI rank
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: total_fragments
integer, intent(in) :: polymers(:,:)
integer, intent(in) :: max_level
type(system_geometry_t), intent(in) :: sys_geom
integer(kind=int32), intent(in) :: method
integer(kind=int32), intent(in) :: calc_type
type(bond_t), intent(in), optional :: bonds(:)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: calc_type_local
type(timer_type), private :: coord_timer
integer, private :: current_log_level
type(error_t), private :: error
integer(kind=int64), private :: frag_idx
integer, private, allocatable :: fragment_indices(:)
integer, private :: fragment_size
integer, private :: iatom
type(mbe_result_t), private :: mbe_result
type(physical_fragment_t), private :: phys_frag
type(calculation_result_t), private, allocatable :: results(:)
Source Code
   module subroutine serial_fragment_processor(total_fragments, polymers, max_level, sys_geom, method, calc_type, bonds)
      !! Process all fragments serially in single-rank mode
      !! This is used when running with only 1 MPI rank
      use mqc_error, only: error_t
      use mqc_result_types, only: mbe_result_t
      integer(int64), intent(in) :: total_fragments
      integer, intent(in) :: polymers(:, :), max_level
      type(system_geometry_t), intent(in) :: sys_geom
      integer(int32), intent(in) :: method
      integer(int32), intent(in) :: calc_type
      type(bond_t), intent(in), optional :: bonds(:)
      integer(int64) :: frag_idx
      integer :: fragment_size, current_log_level, iatom
      integer, allocatable :: fragment_indices(:)
      type(calculation_result_t), allocatable :: results(:)
      type(mbe_result_t) :: mbe_result
      type(physical_fragment_t) :: phys_frag
      type(timer_type) :: coord_timer
      integer(int32) :: calc_type_local
      type(error_t) :: error
      calc_type_local = calc_type
      call logger%info("Processing "//to_char(total_fragments)//" fragments serially...")
      call logger%info("  Calculation type: "//calc_type_to_string(calc_type_local))
      allocate (results(total_fragments))
      call omp_set_num_threads(1)
      call coord_timer%start()
      do frag_idx = 1_int64, total_fragments
         fragment_size = count(polymers(frag_idx, :) > 0)
         allocate (fragment_indices(fragment_size))
         fragment_indices = polymers(frag_idx, 1:fragment_size)
         call build_fragment_from_indices(sys_geom, fragment_indices, phys_frag, error, bonds)
         if (error%has_error()) then
            call logger%error(error%get_full_trace())
            error stop "Failed to build fragment in serial processing"
         end if
         call do_fragment_work(frag_idx, results(frag_idx), method, phys_frag, calc_type=calc_type_local)
         ! Check for calculation errors
         if (results(frag_idx)%has_error) then
            call logger%error("Fragment "//to_char(frag_idx)//" calculation failed: "// &
                              results(frag_idx)%error%get_message())
            error stop "Fragment calculation failed in serial processing"
         end if
         ! Debug output for gradients
         if (calc_type_local == CALC_TYPE_GRADIENT .and. results(frag_idx)%has_gradient) then
            call logger%configuration(level=current_log_level)
            if (current_log_level >= verbose_level) then
               block
                  character(len=512) :: debug_line
                  integer :: iatom_local
                  write (debug_line, '(a,i0,a,*(i0,1x))') "Fragment ", frag_idx, " monomers: ", fragment_indices
                  call logger%verbose(trim(debug_line))
                  write (debug_line, '(a,f25.15)') "  Energy: ", results(frag_idx)%energy%total()
                  call logger%verbose(trim(debug_line))
                  write (debug_line, '(a,f25.15)') "  Gradient norm: ", sqrt(sum(results(frag_idx)%gradient**2))
                  call logger%verbose(trim(debug_line))
                  if (size(results(frag_idx)%gradient, 2) <= 20) then
                     call logger%verbose("  Fragment gradient:")
                     do iatom_local = 1, size(results(frag_idx)%gradient, 2)
                        write (debug_line, '(a,i3,a,3f20.12)') "    Atom ", iatom_local, ": ", &
                           results(frag_idx)%gradient(1, iatom_local), &
                           results(frag_idx)%gradient(2, iatom_local), &
                           results(frag_idx)%gradient(3, iatom_local)
                        call logger%verbose(trim(debug_line))
                     end do
                  end if
               end block
            end if
         end if
         call phys_frag%destroy()
         deallocate (fragment_indices)
         if (mod(frag_idx, max(1_int64, total_fragments/10)) == 0 .or. frag_idx == total_fragments) then
            call logger%info("  Processed "//to_char(frag_idx)//"/"//to_char(total_fragments)// &
                             " fragments ["//to_char(coord_timer%get_elapsed_time())//" s]")
         end if
      end do
      call coord_timer%stop()
      call logger%info("Time to evaluate all fragments "//to_char(coord_timer%get_elapsed_time())//" s")
      call omp_set_num_threads(omp_get_max_threads())
      call logger%info("All fragments processed")
      call logger%info(" ")
      call logger%info("Computing Many-Body Expansion (MBE)...")
      call coord_timer%start()
      ! Allocate mbe_result components based on calc_type
      call mbe_result%allocate_dipole()  ! Always compute dipole
      if (calc_type_local == CALC_TYPE_HESSIAN) then
         call mbe_result%allocate_gradient(sys_geom%total_atoms)
         call mbe_result%allocate_hessian(sys_geom%total_atoms)
      else if (calc_type_local == CALC_TYPE_GRADIENT) then
         call mbe_result%allocate_gradient(sys_geom%total_atoms)
      end if
      call compute_mbe(polymers, total_fragments, max_level, results, mbe_result, sys_geom, bonds)
      call mbe_result%destroy()
      call coord_timer%stop()
      call logger%info("Time to compute MBE "//to_char(coord_timer%get_elapsed_time())//" s")
      deallocate (results)
   end subroutine serial_fragment_processor
Call graph
serial_fragment_processor calls configuration, error, get_elapsed_time, info, do_fragment_work, omp_get_max_threads, omp_set_num_threads, build_fragment_from_indices, calc_type_to_string, compute_mbe, energy_total, error_get_full_trace, error_get_message, error_has_error, fragment_destroy, mbe_result_allocate_dipole, mbe_result_allocate_gradient, mbe_result_allocate_hessian, start, to_char, verbose, serial_fragment_processor
do_fragment_work calls do_fragment_work, configuration, calc_type_to_string, to_char, error_add_context, energy_reset, error_set, method_type_to_string, print_fragment_xyz, xtb_calc_energy, xtb_calc_gradient, xtb_calc_hessian
build_fragment_from_indices calls error_has_error, add_hydrogen_caps, calculate_monomer_distance, check_duplicate_atoms, count_hydrogen_caps, error_add_context, fragment_compute_nelec
compute_mbe calls configuration, error, info, energy_total, to_char, abort_comm, cart_disp, fc_mdyne, force_constants, frequencies, get_message, has_error, build_mbe_lookup_table, compute_mbe_delta, compute_mbe_dipole, compute_mbe_dipole_derivatives, compute_mbe_gradient, compute_mbe_hessian, compute_thermochemistry, compute_vibrational_analysis, fragment_lookup_destroy, map_fragment_to_system_dipole_derivatives, map_fragment_to_system_gradient, map_fragment_to_system_hessian, print_detailed_breakdown, print_detailed_breakdown_json, print_mbe_energy_breakdown, print_mbe_gradient_info, print_vibrational_analysis, print_vibrational_json_mbe, reduced_masses, warning
energy_total calls mp2_total
error_get_full_trace calls error_has_error
fragment_destroy calls basis_set_destroy
basis_set_destroy calls atomic_basis_destroy
build_mbe_lookup_table calls get_elapsed_time, error_has_error, start, to_char, error_add_context, debug, fragment_lookup_init, fragment_lookup_insert
calculate_monomer_distance calls to_angstrom
check_duplicate_atoms calls error, to_char, element_number_to_symbol, error_set
compute_mbe_delta calls error, abort_comm, fragment_lookup_find, get_next_combination
compute_mbe_dipole calls error, abort_comm, fragment_lookup_find, get_next_combination
compute_mbe_dipole_derivatives calls map_fragment_to_system_dipole_derivatives, fragment_lookup_find, get_next_combination
compute_mbe_gradient calls error, abort_comm, map_fragment_to_system_gradient, fragment_lookup_find, get_next_combination
compute_mbe_hessian calls map_fragment_to_system_hessian, fragment_lookup_find, get_next_combination
compute_thermochemistry calls compute_electronic_entropy, compute_moments_of_inertia, compute_partition_functions, compute_rotational_constants, compute_rotational_thermo, compute_translational_thermo, compute_vibrational_thermo, compute_zpe
compute_vibrational_analysis calls compute_cartesian_displacements, compute_force_constants, compute_ir_intensities, compute_reduced_masses, compute_vibrational_frequencies
map_fragment_to_system_dipole_derivatives calls build_fragment_from_indices, fragment_destroy, redistribute_cap_dipole_derivatives
map_fragment_to_system_gradient calls configuration, error, build_fragment_from_indices, error_get_full_trace, error_has_error, fragment_destroy, abort_comm, debug, redistribute_cap_gradients
map_fragment_to_system_hessian calls build_fragment_from_indices, fragment_destroy, redistribute_cap_hessian
print_detailed_breakdown calls verbose, warning, header, level_name, get_frag_level_name
print_detailed_breakdown_json calls error, info, warning, add, create_array, create_object, destroy, initialize, get_basename, get_frag_level_name, get_output_json_filename
print_mbe_energy_breakdown calls info
print_mbe_gradient_info calls info, to_char
print_vibrational_analysis calls info, compute_thermochemistry, warning, element_number_to_symbol, print_thermochemistry
print_vibrational_json_mbe calls write_vibrational_json_impl
atomic_basis_destroy calls cgto_destroy
compute_cartesian_displacements calls element_mass
compute_ir_intensities calls element_mass
compute_moments_of_inertia calls to_char, warning, pic_syev, element_mass
compute_reduced_masses calls element_mass
compute_vibrational_frequencies calls error, warning, pic_syev, mass_weight_hessian, project_translation_rotation
compute_zpe calls to_char, warning
energy_reset calls mp2_reset
fragment_lookup_find calls fnv_1a_hash, arrays_equal_internal, sort
fragment_lookup_init calls next_prime_internal
fragment_lookup_insert calls error_set, fnv_1a_hash, sort
print_fragment_xyz calls info, to_char, element_number_to_symbol, to_angstrom
print_thermochemistry calls info
write_vibrational_json_impl calls error, info, add, create_object, destroy, initialize, get_basename, get_output_json_filename
xtb_calc_energy calls energy_total, error_set, dpat, new, new_gfn1_calculator, new_gfn2_calculator, new_wavefunction, add_solvation_to_calc, qat, xtb_singlepoint
xtb_calc_gradient calls energy_total, error_set, dpat, new, new_gfn1_calculator, new_gfn2_calculator, new_wavefunction, add_solvation_to_calc, qat, xtb_singlepoint
xtb_calc_hessian calls info, to_char, error_set, xtb_calc_gradient, finite_diff_dipole_derivatives, finite_diff_hessian_from_gradients, generate_perturbed_geometries, result_destroy
add_solvation_to_calc calls new_solvation, new_solvation_cds, new_solvation_shift, get_solvent_dielectric, push_back
generate_perturbed_geometries calls copy_and_displace_geometry
mass_weight_hessian calls element_mass
project_translation_rotation calls element_mass, pic_gesvd
result_destroy calls result_reset
run_fragmented_calculation calls serial_fragment_processor
run_calculation calls run_fragmented_calculation
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations