skip_to_end – metalquicha
skip_to_end Subroutine
15 statements
Source File
public subroutine skip_to_end(unit, error)
Skip lines until ‘end’ marker is found
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: unit
type(error_t), intent(out) :: error
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: io_stat
character(len=MAX_LINE_LEN), private :: line
Source Code
   subroutine skip_to_end(unit, error)
      !! Skip lines until 'end' marker is found
      integer, intent(in) :: unit
      type(error_t), intent(out) :: error
      character(len=MAX_LINE_LEN) :: line
      integer :: io_stat
      do
         read (unit, '(A)', iostat=io_stat) line
         if (io_stat /= 0) then
            call error%set(ERROR_IO, "Unexpected end of file while skipping section")
            return
         end if
         line = adjustl(line)
         if (trim(strip_comment(line)) == 'end') exit
      end do
   end subroutine skip_to_end
Call graph
skip_to_end calls error_set, strip_comment
parse_connectivity_generic calls skip_to_end, parse_connectivity_generic
parse_fragments_generic calls skip_to_end, parse_fragments_generic
parse_molecules_section calls skip_to_end, parse_single_molecule, parse_molecules_section
parse_single_molecule calls skip_to_end, parse_molecule_connectivity, parse_molecule_fragments
read_mqc_file calls skip_to_end, parse_molecules_section, parse_connectivity_section, parse_fragments_section
main calls read_mqc_file
parse_connectivity_section calls parse_connectivity_generic, parse_connectivity_section
parse_fragments_section calls parse_fragments_generic, parse_fragments_section
parse_molecule_connectivity calls parse_connectivity_generic
parse_molecule_fragments calls parse_fragments_generic