strip_comment – metalquicha
strip_comment Function
12 statements
Source File
public pure function strip_comment(line) result(stripped)
Remove comments (! or #) from a line and trim result
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: line
Return Value character(len=:), allocatable
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: comment_pos
Source Code
   pure function strip_comment(line) result(stripped)
      !! Remove comments (! or #) from a line and trim result
      character(len=*), intent(in) :: line
      character(len=:), allocatable :: stripped
      integer :: comment_pos
      ! Find first occurrence of ! or #
      comment_pos = index(line, '!')
      if (comment_pos == 0) comment_pos = index(line, '#')
      if (comment_pos > 0) then
         ! Comment found - take everything before it
         stripped = trim(adjustl(line(1:comment_pos - 1)))
      else
         ! No comment - use full line
         stripped = trim(adjustl(line))
      end if
   end function strip_comment
Call graph
parse_aimd_section calls strip_comment, parse_aimd_section
parse_connectivity_generic calls strip_comment, skip_to_end, parse_connectivity_generic
parse_driver_section calls strip_comment, parse_driver_section
parse_fragment calls strip_comment
parse_fragmentation_section calls strip_comment, parse_fragmentation_section
parse_fragments_generic calls strip_comment, parse_fragment, skip_to_end, parse_fragments_generic
parse_geometry_generic calls strip_comment, parse_geometry_generic
parse_hessian_section calls strip_comment, parse_hessian_section
parse_model_section calls strip_comment, parse_model_section
parse_molecules_section calls strip_comment, parse_single_molecule, skip_to_end, parse_molecules_section
parse_scf_section calls strip_comment, parse_scf_section
parse_schema_section calls strip_comment, parse_schema_section
parse_single_molecule calls strip_comment, skip_to_end, parse_molecule_connectivity, parse_molecule_fragments, parse_molecule_geometry, parse_molecule_structure
parse_structure_generic calls strip_comment, parse_structure_generic
parse_system_section calls strip_comment, parse_system_section
parse_xtb_section calls strip_comment, parse_xtb_section
skip_to_end calls strip_comment
read_mqc_file calls skip_to_end, parse_aimd_section, parse_driver_section, parse_fragmentation_section, parse_hessian_section, parse_model_section, parse_molecules_section, parse_scf_section, parse_schema_section, parse_system_section, parse_xtb_section, parse_connectivity_section, parse_fragments_section, parse_geometry_section, parse_structure_section
parse_connectivity_section calls parse_connectivity_generic, parse_connectivity_section
parse_fragments_section calls parse_fragments_generic, parse_fragments_section
parse_geometry_section calls parse_geometry_generic, parse_geometry_section
parse_molecule_connectivity calls parse_connectivity_generic
parse_molecule_fragments calls parse_fragments_generic
parse_molecule_geometry calls parse_geometry_generic
parse_molecule_structure calls parse_structure_generic
parse_structure_section calls parse_structure_generic, parse_structure_section
main calls read_mqc_file