strings_equal – metalquicha
strings_equal Function
5 statements
Source File
public pure function strings_equal(str1, str2) result(equal)
Compare two strings after trimming and adjusting (removing leading/trailing whitespace) Compare two strings for equality after trimming and adjusting (removing leading/trailing whitespace)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str1
character(len=*), intent(in) :: str2
Return Value logical
Called by
Source Code
   pure function strings_equal(str1, str2) result(equal)
      !! Compare two strings for equality after trimming and adjusting (removing leading/trailing whitespace)
      character(len=*), intent(in) :: str1, str2
      logical :: equal
      equal = trim(adjustl(str1)) == trim(adjustl(str2))
   end function strings_equal
Call graph
build_molecular_basis calls strings_equal, find_unique_strings, parse_element_basis
count_shells_for_element calls strings_equal
fill_element_basis calls strings_equal
find_unique_strings calls strings_equal
parse_element_basis calls count_shells_for_element, fill_element_basis