to_angstrom – metalquicha
to_angstrom Function
5 statements
Source File
public pure elemental function to_angstrom(bohr_value) result(angstrom_value)
Convert coordinate from Bohr to Angstrom
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: bohr_value
Return Value real(kind=dp)
Called by
Source Code
   pure elemental function to_angstrom(bohr_value) result(angstrom_value)
      !! Convert coordinate from Bohr to Angstrom
      real(dp), intent(in) :: bohr_value
      real(dp) :: angstrom_value
      angstrom_value = bohr_value*bohr_radius
   end function to_angstrom
Call graph
calculate_fragment_distances calls to_angstrom
calculate_monomer_distance calls to_angstrom
print_fragment_xyz calls to_angstrom
apply_distance_screening calls calculate_monomer_distance
build_fragment_from_indices calls calculate_monomer_distance
do_fragment_work calls print_fragment_xyz
compute_gmbe_energy_gradient calls build_fragment_from_indices
compute_gmbe_energy_gradient_hessian calls build_fragment_from_indices
map_fragment_to_system_gradient calls build_fragment_from_indices
map_fragment_to_system_hessian calls build_fragment_from_indices
node_worker calls build_fragment_from_indices, do_fragment_work
run_fragmented_calculation calls apply_distance_screening, node_worker, serial_fragment_processor, serial_gmbe_pie_processor
serial_fragment_processor calls build_fragment_from_indices, do_fragment_work, compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian
serial_gmbe_pie_processor calls do_fragment_work
unfragmented_calculation calls do_fragment_work
compute_mbe_energy_gradient calls map_fragment_to_system_gradient, compute_mbe_gradient
compute_mbe_energy_gradient_hessian calls map_fragment_to_system_gradient, map_fragment_to_system_hessian, compute_mbe_gradient, compute_mbe_hessian
compute_mbe_gradient calls map_fragment_to_system_gradient
compute_mbe_hessian calls map_fragment_to_system_hessian
run_calculation calls run_fragmented_calculation, run_unfragmented_calculation
run_unfragmented_calculation calls unfragmented_calculation
compute_energy_and_forces calls run_calculation
global_coordinator calls compute_mbe_energy_gradient, compute_mbe_energy_gradient_hessian
run_multi_molecule_calculations calls run_calculation
main calls run_calculation