to_bohr – metalquicha
to_bohr Function
5 statements
Source File
public pure elemental function to_bohr(angstrom_value) result(bohr_value)
Convert coordinate from Angstrom to Bohr
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: angstrom_value
Return Value real(kind=dp)
Called by
Source Code
   pure elemental function to_bohr(angstrom_value) result(bohr_value)
      !! Convert coordinate from Angstrom to Bohr
      real(dp), intent(in) :: angstrom_value
      real(dp) :: bohr_value
      bohr_value = angstrom_value/bohr_radius
   end function to_bohr
Call graph
geometry_to_system_fragmented calls to_bohr
geometry_to_system_unfragmented calls to_bohr
initialize_system_geometry calls to_bohr
config_to_system_geometry calls geometry_to_system_fragmented, geometry_to_system_unfragmented
geometry_to_system calls geometry_to_system_unfragmented
main calls config_to_system_geometry