write_json_output – metalquicha
write_json_output Subroutine
25 statements
Source File
public subroutine write_json_output(output_data)
THE single entry point for all JSON output
Dispatches to the appropriate JSON writer based on output_mode. This is the ONLY place in the codebase where JSON files are written.
Arguments
Type Intent Optional Attributes Name
type(json_output_data_t), intent(in) :: output_data
Calls
Called by
Source Code
   subroutine write_json_output(output_data)
      !! THE single entry point for all JSON output
      !!
      !! Dispatches to the appropriate JSON writer based on output_mode.
      !! This is the ONLY place in the codebase where JSON files are written.
      type(json_output_data_t), intent(in) :: output_data
      select case (output_data%output_mode)
      case (OUTPUT_MODE_UNFRAGMENTED)
         if (output_data%has_vibrational) then
            call write_vibrational_json_impl(output_data)
         else
            call write_unfragmented_json_impl(output_data)
         end if
      case (OUTPUT_MODE_MBE)
         if (output_data%has_vibrational) then
            call write_vibrational_json_impl(output_data)
         else
            call write_mbe_breakdown_json_impl(output_data)
         end if
      case (OUTPUT_MODE_GMBE_PIE)
         if (output_data%has_vibrational) then
            call write_vibrational_json_impl(output_data)
         else
            call write_gmbe_pie_json_impl(output_data)
         end if
      case default
         call logger%error("Unknown output mode in write_json_output")
      end select
   end subroutine write_json_output
Call graph
write_json_output calls error, write_gmbe_pie_json_impl, write_mbe_breakdown_json_impl, write_unfragmented_json_impl, write_vibrational_json_impl
write_gmbe_pie_json_impl calls error, add, create_array, create_object, destroy, info, initialize, get_basename, get_output_json_filename
write_mbe_breakdown_json_impl calls error, add, create_array, create_object, destroy, info, initialize, get_basename, get_frag_level_name, get_output_json_filename, warning
write_unfragmented_json_impl calls error, add, create_object, destroy, info, initialize, get_basename, get_output_json_filename
write_vibrational_json_impl calls error, add, create_object, destroy, info, initialize, get_basename, get_output_json_filename
run_calculation calls write_json_output
compute_energy_and_forces calls run_calculation
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations