xtb_has_solvation – metalquicha
xtb_has_solvation Function
4 statements
Source File
private pure function xtb_has_solvation(this)
Check if solvation is configured for XTB
Type Bound
xtb_config_t
Arguments
Type Intent Optional Attributes Name
class(xtb_config_t), intent(in) :: this
Return Value logical
Called by
Source Code
   pure logical function xtb_has_solvation(this)
      !! Check if solvation is configured for XTB
      class(xtb_config_t), intent(in) :: this
      xtb_has_solvation = len_trim(this%solvent) > 0 .or. this%dielectric > 0.0_dp
   end function xtb_has_solvation
Call graph
configure_xtb calls xtb_has_solvation
xtb_get_solvation_info calls xtb_has_solvation
config_log_settings calls xtb_get_solvation_info
factory_create calls configure_xtb
create_method calls factory_create
run_calculation calls config_log_settings
compute_energy_and_forces calls run_calculation
do_fragment_work calls create_method, do_fragment_work
hessian_coordinator calls create_method, hessian_coordinator
hessian_worker calls create_method, hessian_worker
run_multi_molecule_calculations calls run_calculation
main calls run_calculation, run_multi_molecule_calculations